// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type Account struct {
	Id int `json:"id"`
	Name string `json:"name"`
	ParentAccountId int `json:"parent_account_id"`
	RootAccountId int `json:"root_account_id"`
	Uuid string `json:"uuid"`
	WorkflowState string `json:"workflow_state"`
}

type AccountCalendar struct {
	AssetString string `json:"asset_string"`
	AutoSubscribe bool `json:"auto_subscribe"`
	CalendarEventUrl string `json:"calendar_event_url"`
	CanCreateCalendarEvents bool `json:"can_create_calendar_events"`
	CreateCalendarEventUrl string `json:"create_calendar_event_url"`
	Id int `json:"id"`
	Name string `json:"name"`
	NewCalendarEventUrl string `json:"new_calendar_event_url"`
	ParentAccountId int `json:"parent_account_id"`
	RootAccountId int `json:"root_account_id"`
	SubAccountCount int `json:"sub_account_count"`
	Type string `json:"type"`
	Visible bool `json:"visible"`
}

type AccountNotification struct {
	Author json.RawMessage `json:"author"`
	EndAt string `json:"end_at"`
	Icon string `json:"icon"`
	Message string `json:"message"`
	RoleIds json.RawMessage `json:"role_ids"`
	Roles json.RawMessage `json:"roles"`
	StartAt string `json:"start_at"`
	Subject string `json:"subject"`
}

type Admin struct {
	Id int `json:"id"`
	Role string `json:"role"`
	User json.RawMessage `json:"user"`
	WorkflowState string `json:"workflow_state"`
}

type AiExperience struct {
	CourseId int `json:"course_id"`
	Description string `json:"description"`
	Facts string `json:"facts"`
	Id int `json:"id"`
	LearningObjective string `json:"learning_objective"`
	PedagogicalGuidance string `json:"pedagogical_guidance"`
	Title string `json:"title"`
	WorkflowState string `json:"workflow_state"`
}

type AnonymousUserDisplay struct {
	AnonymousId string `json:"anonymous_id"`
	AvatarImageUrl string `json:"avatar_image_url"`
	DisplayName string `json:"display_name"`
}

type Answer struct {
	AnswerComments string `json:"answer_comments"`
	AnswerMatchLeft string `json:"answer_match_left"`
	AnswerMatchRight string `json:"answer_match_right"`
	AnswerText string `json:"answer_text"`
	AnswerWeight int `json:"answer_weight"`
	Approximate float64 `json:"approximate"`
	BlankId int `json:"blank_id"`
	End int `json:"end"`
	Exact int `json:"exact"`
	Id int `json:"id"`
	Margin int `json:"margin"`
	MatchingAnswerIncorrectMatches string `json:"matching_answer_incorrect_matches"`
	NumericalAnswerType string `json:"numerical_answer_type"`
	Precision int `json:"precision"`
	Start int `json:"start"`
	TextAfterAnswers string `json:"text_after_answers"`
}

type Appointment struct {
	EndAt string `json:"end_at"`
	Id int `json:"id"`
	StartAt string `json:"start_at"`
}

type AppointmentGroup struct {
	AllowObserverSignup bool `json:"allow_observer_signup"`
	Appointments json.RawMessage `json:"appointments"`
	AppointmentsCount int `json:"appointments_count"`
	ContextCodes json.RawMessage `json:"context_codes"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	EndAt string `json:"end_at"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	LocationAddress string `json:"location_address"`
	LocationName string `json:"location_name"`
	MaxAppointmentsPerParticipant int `json:"max_appointments_per_participant"`
	MinAppointmentsPerParticipant int `json:"min_appointments_per_participant"`
	NewAppointments json.RawMessage `json:"new_appointments"`
	ParticipantCount int `json:"participant_count"`
	ParticipantType string `json:"participant_type"`
	ParticipantVisibility string `json:"participant_visibility"`
	ParticipantsPerAppointment int `json:"participants_per_appointment"`
	RequiringAction bool `json:"requiring_action"`
	ReservedTimes json.RawMessage `json:"reserved_times"`
	StartAt string `json:"start_at"`
	SubContextCodes json.RawMessage `json:"sub_context_codes"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	WorkflowState string `json:"workflow_state"`
}

type Assessment struct {
	Id string `json:"id"`
	Key string `json:"key"`
	Title string `json:"title"`
}

type AssessmentQuestion struct {
	AnswerTolerance string `json:"answer_tolerance"`
	Answers json.RawMessage `json:"answers"`
	AssessmentQuestionBankId int `json:"assessment_question_bank_id"`
	CorrectComments string `json:"correct_comments"`
	CorrectCommentsHtml string `json:"correct_comments_html"`
	CreatedAt string `json:"created_at"`
	FormulaDecimalPlaces int `json:"formula_decimal_places"`
	Formulas json.RawMessage `json:"formulas"`
	Id int `json:"id"`
	IncorrectComments string `json:"incorrect_comments"`
	IncorrectCommentsHtml string `json:"incorrect_comments_html"`
	Matches json.RawMessage `json:"matches"`
	MatchingAnswerIncorrectMatches json.RawMessage `json:"matching_answer_incorrect_matches"`
	NeutralComments string `json:"neutral_comments"`
	NeutralCommentsHtml string `json:"neutral_comments_html"`
	PointsPossible float64 `json:"points_possible"`
	Position int `json:"position"`
	QuestionName string `json:"question_name"`
	QuestionText string `json:"question_text"`
	QuestionType string `json:"question_type"`
	Variables json.RawMessage `json:"variables"`
}

type AssessmentQuestionBank struct {
	AssessmentQuestionCount int `json:"assessment_question_count"`
	ContextCode string `json:"context_code"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	WorkflowState string `json:"workflow_state"`
}

type Assignment struct {
	AbGuid json.RawMessage `json:"ab_guid"`
	AllDates json.RawMessage `json:"all_dates"`
	AllowedAttempts int `json:"allowed_attempts"`
	AllowedExtensions json.RawMessage `json:"allowed_extensions"`
	AnnotatableAttachmentId int `json:"annotatable_attachment_id"`
	AnonymizeStudents bool `json:"anonymize_students"`
	AnonymousGrading bool `json:"anonymous_grading"`
	AnonymousInstructorAnnotations bool `json:"anonymous_instructor_annotations"`
	AnonymousPeerReviews bool `json:"anonymous_peer_reviews"`
	AnonymousSubmissions bool `json:"anonymous_submissions"`
	AssignmentGroupId int `json:"assignment_group_id"`
	AssignmentVisibility json.RawMessage `json:"assignment_visibility"`
	AutomaticPeerReviews bool `json:"automatic_peer_reviews"`
	CanDuplicate bool `json:"can_duplicate"`
	CanSubmit bool `json:"can_submit"`
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	DiscussionTopic json.RawMessage `json:"discussion_topic"`
	DueAt string `json:"due_at"`
	DueDateRequired bool `json:"due_date_required"`
	ExternalToolTagAttributes json.RawMessage `json:"external_tool_tag_attributes"`
	FinalGraderId int `json:"final_grader_id"`
	FreezeOnCopy bool `json:"freeze_on_copy"`
	Frozen bool `json:"frozen"`
	FrozenAttributes json.RawMessage `json:"frozen_attributes"`
	GradeGroupStudentsIndividually bool `json:"grade_group_students_individually"`
	GradedSubmissionsExist bool `json:"graded_submissions_exist"`
	GraderCommentsVisibleToGraders bool `json:"grader_comments_visible_to_graders"`
	GraderCount int `json:"grader_count"`
	GraderNamesVisibleToFinalGrader bool `json:"grader_names_visible_to_final_grader"`
	GradersAnonymousToGraders bool `json:"graders_anonymous_to_graders"`
	GradingStandardId int `json:"grading_standard_id"`
	GradingType string `json:"grading_type"`
	GroupCategoryId int `json:"group_category_id"`
	HasOverrides bool `json:"has_overrides"`
	HasSubmittedSubmissions bool `json:"has_submitted_submissions"`
	HideInGradebook bool `json:"hide_in_gradebook"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	ImportantDates bool `json:"important_dates"`
	InClosedGradingPeriod bool `json:"in_closed_grading_period"`
	IntegrationData json.RawMessage `json:"integration_data"`
	IntegrationId string `json:"integration_id"`
	IntraGroupPeerReviews bool `json:"intra_group_peer_reviews"`
	IsQuizAssignment bool `json:"is_quiz_assignment"`
	LockAt string `json:"lock_at"`
	LockExplanation string `json:"lock_explanation"`
	LockInfo json.RawMessage `json:"lock_info"`
	LockedForUser bool `json:"locked_for_user"`
	MaxNameLength int `json:"max_name_length"`
	ModeratedGrading bool `json:"moderated_grading"`
	Muted bool `json:"muted"`
	Name string `json:"name"`
	NeedsGradingCount int `json:"needs_grading_count"`
	NeedsGradingCountBySection json.RawMessage `json:"needs_grading_count_by_section"`
	OmitFromFinalGrade bool `json:"omit_from_final_grade"`
	OnlyVisibleToOverrides bool `json:"only_visible_to_overrides"`
	OriginalAssignmentId int `json:"original_assignment_id"`
	OriginalAssignmentName string `json:"original_assignment_name"`
	OriginalCourseId int `json:"original_course_id"`
	OriginalLtiResourceLinkId int `json:"original_lti_resource_link_id"`
	OriginalQuizId int `json:"original_quiz_id"`
	Overrides json.RawMessage `json:"overrides"`
	PeerReviewCount int `json:"peer_review_count"`
	PeerReviews bool `json:"peer_reviews"`
	PeerReviewsAssignAt string `json:"peer_reviews_assign_at"`
	PointsPossible float64 `json:"points_possible"`
	Position int `json:"position"`
	PostManually bool `json:"post_manually"`
	PostToSis bool `json:"post_to_sis"`
	Published bool `json:"published"`
	QuizId int `json:"quiz_id"`
	RequireLockdownBrowser bool `json:"require_lockdown_browser"`
	Rubric json.RawMessage `json:"rubric"`
	RubricSettings json.RawMessage `json:"rubric_settings"`
	ScoreStatistics json.RawMessage `json:"score_statistics"`
	Submission json.RawMessage `json:"submission"`
	SubmissionTypes json.RawMessage `json:"submission_types"`
	SubmissionsDownloadUrl string `json:"submissions_download_url"`
	TurnitinEnabled bool `json:"turnitin_enabled"`
	TurnitinSettings json.RawMessage `json:"turnitin_settings"`
	UnlockAt string `json:"unlock_at"`
	Unpublishable bool `json:"unpublishable"`
	UpdatedAt string `json:"updated_at"`
	UseRubricForGrading bool `json:"use_rubric_for_grading"`
	VericiteEnabled bool `json:"vericite_enabled"`
	WorkflowState string `json:"workflow_state"`
}

type AssignmentDate struct {
	Base bool `json:"base"`
	DueAt string `json:"due_at"`
	Id int `json:"id"`
	LockAt string `json:"lock_at"`
	Title string `json:"title"`
	UnlockAt string `json:"unlock_at"`
}

type AssignmentEvent struct {
	AllDay bool `json:"all_day"`
	AllDayDate string `json:"all_day_date"`
	Assignment json.RawMessage `json:"assignment"`
	AssignmentOverrides json.RawMessage `json:"assignment_overrides"`
	ContextCode string `json:"context_code"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	EndAt string `json:"end_at"`
	HtmlUrl string `json:"html_url"`
	Id string `json:"id"`
	ImportantDates bool `json:"important_dates"`
	Rrule string `json:"rrule"`
	SeriesHead bool `json:"series_head"`
	SeriesNaturalLanguage string `json:"series_natural_language"`
	StartAt string `json:"start_at"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	WorkflowState string `json:"workflow_state"`
}

type AssignmentExtension struct {
	AssignmentId int `json:"assignment_id"`
	ExtraAttempts int `json:"extra_attempts"`
	UserId int `json:"user_id"`
}

type AssignmentGroup struct {
	Assignments json.RawMessage `json:"assignments"`
	GroupWeight int `json:"group_weight"`
	Id int `json:"id"`
	IntegrationData json.RawMessage `json:"integration_data"`
	Name string `json:"name"`
	Position int `json:"position"`
	Rules json.RawMessage `json:"rules"`
	SisSourceId string `json:"sis_source_id"`
}

type AssignmentGroupAttributes struct {
	GroupWeight int `json:"group_weight"`
	Id int `json:"id"`
	IntegrationData json.RawMessage `json:"integration_data"`
	Name string `json:"name"`
	SisSourceId string `json:"sis_source_id"`
}

type AssignmentGroupGrade struct {
	Dropped json.RawMessage `json:"dropped"`
	GlobalId int `json:"global_id"`
	Grade float64 `json:"grade"`
	Id int `json:"id"`
	Possible float64 `json:"possible"`
	Score float64 `json:"score"`
	Weight float64 `json:"weight"`
}

type AssignmentOverride struct {
	AllDay bool `json:"all_day"`
	AllDayDate string `json:"all_day_date"`
	AssignmentId int `json:"assignment_id"`
	AttachmentId int `json:"attachment_id"`
	ContextModuleId int `json:"context_module_id"`
	CourseSectionId int `json:"course_section_id"`
	DiscussionTopicId int `json:"discussion_topic_id"`
	DueAt string `json:"due_at"`
	GroupId int `json:"group_id"`
	Id int `json:"id"`
	LockAt string `json:"lock_at"`
	QuizId int `json:"quiz_id"`
	StudentIds json.RawMessage `json:"student_ids"`
	Title string `json:"title"`
	UnlockAt string `json:"unlock_at"`
	WikiPageId int `json:"wiki_page_id"`
}

type AsyncApiErrorResponse struct {
	Errors json.RawMessage `json:"errors"`
}

type AsyncQueryResponse struct {
	PollUrl string `json:"poll_url"`
}

type AsyncQueryResultsResponse struct {
	Content string `json:"content"`
	ContentEncoding string `json:"content_encoding"`
	ContentType string `json:"content_type"`
	Filename string `json:"filename"`
}

type AsyncQueryStatusResponse struct {
	ErrorCode string `json:"error_code"`
	Format string `json:"format"`
	QueryId string `json:"query_id"`
	ResultsUrl string `json:"results_url"`
	Status string `json:"status"`
}

type AuthenticationEvent struct {
	AccountId int `json:"account_id"`
	CreatedAt string `json:"created_at"`
	EventType string `json:"event_type"`
	PseudonymId int `json:"pseudonym_id"`
	UserId int `json:"user_id"`
}

type AuthenticationProvider struct {
	AuthBase string `json:"auth_base"`
	AuthFilter string `json:"auth_filter"`
	AuthHost string `json:"auth_host"`
	AuthOverTls int `json:"auth_over_tls"`
	AuthPort int `json:"auth_port"`
	AuthType string `json:"auth_type"`
	AuthUsername string `json:"auth_username"`
	CertificateFingerprint string `json:"certificate_fingerprint"`
	FederatedAttributes json.RawMessage `json:"federated_attributes"`
	Id int `json:"id"`
	IdentifierFormat string `json:"identifier_format"`
	IdpEntityId string `json:"idp_entity_id"`
	JitProvisioning bool `json:"jit_provisioning"`
	LogInUrl string `json:"log_in_url"`
	LogOutUrl string `json:"log_out_url"`
	LoginAttribute string `json:"login_attribute"`
	MfaRequired bool `json:"mfa_required"`
	Position int `json:"position"`
	RequestedAuthnContext string `json:"requested_authn_context"`
	SigAlg string `json:"sig_alg"`
}

type AuthorizationJWT struct {
	Aud string `json:"aud"`
	Exp int `json:"exp"`
	Iat int `json:"iat"`
	Jti string `json:"jti"`
	Sub string `json:"sub"`
}

type Avatar struct {
	ContentType string `json:"content-type"`
	DisplayName string `json:"display_name"`
	Filename string `json:"filename"`
	Id int `json:"id"`
	Size int `json:"size"`
	Token string `json:"token"`
	Type string `json:"type"`
	Url string `json:"url"`
}

type BasicUser struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type BlackoutDate struct {
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	EndDate string `json:"end_date"`
	EventTitle string `json:"event_title"`
	Id int `json:"id"`
	StartDate string `json:"start_date"`
}

type BlockEditorTemplate struct {
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	EditorVersion string `json:"editor_version"`
	Id int `json:"id"`
	Name string `json:"name"`
	NodeTree string `json:"node_tree"`
	TemplateType string `json:"template_type"`
	UpdatedAt string `json:"updated_at"`
	WorkflowState string `json:"workflow_state"`
}

type BlueprintMigration struct {
	Comment string `json:"comment"`
	CreatedAt string `json:"created_at"`
	ExportsStartedAt string `json:"exports_started_at"`
	Id int `json:"id"`
	ImportsCompletedAt string `json:"imports_completed_at"`
	ImportsQueuedAt string `json:"imports_queued_at"`
	SubscriptionId int `json:"subscription_id"`
	TemplateId int `json:"template_id"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type BlueprintRestriction struct {
	AvailabilityDates bool `json:"availability_dates"`
	Content bool `json:"content"`
	DueDates bool `json:"due_dates"`
	Points bool `json:"points"`
}

type BlueprintSubscription struct {
	BlueprintCourse json.RawMessage `json:"blueprint_course"`
	Id int `json:"id"`
	TemplateId int `json:"template_id"`
}

type BlueprintTemplate struct {
	AssociatedCourseCount int `json:"associated_course_count"`
	CourseId int `json:"course_id"`
	Id int `json:"id"`
	LastExportCompletedAt string `json:"last_export_completed_at"`
	LatestMigration json.RawMessage `json:"latest_migration"`
}

type Bookmark struct {
	Data json.RawMessage `json:"data"`
	Id int `json:"id"`
	Name string `json:"name"`
	Position int `json:"position"`
	Url string `json:"url"`
}

type CalendarEvent struct {
	AllContextCodes string `json:"all_context_codes"`
	AllDay bool `json:"all_day"`
	AllDayDate string `json:"all_day_date"`
	AppointmentGroupId int `json:"appointment_group_id"`
	AppointmentGroupUrl string `json:"appointment_group_url"`
	AvailableSlots int `json:"available_slots"`
	BlackoutDate bool `json:"blackout_date"`
	ChildEvents json.RawMessage `json:"child_events"`
	ChildEventsCount int `json:"child_events_count"`
	ContextCode string `json:"context_code"`
	ContextName string `json:"context_name"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	EffectiveContextCode string `json:"effective_context_code"`
	EndAt string `json:"end_at"`
	Group string `json:"group"`
	Hidden bool `json:"hidden"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	ImportantDates bool `json:"important_dates"`
	LocationAddress string `json:"location_address"`
	LocationName string `json:"location_name"`
	OwnReservation bool `json:"own_reservation"`
	ParentEventId int `json:"parent_event_id"`
	ParticipantType string `json:"participant_type"`
	ParticipantsPerAppointment int `json:"participants_per_appointment"`
	ReserveUrl string `json:"reserve_url"`
	Reserved bool `json:"reserved"`
	Rrule string `json:"rrule"`
	SeriesHead bool `json:"series_head"`
	SeriesNaturalLanguage string `json:"series_natural_language"`
	SeriesUuid string `json:"series_uuid"`
	StartAt string `json:"start_at"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	User string `json:"user"`
	WorkflowState string `json:"workflow_state"`
}

type CalendarLink struct {
	Ics string `json:"ics"`
}

type ChangeRecord struct {
	AssetId int `json:"asset_id"`
	AssetName string `json:"asset_name"`
	AssetType string `json:"asset_type"`
	ChangeType string `json:"change_type"`
	Exceptions json.RawMessage `json:"exceptions"`
	HtmlUrl string `json:"html_url"`
	Locked bool `json:"locked"`
}

type Collaboration struct {
	CollaborationType string `json:"collaboration_type"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	DocumentId string `json:"document_id"`
	Id int `json:"id"`
	Title string `json:"title"`
	Type string `json:"type"`
	UpdateUrl string `json:"update_url"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	UserId int `json:"user_id"`
	UserName string `json:"user_name"`
}

type Collaborator struct {
	Id int `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

type ColumnDatum struct {
	Content string `json:"content"`
	UserId int `json:"user_id"`
}

type CommMessage struct {
	Body string `json:"body"`
	CreatedAt string `json:"created_at"`
	From string `json:"from"`
	FromName string `json:"from_name"`
	HtmlBody string `json:"html_body"`
	Id int `json:"id"`
	ReplyTo string `json:"reply_to"`
	SentAt string `json:"sent_at"`
	Subject string `json:"subject"`
	To string `json:"to"`
	WorkflowState string `json:"workflow_state"`
}

type CommunicationChannel struct {
	Address string `json:"address"`
	BounceCount int `json:"bounce_count"`
	Id int `json:"id"`
	LastBounceAt string `json:"last_bounce_at"`
	Position int `json:"position"`
	Type string `json:"type"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type CompletionRequirement struct {
	Completed bool `json:"completed"`
	MinPercentage int `json:"min_percentage"`
	MinScore int `json:"min_score"`
	Type string `json:"type"`
}

type Conference struct {
	Attendees json.RawMessage `json:"attendees"`
	ConferenceKey string `json:"conference_key"`
	ConferenceType string `json:"conference_type"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	Description string `json:"description"`
	Duration int `json:"duration"`
	EndedAt string `json:"ended_at"`
	HasAdvancedSettings bool `json:"has_advanced_settings"`
	Id int `json:"id"`
	Invitees json.RawMessage `json:"invitees"`
	JoinUrl string `json:"join_url"`
	LongRunning bool `json:"long_running"`
	Recordings json.RawMessage `json:"recordings"`
	StartedAt string `json:"started_at"`
	Title string `json:"title"`
	Url string `json:"url"`
	UserSettings json.RawMessage `json:"user_settings"`
	Users json.RawMessage `json:"users"`
}

type ConferenceRecording struct {
	CreatedAt string `json:"created_at"`
	DurationMinutes int `json:"duration_minutes"`
	PlaybackUrl string `json:"playback_url"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
}

type ContentDetails struct {
	DueAt string `json:"due_at"`
	LockAt string `json:"lock_at"`
	LockExplanation string `json:"lock_explanation"`
	LockInfo json.RawMessage `json:"lock_info"`
	LockedForUser bool `json:"locked_for_user"`
	PointsPossible int `json:"points_possible"`
	UnlockAt string `json:"unlock_at"`
}

type ContentExport struct {
	Attachment json.RawMessage `json:"attachment"`
	CreatedAt string `json:"created_at"`
	ExportType string `json:"export_type"`
	Id int `json:"id"`
	ProgressUrl string `json:"progress_url"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type ContentMigration struct {
	Attachment string `json:"attachment"`
	FinishedAt string `json:"finished_at"`
	Id int `json:"id"`
	MigrationIssuesUrl string `json:"migration_issues_url"`
	MigrationType string `json:"migration_type"`
	MigrationTypeTitle string `json:"migration_type_title"`
	PreAttachment string `json:"pre_attachment"`
	ProgressUrl string `json:"progress_url"`
	StartedAt string `json:"started_at"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type ContentShare struct {
	ContentExport json.RawMessage `json:"content_export"`
	ContentType string `json:"content_type"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	Name string `json:"name"`
	ReadState string `json:"read_state"`
	Receivers json.RawMessage `json:"receivers"`
	Sender json.RawMessage `json:"sender"`
	SourceCourse json.RawMessage `json:"source_course"`
	UpdatedAt string `json:"updated_at"`
	UserId int `json:"user_id"`
}

type ContextExternalTool struct {
	ActivityAssetProcessor json.RawMessage `json:"ActivityAssetProcessor"`
	ActivityAssetProcessorContribution json.RawMessage `json:"ActivityAssetProcessorContribution"`
	AccountNavigation json.RawMessage `json:"account_navigation"`
	AllowMembershipServiceAccess bool `json:"allow_membership_service_access"`
	AnalyticsHub json.RawMessage `json:"analytics_hub"`
	AssignmentEdit json.RawMessage `json:"assignment_edit"`
	AssignmentGroupMenu json.RawMessage `json:"assignment_group_menu"`
	AssignmentIndexMenu json.RawMessage `json:"assignment_index_menu"`
	AssignmentMenu json.RawMessage `json:"assignment_menu"`
	AssignmentSelection json.RawMessage `json:"assignment_selection"`
	AssignmentView json.RawMessage `json:"assignment_view"`
	Collaboration json.RawMessage `json:"collaboration"`
	ConferenceSelection json.RawMessage `json:"conference_selection"`
	ConsumerKey string `json:"consumer_key"`
	CourseAssignmentsMenu json.RawMessage `json:"course_assignments_menu"`
	CourseHomeSubNavigation json.RawMessage `json:"course_home_sub_navigation"`
	CourseNavigation json.RawMessage `json:"course_navigation"`
	CourseSettingsSubNavigation json.RawMessage `json:"course_settings_sub_navigation"`
	CreatedAt string `json:"created_at"`
	CustomFields json.RawMessage `json:"custom_fields"`
	DeploymentId string `json:"deployment_id"`
	Description string `json:"description"`
	DeveloperKeyId int `json:"developer_key_id"`
	DiscussionTopicIndexMenu json.RawMessage `json:"discussion_topic_index_menu"`
	DiscussionTopicMenu json.RawMessage `json:"discussion_topic_menu"`
	Domain string `json:"domain"`
	EditorButton json.RawMessage `json:"editor_button"`
	EstimatedDuration json.RawMessage `json:"estimated_duration"`
	FileIndexMenu json.RawMessage `json:"file_index_menu"`
	FileMenu json.RawMessage `json:"file_menu"`
	GlobalNavigation json.RawMessage `json:"global_navigation"`
	HomeworkSubmission json.RawMessage `json:"homework_submission"`
	IconUrl string `json:"icon_url"`
	Id int `json:"id"`
	IsRceFavorite bool `json:"is_rce_favorite"`
	IsTopNavFavorite bool `json:"is_top_nav_favorite"`
	LinkSelection json.RawMessage `json:"link_selection"`
	LtiRegistrationId int `json:"lti_registration_id"`
	MessageSettings json.RawMessage `json:"message_settings"`
	MigrationSelection json.RawMessage `json:"migration_selection"`
	ModuleGroupMenu json.RawMessage `json:"module_group_menu"`
	ModuleIndexMenu json.RawMessage `json:"module_index_menu"`
	ModuleIndexMenuModal json.RawMessage `json:"module_index_menu_modal"`
	ModuleMenu json.RawMessage `json:"module_menu"`
	ModuleMenuModal json.RawMessage `json:"module_menu_modal"`
	Name string `json:"name"`
	NotSelectable bool `json:"not_selectable"`
	PageIndexMenu json.RawMessage `json:"page_index_menu"`
	PageMenu json.RawMessage `json:"page_menu"`
	PostGrades json.RawMessage `json:"post_grades"`
	PreferSisEmail bool `json:"prefer_sis_email"`
	PrivacyLevel string `json:"privacy_level"`
	QuizIndexMenu json.RawMessage `json:"quiz_index_menu"`
	QuizMenu json.RawMessage `json:"quiz_menu"`
	ResourceSelection json.RawMessage `json:"resource_selection"`
	SelectionHeight int `json:"selection_height"`
	SelectionWidth int `json:"selection_width"`
	SimilarityDetection json.RawMessage `json:"similarity_detection"`
	StudentContextCard json.RawMessage `json:"student_context_card"`
	SubmissionTypeSelection json.RawMessage `json:"submission_type_selection"`
	ToolConfiguration json.RawMessage `json:"tool_configuration"`
	TopNavigation json.RawMessage `json:"top_navigation"`
	UnifiedToolId string `json:"unified_tool_id"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	UserNavigation json.RawMessage `json:"user_navigation"`
	Version string `json:"version"`
	WikiIndexMenu json.RawMessage `json:"wiki_index_menu"`
	WikiPageMenu json.RawMessage `json:"wiki_page_menu"`
	WorkflowState string `json:"workflow_state"`
}

type ContextExternalToolMessageSettings struct {
	CustomFields json.RawMessage `json:"custom_fields"`
	Enabled bool `json:"enabled"`
	TargetLinkUri string `json:"target_link_uri"`
	Type string `json:"type"`
}

type ContextExternalToolPlacement struct {
	AcceptMediaTypes string `json:"accept_media_types"`
	AllowFullscreen bool `json:"allow_fullscreen"`
	CanvasIconClass string `json:"canvas_icon_class"`
	CustomFields json.RawMessage `json:"custom_fields"`
	Default string `json:"default"`
	Description string `json:"description"`
	DisplayType string `json:"display_type"`
	Enabled bool `json:"enabled"`
	IconSvgPath64 string `json:"icon_svg_path_64"`
	IconUrl string `json:"icon_url"`
	Label string `json:"label"`
	Labels json.RawMessage `json:"labels"`
	LaunchHeight int `json:"launch_height"`
	LaunchWidth int `json:"launch_width"`
	MessageType string `json:"message_type"`
	OauthCompliant bool `json:"oauth_compliant"`
	PreferSisEmail bool `json:"prefer_sis_email"`
	RequireResourceSelection bool `json:"require_resource_selection"`
	RequiredPermissions string `json:"required_permissions"`
	RootAccountOnly bool `json:"root_account_only"`
	SelectionHeight int `json:"selection_height"`
	SelectionWidth int `json:"selection_width"`
	TargetLinkUri string `json:"target_link_uri"`
	Text string `json:"text"`
	Url string `json:"url"`
	UseTray bool `json:"use_tray"`
	Visibility string `json:"visibility"`
	WindowTarget string `json:"windowTarget"`
}

type ContextSearchResponse struct {
	Accounts json.RawMessage `json:"accounts"`
	Courses json.RawMessage `json:"courses"`
}

type Conversation struct {
	Audience json.RawMessage `json:"audience"`
	AudienceContexts json.RawMessage `json:"audience_contexts"`
	AvatarUrl string `json:"avatar_url"`
	ContextName string `json:"context_name"`
	Id int `json:"id"`
	LastMessage string `json:"last_message"`
	MessageCount int `json:"message_count"`
	Participants json.RawMessage `json:"participants"`
	Private bool `json:"private"`
	Properties json.RawMessage `json:"properties"`
	Starred bool `json:"starred"`
	StartAt string `json:"start_at"`
	Subject string `json:"subject"`
	Subscribed bool `json:"subscribed"`
	Visible bool `json:"visible"`
	WorkflowState string `json:"workflow_state"`
}

type ConversationParticipant struct {
	AvatarUrl string `json:"avatar_url"`
	FullName string `json:"full_name"`
	Id int `json:"id"`
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}

type Course struct {
	AccessRestrictedByDate bool `json:"access_restricted_by_date"`
	AccountId int `json:"account_id"`
	AllowStudentAssignmentEdits bool `json:"allow_student_assignment_edits"`
	AllowStudentForumAttachments bool `json:"allow_student_forum_attachments"`
	AllowWikiComments bool `json:"allow_wiki_comments"`
	ApplyAssignmentGroupWeights bool `json:"apply_assignment_group_weights"`
	Blueprint bool `json:"blueprint"`
	BlueprintRestrictions json.RawMessage `json:"blueprint_restrictions"`
	BlueprintRestrictionsByObjectType json.RawMessage `json:"blueprint_restrictions_by_object_type"`
	Calendar json.RawMessage `json:"calendar"`
	CourseCode string `json:"course_code"`
	CourseFormat string `json:"course_format"`
	CourseProgress json.RawMessage `json:"course_progress"`
	CreatedAt string `json:"created_at"`
	DefaultView string `json:"default_view"`
	EndAt string `json:"end_at"`
	EnrollmentTermId int `json:"enrollment_term_id"`
	Enrollments json.RawMessage `json:"enrollments"`
	GradePassbackSetting string `json:"grade_passback_setting"`
	GradingPeriods json.RawMessage `json:"grading_periods"`
	GradingStandardId int `json:"grading_standard_id"`
	HideFinalGrades bool `json:"hide_final_grades"`
	Id int `json:"id"`
	IntegrationId string `json:"integration_id"`
	IsPublic bool `json:"is_public"`
	IsPublicToAuthUsers bool `json:"is_public_to_auth_users"`
	License string `json:"license"`
	Locale string `json:"locale"`
	Name string `json:"name"`
	NeedsGradingCount int `json:"needs_grading_count"`
	OpenEnrollment bool `json:"open_enrollment"`
	OriginalName string `json:"original_name"`
	Permissions json.RawMessage `json:"permissions"`
	PublicDescription string `json:"public_description"`
	PublicSyllabus bool `json:"public_syllabus"`
	PublicSyllabusToAuth bool `json:"public_syllabus_to_auth"`
	RestrictEnrollmentsToCourseDates bool `json:"restrict_enrollments_to_course_dates"`
	RootAccountId int `json:"root_account_id"`
	SelfEnrollment bool `json:"self_enrollment"`
	SisCourseId string `json:"sis_course_id"`
	SisImportId int `json:"sis_import_id"`
	StartAt string `json:"start_at"`
	StorageQuotaMb int `json:"storage_quota_mb"`
	StorageQuotaUsedMb float64 `json:"storage_quota_used_mb"`
	SyllabusBody string `json:"syllabus_body"`
	Template bool `json:"template"`
	Term json.RawMessage `json:"term"`
	TimeZone string `json:"time_zone"`
	TotalStudents int `json:"total_students"`
	Uuid string `json:"uuid"`
	WorkflowState string `json:"workflow_state"`
}

type CourseAttributes struct {
	Id int `json:"id"`
	IntegrationId string `json:"integration_id"`
	Name string `json:"name"`
	SisId string `json:"sis_id"`
}

type CourseEpubExport struct {
	EpubExport json.RawMessage `json:"epub_export"`
	Id int `json:"id"`
	Name string `json:"name"`
}

type CourseEvent struct {
	CreatedAt string `json:"created_at"`
	EventData string `json:"event_data"`
	EventSource string `json:"event_source"`
	EventType string `json:"event_type"`
	Id string `json:"id"`
	Links json.RawMessage `json:"links"`
}

type CourseEventLink struct {
	CopiedFrom int `json:"copied_from"`
	CopiedTo int `json:"copied_to"`
	Course int `json:"course"`
	PageView string `json:"page_view"`
	SisBatch int `json:"sis_batch"`
	User int `json:"user"`
}

type CourseNickname struct {
	CourseId int `json:"course_id"`
	Name string `json:"name"`
	Nickname string `json:"nickname"`
}

type CoursePace struct {
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	EndDate string `json:"end_date"`
	ExcludeWeekends bool `json:"exclude_weekends"`
	HardEndDates bool `json:"hard_end_dates"`
	Id int `json:"id"`
	Modules json.RawMessage `json:"modules"`
	Progress json.RawMessage `json:"progress"`
	PublishedAt string `json:"published_at"`
	RootAccountId int `json:"root_account_id"`
	SelectedDaysToSkip json.RawMessage `json:"selected_days_to_skip"`
	StartDate string `json:"start_date"`
	UpdatedAt string `json:"updated_at"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type CourseProgress struct {
	CompletedAt string `json:"completed_at"`
	NextRequirementUrl string `json:"next_requirement_url"`
	RequirementCompletedCount int `json:"requirement_completed_count"`
	RequirementCount int `json:"requirement_count"`
}

type CourseQuizExtension struct {
	EndAt string `json:"end_at"`
	ExtraAttempts int `json:"extra_attempts"`
	ExtraTime int `json:"extra_time"`
	ManuallyUnlocked bool `json:"manually_unlocked"`
	UserId int `json:"user_id"`
}

type CreatedEventData struct {
	ConcludeAt json.RawMessage `json:"conclude_at"`
	CreatedSource string `json:"created_source"`
	IsPublic json.RawMessage `json:"is_public"`
	Name json.RawMessage `json:"name"`
	StartAt json.RawMessage `json:"start_at"`
}

type CustomColumn struct {
	Hidden bool `json:"hidden"`
	Id int `json:"id"`
	Position int `json:"position"`
	ReadOnly bool `json:"read_only"`
	TeacherNotes bool `json:"teacher_notes"`
	Title string `json:"title"`
}

type DataServiceEventTypes struct {
	EventCategory json.RawMessage `json:"EventCategory"`
}

type DataServiceSubscription struct {
	ContextId string `json:"ContextId"`
	ContextType string `json:"ContextType"`
	EventTypes json.RawMessage `json:"EventTypes"`
	Format string `json:"Format"`
	TransportMetadata string `json:"TransportMetadata"`
	TransportType string `json:"TransportType"`
}

type Day struct {
	Date string `json:"date"`
	Graders int `json:"graders"`
}

type DeveloperKey struct {
	AccessTokenCount int `json:"access_token_count"`
	AccountName string `json:"account_name"`
	AllowIncludes bool `json:"allow_includes"`
	ApiKey string `json:"api_key"`
	ClientCredentialsAudience string `json:"client_credentials_audience"`
	CreatedAt string `json:"created_at"`
	Email string `json:"email"`
	IconUrl string `json:"icon_url"`
	Id int `json:"id"`
	IsLtiKey bool `json:"is_lti_key"`
	IsLtiRegistration bool `json:"is_lti_registration"`
	LastUsedAt string `json:"last_used_at"`
	LtiRegistration json.RawMessage `json:"lti_registration"`
	Name string `json:"name"`
	Notes string `json:"notes"`
	PublicJwk json.RawMessage `json:"public_jwk"`
	PublicJwkUrl string `json:"public_jwk_url"`
	RedirectUri string `json:"redirect_uri"`
	RedirectUris json.RawMessage `json:"redirect_uris"`
	RequireScopes bool `json:"require_scopes"`
	Scopes json.RawMessage `json:"scopes"`
	TestClusterOnly bool `json:"test_cluster_only"`
	ToolConfiguration json.RawMessage `json:"tool_configuration"`
	UnifiedToolId string `json:"unified_tool_id"`
	UpdatedAt string `json:"updated_at"`
	UserId string `json:"user_id"`
	UserName string `json:"user_name"`
	VendorCode string `json:"vendor_code"`
	Visible bool `json:"visible"`
	WorkflowState string `json:"workflow_state"`
}

type DeveloperKeyAccountBinding struct {
	AccountId float64 `json:"account_id"`
	AccountOwnsBinding bool `json:"account_owns_binding"`
	DeveloperKeyId float64 `json:"developer_key_id"`
	Id float64 `json:"id"`
	WorkflowState float64 `json:"workflow_state"`
}

type DiscoveryPage struct {
	Active bool `json:"active"`
	Primary json.RawMessage `json:"primary"`
	Secondary json.RawMessage `json:"secondary"`
}

type DiscoveryPageEntry struct {
	AuthenticationProviderId int `json:"authentication_provider_id"`
	Icon string `json:"icon"`
	Label string `json:"label"`
}

type DiscussionTopic struct {
	AllowRating bool `json:"allow_rating"`
	AssignmentId int `json:"assignment_id"`
	Attachments json.RawMessage `json:"attachments"`
	DelayedPostAt string `json:"delayed_post_at"`
	DiscussionSubentryCount int `json:"discussion_subentry_count"`
	DiscussionType string `json:"discussion_type"`
	Expand bool `json:"expand"`
	ExpandLocked bool `json:"expand_locked"`
	GroupCategoryId int `json:"group_category_id"`
	GroupTopicChildren json.RawMessage `json:"group_topic_children"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	LastReplyAt string `json:"last_reply_at"`
	LockAt string `json:"lock_at"`
	LockExplanation string `json:"lock_explanation"`
	LockInfo json.RawMessage `json:"lock_info"`
	Locked bool `json:"locked"`
	LockedForUser bool `json:"locked_for_user"`
	Message string `json:"message"`
	OnlyGradersCanRate bool `json:"only_graders_can_rate"`
	Permissions json.RawMessage `json:"permissions"`
	Pinned bool `json:"pinned"`
	PodcastUrl string `json:"podcast_url"`
	PostedAt string `json:"posted_at"`
	Published bool `json:"published"`
	ReadState string `json:"read_state"`
	RequireInitialPost bool `json:"require_initial_post"`
	RootTopicId int `json:"root_topic_id"`
	SortByRating bool `json:"sort_by_rating"`
	SortOrder string `json:"sort_order"`
	SortOrderLocked bool `json:"sort_order_locked"`
	Subscribed bool `json:"subscribed"`
	SubscriptionHold string `json:"subscription_hold"`
	Title string `json:"title"`
	TopicChildren json.RawMessage `json:"topic_children"`
	UnreadCount int `json:"unread_count"`
	UserCanSeePosts bool `json:"user_can_see_posts"`
	UserName string `json:"user_name"`
}

type Enrollment struct {
	AssociatedUserId int `json:"associated_user_id"`
	CourseId int `json:"course_id"`
	CourseIntegrationId string `json:"course_integration_id"`
	CourseSectionId int `json:"course_section_id"`
	CreatedAt string `json:"created_at"`
	CurrentGradingPeriodId int `json:"current_grading_period_id"`
	CurrentGradingPeriodTitle string `json:"current_grading_period_title"`
	CurrentPeriodOverrideGrade string `json:"current_period_override_grade"`
	CurrentPeriodOverrideScore float64 `json:"current_period_override_score"`
	CurrentPeriodUnpostedCurrentGrade string `json:"current_period_unposted_current_grade"`
	CurrentPeriodUnpostedCurrentScore float64 `json:"current_period_unposted_current_score"`
	CurrentPeriodUnpostedFinalGrade string `json:"current_period_unposted_final_grade"`
	CurrentPeriodUnpostedFinalScore float64 `json:"current_period_unposted_final_score"`
	EndAt string `json:"end_at"`
	EnrollmentState string `json:"enrollment_state"`
	Grades json.RawMessage `json:"grades"`
	HasGradingPeriods bool `json:"has_grading_periods"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	LastActivityAt string `json:"last_activity_at"`
	LastAttendedAt string `json:"last_attended_at"`
	LimitPrivilegesToCourseSection bool `json:"limit_privileges_to_course_section"`
	OverrideGrade string `json:"override_grade"`
	OverrideScore float64 `json:"override_score"`
	Role string `json:"role"`
	RoleId int `json:"role_id"`
	RootAccountId int `json:"root_account_id"`
	SectionIntegrationId string `json:"section_integration_id"`
	SisAccountId string `json:"sis_account_id"`
	SisCourseId string `json:"sis_course_id"`
	SisImportId int `json:"sis_import_id"`
	SisSectionId string `json:"sis_section_id"`
	SisUserId string `json:"sis_user_id"`
	StartAt string `json:"start_at"`
	TotalActivityTime int `json:"total_activity_time"`
	TotalsForAllGradingPeriodsOption bool `json:"totals_for_all_grading_periods_option"`
	Type string `json:"type"`
	UnpostedCurrentGrade string `json:"unposted_current_grade"`
	UnpostedCurrentScore string `json:"unposted_current_score"`
	UnpostedFinalGrade string `json:"unposted_final_grade"`
	UnpostedFinalScore string `json:"unposted_final_score"`
	UpdatedAt string `json:"updated_at"`
	User json.RawMessage `json:"user"`
	UserId int `json:"user_id"`
}

type EnrollmentTerm struct {
	CourseCount int `json:"course_count"`
	EndAt string `json:"end_at"`
	Id int `json:"id"`
	Name string `json:"name"`
	Overrides json.RawMessage `json:"overrides"`
	SisImportId int `json:"sis_import_id"`
	SisTermId string `json:"sis_term_id"`
	StartAt string `json:"start_at"`
	WorkflowState string `json:"workflow_state"`
}

type EnrollmentTermsList struct {
	EnrollmentTerms json.RawMessage `json:"enrollment_terms"`
}

type EpubExport struct {
	Attachment json.RawMessage `json:"attachment"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	ProgressUrl string `json:"progress_url"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type ErrorReport struct {
	Comments string `json:"comments"`
	ContextAssetString string `json:"context_asset_string"`
	Email string `json:"email"`
	Subject string `json:"subject"`
	Url string `json:"url"`
	UserPerceivedSeverity string `json:"user_perceived_severity"`
	UserRoles string `json:"user_roles"`
}

type EstimatedDuration struct {
	CreatedAt string `json:"created_at"`
	Duration string `json:"duration"`
	Id int `json:"id"`
	UpdatedAt string `json:"updated_at"`
}

type ExceptionRecord struct {
	ConflictingChanges json.RawMessage `json:"conflicting_changes"`
	CourseId int `json:"course_id"`
}

type ExperienceSummary struct {
	AvailableApps json.RawMessage `json:"available_apps"`
	CurrentApp string `json:"current_app"`
}

type ExternalFeed struct {
	CreatedAt string `json:"created_at"`
	DisplayName string `json:"display_name"`
	HeaderMatch string `json:"header_match"`
	Id int `json:"id"`
	Url string `json:"url"`
	Verbosity string `json:"verbosity"`
}

type ExternalToolTagAttributes struct {
	NewTab bool `json:"new_tab"`
	ResourceLinkId string `json:"resource_link_id"`
	Url string `json:"url"`
}

type Favorite struct {
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
}

type Feature struct {
	AppliesTo string `json:"applies_to"`
	Autoexpand bool `json:"autoexpand"`
	Beta bool `json:"beta"`
	DisplayName string `json:"display_name"`
	EarlyAccessProgram bool `json:"early_access_program"`
	Feature string `json:"feature"`
	FeatureFlag json.RawMessage `json:"feature_flag"`
	ReleaseNotesUrl string `json:"release_notes_url"`
	RootOptIn bool `json:"root_opt_in"`
}

type FeatureFlag struct {
	Name string `json:"name"`
	State string `json:"state"`
}

type FederatedAttributeConfig struct {
	Attribute string `json:"attribute"`
	Autoconfirm bool `json:"autoconfirm"`
	ProvisioningOnly bool `json:"provisioning_only"`
}

type FederatedAttributesConfig struct {
	AdminRoles string `json:"admin_roles"`
	DisplayName string `json:"display_name"`
	Email string `json:"email"`
	GivenName string `json:"given_name"`
	IntegrationId string `json:"integration_id"`
	Locale string `json:"locale"`
	Name string `json:"name"`
	SisUserId string `json:"sis_user_id"`
	SortableName string `json:"sortable_name"`
	Surname string `json:"surname"`
	Timezone string `json:"timezone"`
}

type File struct {
	ContentType string `json:"content-type"`
	CreatedAt string `json:"created_at"`
	DisplayName string `json:"display_name"`
	Id int `json:"id"`
	Size int `json:"size"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
}

type FileAttachment struct {
	ContentType string `json:"content-type"`
	DisplayName string `json:"display_name"`
	Filename string `json:"filename"`
	Url string `json:"url"`
}

type Folder struct {
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	CreatedAt string `json:"created_at"`
	FilesCount int `json:"files_count"`
	FilesUrl string `json:"files_url"`
	FoldersCount int `json:"folders_count"`
	FoldersUrl string `json:"folders_url"`
	ForSubmissions bool `json:"for_submissions"`
	FullName string `json:"full_name"`
	Hidden bool `json:"hidden"`
	HiddenForUser bool `json:"hidden_for_user"`
	Id int `json:"id"`
	LockAt string `json:"lock_at"`
	Locked bool `json:"locked"`
	LockedForUser bool `json:"locked_for_user"`
	Name string `json:"name"`
	ParentFolderId int `json:"parent_folder_id"`
	Position int `json:"position"`
	UnlockAt string `json:"unlock_at"`
	UpdatedAt string `json:"updated_at"`
}

type Grade struct {
	Dropped json.RawMessage `json:"dropped"`
	Grade float64 `json:"grade"`
	Possible float64 `json:"possible"`
	Total float64 `json:"total"`
}

type GradeChangeEvent struct {
	CreatedAt string `json:"created_at"`
	EventType string `json:"event_type"`
	ExcusedAfter bool `json:"excused_after"`
	ExcusedBefore bool `json:"excused_before"`
	GradeAfter string `json:"grade_after"`
	GradeBefore string `json:"grade_before"`
	GradedAnonymously bool `json:"graded_anonymously"`
	Id string `json:"id"`
	Links json.RawMessage `json:"links"`
	RequestId string `json:"request_id"`
	VersionNumber string `json:"version_number"`
}

type GradeChangeEventLinks struct {
	Assignment int `json:"assignment"`
	Course int `json:"course"`
	Grader int `json:"grader"`
	PageView string `json:"page_view"`
	Student int `json:"student"`
}

type GradeGroup struct {
	SubmissionId json.RawMessage `json:"submission_id"`
}

type Grader struct {
	Assignments json.RawMessage `json:"assignments"`
	Id int `json:"id"`
	Name string `json:"name"`
}

type Grades struct {
	Current json.RawMessage `json:"current"`
	CurrentGroups json.RawMessage `json:"current_groups"`
	Final json.RawMessage `json:"final"`
	FinalGroups json.RawMessage `json:"final_groups"`
}

type GradingPeriod struct {
	CloseDate string `json:"close_date"`
	EndDate string `json:"end_date"`
	Id int `json:"id"`
	IsClosed bool `json:"is_closed"`
	StartDate string `json:"start_date"`
	Title string `json:"title"`
	Weight int `json:"weight"`
}

type GradingPeriodSets struct {
	DisplayTotalsForAllGradingPeriods bool `json:"display_totals_for_all_grading_periods"`
	Title string `json:"title"`
	Weighted bool `json:"weighted"`
}

type GradingRules struct {
	DropHighest int `json:"drop_highest"`
	DropLowest int `json:"drop_lowest"`
	NeverDrop json.RawMessage `json:"never_drop"`
}

type GradingSchemeEntry struct {
	CalculatedValue int `json:"calculated_value"`
	Name string `json:"name"`
	Value int `json:"value"`
}

type GradingStandard struct {
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	GradingScheme json.RawMessage `json:"grading_scheme"`
	Id int `json:"id"`
	PointsBased bool `json:"points_based"`
	ScalingFactor float64 `json:"scaling_factor"`
	Title string `json:"title"`
}

type Group struct {
	AvatarUrl string `json:"avatar_url"`
	ContextName string `json:"context_name"`
	ContextType string `json:"context_type"`
	CourseId int `json:"course_id"`
	Description string `json:"description"`
	FollowedByUser bool `json:"followed_by_user"`
	GroupCategoryId int `json:"group_category_id"`
	Id int `json:"id"`
	IsPublic bool `json:"is_public"`
	JoinLevel string `json:"join_level"`
	MembersCount int `json:"members_count"`
	Name string `json:"name"`
	NonCollaborative bool `json:"non_collaborative"`
	Permissions json.RawMessage `json:"permissions"`
	Role string `json:"role"`
	SisGroupId string `json:"sis_group_id"`
	SisImportId int `json:"sis_import_id"`
	StorageQuotaMb int `json:"storage_quota_mb"`
	Users json.RawMessage `json:"users"`
}

type GroupCategory struct {
	AccountId int `json:"account_id"`
	AutoLeader string `json:"auto_leader"`
	ContextType string `json:"context_type"`
	GroupLimit int `json:"group_limit"`
	Id int `json:"id"`
	Name string `json:"name"`
	NonCollaborative bool `json:"non_collaborative"`
	Progress json.RawMessage `json:"progress"`
	Role string `json:"role"`
	SelfSignup string `json:"self_signup"`
	SisGroupCategoryId string `json:"sis_group_category_id"`
	SisImportId int `json:"sis_import_id"`
}

type GroupMembership struct {
	GroupId int `json:"group_id"`
	Id int `json:"id"`
	JustCreated bool `json:"just_created"`
	Moderator bool `json:"moderator"`
	SisImportId int `json:"sis_import_id"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type HelpLink struct {
	AvailableTo json.RawMessage `json:"available_to"`
	Id string `json:"id"`
	Subtext string `json:"subtext"`
	Text string `json:"text"`
	Type string `json:"type"`
	Url string `json:"url"`
}

type HelpLinks struct {
	CustomHelpLinks json.RawMessage `json:"custom_help_links"`
	DefaultHelpLinks json.RawMessage `json:"default_help_links"`
	HelpLinkIcon string `json:"help_link_icon"`
	HelpLinkName string `json:"help_link_name"`
}

type HistoryEntry struct {
	AssetCode string `json:"asset_code"`
	AssetIcon string `json:"asset_icon"`
	AssetName string `json:"asset_name"`
	AssetReadableCategory string `json:"asset_readable_category"`
	ContextId int `json:"context_id"`
	ContextName string `json:"context_name"`
	ContextType string `json:"context_type"`
	InteractionSeconds int `json:"interaction_seconds"`
	VisitedAt string `json:"visited_at"`
	VisitedUrl string `json:"visited_url"`
}

type InstAccessToken struct {
	Token string `json:"token"`
}

type JSONAPIPagination struct {
}

type JWKs struct {
}

type JWT struct {
	Token string `json:"token"`
}

type LatePolicy struct {
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	LateSubmissionDeduction float64 `json:"late_submission_deduction"`
	LateSubmissionDeductionEnabled bool `json:"late_submission_deduction_enabled"`
	LateSubmissionInterval string `json:"late_submission_interval"`
	LateSubmissionMinimumPercent float64 `json:"late_submission_minimum_percent"`
	LateSubmissionMinimumPercentEnabled bool `json:"late_submission_minimum_percent_enabled"`
	MissingSubmissionDeduction float64 `json:"missing_submission_deduction"`
	MissingSubmissionDeductionEnabled bool `json:"missing_submission_deduction_enabled"`
	UpdatedAt string `json:"updated_at"`
}

type LearningObjectDates struct {
	BlueprintDateLocks json.RawMessage `json:"blueprint_date_locks"`
	Checkpoints json.RawMessage `json:"checkpoints"`
	DueAt string `json:"due_at"`
	Graded bool `json:"graded"`
	Id int `json:"id"`
	LockAt string `json:"lock_at"`
	OnlyVisibleToOverrides bool `json:"only_visible_to_overrides"`
	Overrides json.RawMessage `json:"overrides"`
	PeerReviewSubAssignment json.RawMessage `json:"peer_review_sub_assignment"`
	ReplyToTopicDueAt string `json:"reply_to_topic_due_at"`
	RequiredRepliesDueAt string `json:"required_replies_due_at"`
	Tag string `json:"tag"`
	UnlockAt string `json:"unlock_at"`
	VisibleToEveryone bool `json:"visible_to_everyone"`
}

type License struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Url string `json:"url"`
}

type LineItem struct {
	HttpsCanvasInstructureComLtiLaunchUrl string `json:"https://canvas.instructure.com/lti/launch_url"`
	HttpsCanvasInstructureComLtiSubmissionType string `json:"https://canvas.instructure.com/lti/submission_type"`
	Id string `json:"id"`
	Label string `json:"label"`
	ResourceId string `json:"resourceId"`
	ResourceLinkId string `json:"resourceLinkId"`
	ScoreMaximum float64 `json:"scoreMaximum"`
	Tag string `json:"tag"`
}

type ListLtiRegistrationsResponse struct {
	Data json.RawMessage `json:"data"`
	Total int `json:"total"`
}

type LockInfo struct {
	AssetString string `json:"asset_string"`
	ContextModule string `json:"context_module"`
	LockAt string `json:"lock_at"`
	ManuallyLocked bool `json:"manually_locked"`
	UnlockAt string `json:"unlock_at"`
}

type LtiAssignment struct {
	CourseId int `json:"course_id"`
	Description string `json:"description"`
	DueAt string `json:"due_at"`
	Id int `json:"id"`
	LtiCourseId string `json:"lti_course_id"`
	LtiId string `json:"lti_id"`
	Name string `json:"name"`
	PointsPossible int `json:"points_possible"`
}

type Lti_ContextControl struct {
	AccountId int `json:"account_id"`
	Available bool `json:"available"`
	ChildControlCount int `json:"child_control_count"`
	ContextName string `json:"context_name"`
	CourseCount int `json:"course_count"`
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	CreatedBy json.RawMessage `json:"created_by"`
	DeploymentId int `json:"deployment_id"`
	Depth int `json:"depth"`
	DisplayPath json.RawMessage `json:"display_path"`
	Id int `json:"id"`
	Path string `json:"path"`
	SubaccountCount int `json:"subaccount_count"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy json.RawMessage `json:"updated_by"`
	WorkflowState string `json:"workflow_state"`
}

type Lti_Deployment struct {
	ContextControls json.RawMessage `json:"context_controls"`
	ContextId int `json:"context_id"`
	ContextName string `json:"context_name"`
	ContextType string `json:"context_type"`
	DeploymentId string `json:"deployment_id"`
	Id int `json:"id"`
	RegistrationId int `json:"registration_id"`
	WorkflowState string `json:"workflow_state"`
}

type Lti_LaunchDefinition struct {
	ContextName string `json:"context_name"`
	DefinitionId string `json:"definition_id"`
	DefinitionType string `json:"definition_type"`
	Description string `json:"description"`
	Domain string `json:"domain"`
	Name string `json:"name"`
	Placements json.RawMessage `json:"placements"`
	Url string `json:"url"`
}

type Lti_LaunchSettings struct {
	AcceptMediaTypes string `json:"accept_media_types"`
	CanvasIconClass string `json:"canvas_icon_class"`
	CustomFields json.RawMessage `json:"custom_fields"`
	Default string `json:"default"`
	DisplayType string `json:"display_type"`
	IconSvgPath64 string `json:"icon_svg_path_64"`
	IconUrl string `json:"icon_url"`
	Labels json.RawMessage `json:"labels"`
	LaunchHeight float64 `json:"launch_height"`
	LaunchWidth float64 `json:"launch_width"`
	MessageType string `json:"message_type"`
	OauthCompliant bool `json:"oauth_compliant"`
	PreferSisEmail bool `json:"prefer_sis_email"`
	RequiredPermissions string `json:"required_permissions"`
	SelectionHeight float64 `json:"selection_height"`
	SelectionWidth float64 `json:"selection_width"`
	TargetLinkUri string `json:"target_link_uri"`
	Text string `json:"text"`
	Url string `json:"url"`
	UseTray bool `json:"use_tray"`
	Visibility string `json:"visibility"`
	WindowTarget string `json:"windowTarget"`
}

type Lti_LegacyConfiguration struct {
	CustomFields json.RawMessage `json:"custom_fields"`
	Description string `json:"description"`
	Extensions json.RawMessage `json:"extensions"`
	OidcInitiationUrl string `json:"oidc_initiation_url"`
	OidcInitiationUrls json.RawMessage `json:"oidc_initiation_urls"`
	PublicJwk json.RawMessage `json:"public_jwk"`
	PublicJwkUrl string `json:"public_jwk_url"`
	Scopes json.RawMessage `json:"scopes"`
	TargetLinkUri string `json:"target_link_uri"`
	Title string `json:"title"`
}

type Lti_Overlay struct {
	CustomFields json.RawMessage `json:"custom_fields"`
	Description string `json:"description"`
	DisabledPlacements json.RawMessage `json:"disabled_placements"`
	DisabledScopes json.RawMessage `json:"disabled_scopes"`
	Domain string `json:"domain"`
	OidcInitiationUrl string `json:"oidc_initiation_url"`
	Placements json.RawMessage `json:"placements"`
	PrivacyLevel string `json:"privacy_level"`
	TargetLinkUri string `json:"target_link_uri"`
	Title string `json:"title"`
}

type Lti_OverlayVersion struct {
	AccountId int `json:"account_id"`
	CausedByReset bool `json:"caused_by_reset"`
	CreatedAt string `json:"created_at"`
	CreatedBy json.RawMessage `json:"created_by"`
	Diff json.RawMessage `json:"diff"`
	LtiOverlayId int `json:"lti_overlay_id"`
	RootAccountId int `json:"root_account_id"`
	UpdatedAt string `json:"updated_at"`
}

type Lti_Placement struct {
	AcceptMediaTypes string `json:"accept_media_types"`
	CanvasIconClass string `json:"canvas_icon_class"`
	CustomFields json.RawMessage `json:"custom_fields"`
	Default string `json:"default"`
	DisplayType string `json:"display_type"`
	Enabled bool `json:"enabled"`
	IconSvgPath64 string `json:"icon_svg_path_64"`
	IconUrl string `json:"icon_url"`
	Labels json.RawMessage `json:"labels"`
	LaunchHeight float64 `json:"launch_height"`
	LaunchWidth float64 `json:"launch_width"`
	MessageType string `json:"message_type"`
	OauthCompliant bool `json:"oauth_compliant"`
	Placement string `json:"placement"`
	PreferSisEmail bool `json:"prefer_sis_email"`
	RequiredPermissions string `json:"required_permissions"`
	SelectionHeight float64 `json:"selection_height"`
	SelectionWidth float64 `json:"selection_width"`
	TargetLinkUri string `json:"target_link_uri"`
	Text string `json:"text"`
	Url string `json:"url"`
	UseTray bool `json:"use_tray"`
	Visibility string `json:"visibility"`
	WindowTarget string `json:"windowTarget"`
}

type Lti_PlacementLaunchDefinition struct {
	MessageType string `json:"message_type"`
	Title string `json:"title"`
	Url string `json:"url"`
}

type Lti_PlacementOverlay struct {
	Default string `json:"default"`
	IconUrl string `json:"icon_url"`
	LaunchHeight float64 `json:"launch_height"`
	LaunchWidth float64 `json:"launch_width"`
	MessageType string `json:"message_type"`
	TargetLinkUri string `json:"target_link_uri"`
	Text string `json:"text"`
}

type Lti_Registration struct {
	AccountBinding json.RawMessage `json:"account_binding"`
	AccountId int `json:"account_id"`
	AdminNickname string `json:"admin_nickname"`
	Configuration json.RawMessage `json:"configuration"`
	CreatedAt string `json:"created_at"`
	CreatedBy json.RawMessage `json:"created_by"`
	DynamicRegistration bool `json:"dynamic_registration"`
	IconUrl string `json:"icon_url"`
	Id int `json:"id"`
	Inherited bool `json:"inherited"`
	InternalService bool `json:"internal_service"`
	LtiVersion string `json:"lti_version"`
	Name string `json:"name"`
	RootAccountId int `json:"root_account_id"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy json.RawMessage `json:"updated_by"`
	Vendor string `json:"vendor"`
	WorkflowState string `json:"workflow_state"`
}

type Lti_RegistrationAccountBinding struct {
	AccountId int `json:"account_id"`
	CreatedAt string `json:"created_at"`
	CreatedBy json.RawMessage `json:"created_by"`
	Id int `json:"id"`
	RegistrationId int `json:"registration_id"`
	RootAccountId int `json:"root_account_id"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy json.RawMessage `json:"updated_by"`
	WorkflowState string `json:"workflow_state"`
}

type Lti_ResourceLink struct {
	AssociatedContentId int `json:"associated_content_id"`
	AssociatedContentType string `json:"associated_content_type"`
	CanvasLaunchUrl string `json:"canvas_launch_url"`
	ContextExternalToolId int `json:"context_external_tool_id"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	LookupUuid string `json:"lookup_uuid"`
	Lti11Id string `json:"lti_1_1_id"`
	ResourceLinkUuid string `json:"resource_link_uuid"`
	ResourceType string `json:"resource_type"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	WorkflowState string `json:"workflow_state"`
}

type Lti_ToolConfiguration struct {
	CustomFields json.RawMessage `json:"custom_fields"`
	Description string `json:"description"`
	Domain string `json:"domain"`
	LaunchSettings json.RawMessage `json:"launch_settings"`
	OidcInitiationUrl string `json:"oidc_initiation_url"`
	OidcInitiationUrls json.RawMessage `json:"oidc_initiation_urls"`
	Placements json.RawMessage `json:"placements"`
	PrivacyLevel string `json:"privacy_level"`
	PublicJwk json.RawMessage `json:"public_jwk"`
	PublicJwkUrl string `json:"public_jwk_url"`
	RedirectUris json.RawMessage `json:"redirect_uris"`
	Scopes json.RawMessage `json:"scopes"`
	TargetLinkUri string `json:"target_link_uri"`
	Title string `json:"title"`
	ToolId string `json:"tool_id"`
}

type MediaComment struct {
	ContentType string `json:"content-type"`
	DisplayName string `json:"display_name"`
	MediaId string `json:"media_id"`
	MediaType string `json:"media_type"`
	Url string `json:"url"`
}

type MicrosoftSync_Group struct {
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	DebugInfo json.RawMessage `json:"debug_info"`
	Id int `json:"id"`
	JobState string `json:"job_state"`
	LastError string `json:"last_error"`
	LastErrorReportId int `json:"last_error_report_id"`
	LastSyncedAt string `json:"last_synced_at"`
	RootAccountId int `json:"root_account_id"`
	UpdatedAt string `json:"updated_at"`
	WorkflowState string `json:"workflow_state"`
}

type MigrationIssue struct {
	ContentMigrationUrl string `json:"content_migration_url"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	ErrorMessage string `json:"error_message"`
	ErrorReportHtmlUrl string `json:"error_report_html_url"`
	FixIssueHtmlUrl string `json:"fix_issue_html_url"`
	Id int `json:"id"`
	IssueType string `json:"issue_type"`
	UpdatedAt string `json:"updated_at"`
	WorkflowState string `json:"workflow_state"`
}

type Migrator struct {
	Name string `json:"name"`
	RequiredSettings json.RawMessage `json:"required_settings"`
	RequiresFileUpload bool `json:"requires_file_upload"`
	Type string `json:"type"`
}

type Module struct {
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	Id int `json:"id"`
	Items json.RawMessage `json:"items"`
	Name string `json:"name"`
	Position int `json:"position"`
}

type ModuleAssignmentOverride struct {
	ContextModuleId int `json:"context_module_id"`
	CourseSection json.RawMessage `json:"course_section"`
	Id int `json:"id"`
	Students json.RawMessage `json:"students"`
	Title string `json:"title"`
}

type ModuleItem struct {
	AssignmentLink string `json:"assignment_link"`
	AssignmentTitle string `json:"assignment_title"`
	CoursePaceId int `json:"course_pace_id"`
	Duration int `json:"duration"`
	Id int `json:"id"`
	ModuleItemId int `json:"module_item_id"`
	ModuleItemType string `json:"module_item_type"`
	PointsPossible float64 `json:"points_possible"`
	Position int `json:"position"`
	Published bool `json:"published"`
	RootAccountId int `json:"root_account_id"`
}

type ModuleItemSequence struct {
	Items json.RawMessage `json:"items"`
	Modules json.RawMessage `json:"modules"`
}

type ModuleItemSequenceNode struct {
	Current json.RawMessage `json:"current"`
	MasteryPath json.RawMessage `json:"mastery_path"`
	Next json.RawMessage `json:"next"`
	Prev json.RawMessage `json:"prev"`
}

type NamesAndRoleContext struct {
	Id string `json:"id"`
	Label string `json:"label"`
	Title string `json:"title"`
}

type NamesAndRoleMembership struct {
	Email string `json:"email"`
	FamilyName string `json:"family_name"`
	GivenName string `json:"given_name"`
	LisPersonSourcedid string `json:"lis_person_sourcedid"`
	Message json.RawMessage `json:"message"`
	Name string `json:"name"`
	Picture string `json:"picture"`
	Roles json.RawMessage `json:"roles"`
	Status string `json:"status"`
	UserId string `json:"user_id"`
}

type NamesAndRoleMemberships struct {
	Context json.RawMessage `json:"context"`
	Id string `json:"id"`
	Members json.RawMessage `json:"members"`
}

type NamesAndRoleMessage struct {
	HttpsPurlImsglobalOrgSpecLtiClaimCustom json.RawMessage `json:"https://purl.imsglobal.org/spec/lti/claim/custom"`
	HttpsPurlImsglobalOrgSpecLtiClaimMessageType string `json:"https://purl.imsglobal.org/spec/lti/claim/message_type"`
	HttpsWwwInstructureComCanvasUserId int `json:"https://www.instructure.com/canvas_user_id"`
	HttpsWwwInstructureComCanvasUserLoginId string `json:"https://www.instructure.com/canvas_user_login_id"`
	Locale string `json:"locale"`
}

type NeedsGradingCount struct {
	NeedsGradingCount int `json:"needs_grading_count"`
	SectionId string `json:"section_id"`
}

type NoticeCatalog struct {
	ClientId string `json:"client_id"`
	DeploymentId string `json:"deployment_id"`
	NoticeHandlers json.RawMessage `json:"notice_handlers"`
}

type NoticeHandler struct {
	Handler string `json:"handler"`
	MaxBatchSize int `json:"max_batch_size"`
	NoticeType string `json:"notice_type"`
}

type NotificationPreference struct {
	Category string `json:"category"`
	Frequency string `json:"frequency"`
	Href string `json:"href"`
	Notification string `json:"notification"`
}

type OriginalityReport struct {
	ErrorReport string `json:"error_report"`
	FileId int `json:"file_id"`
	Id int `json:"id"`
	OriginalityReportFileId int `json:"originality_report_file_id"`
	OriginalityReportUrl string `json:"originality_report_url"`
	OriginalityScore float64 `json:"originality_score"`
	RootAccountId int `json:"root_account_id"`
	SubmissionTime string `json:"submission_time"`
	ToolSetting json.RawMessage `json:"tool_setting"`
}

type Outcome struct {
	Assessed bool `json:"assessed"`
	CalculationInt int `json:"calculation_int"`
	CalculationMethod string `json:"calculation_method"`
	CanEdit bool `json:"can_edit"`
	CanUnlink bool `json:"can_unlink"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	Description string `json:"description"`
	DisplayName string `json:"display_name"`
	HasUpdateableRubrics bool `json:"has_updateable_rubrics"`
	Id int `json:"id"`
	MasteryPoints int `json:"mastery_points"`
	PointsPossible int `json:"points_possible"`
	Ratings json.RawMessage `json:"ratings"`
	Title string `json:"title"`
	Url string `json:"url"`
	VendorGuid string `json:"vendor_guid"`
}

type OutcomeAlignment struct {
	AssessmentId int `json:"assessment_id"`
	AssignmentId int `json:"assignment_id"`
	Id int `json:"id"`
	SubmissionTypes string `json:"submission_types"`
	Title string `json:"title"`
	Url string `json:"url"`
}

type OutcomeGroup struct {
	CanEdit bool `json:"can_edit"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	Description string `json:"description"`
	Id int `json:"id"`
	ImportUrl string `json:"import_url"`
	OutcomesUrl string `json:"outcomes_url"`
	ParentOutcomeGroup json.RawMessage `json:"parent_outcome_group"`
	SubgroupsUrl string `json:"subgroups_url"`
	Title string `json:"title"`
	Url string `json:"url"`
	VendorGuid string `json:"vendor_guid"`
}

type OutcomeImport struct {
	CreatedAt string `json:"created_at"`
	Data json.RawMessage `json:"data"`
	EndedAt string `json:"ended_at"`
	Id int `json:"id"`
	LearningOutcomeGroupId int `json:"learning_outcome_group_id"`
	ProcessingErrors json.RawMessage `json:"processing_errors"`
	Progress string `json:"progress"`
	UpdatedAt string `json:"updated_at"`
	User json.RawMessage `json:"user"`
	WorkflowState string `json:"workflow_state"`
}

type OutcomeImportData struct {
	ImportType string `json:"import_type"`
}

type OutcomeLink struct {
	Assessed bool `json:"assessed"`
	CanUnlink bool `json:"can_unlink"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	Outcome json.RawMessage `json:"outcome"`
	OutcomeGroup json.RawMessage `json:"outcome_group"`
	Url string `json:"url"`
}

type OutcomePath struct {
	Id int `json:"id"`
	Parts json.RawMessage `json:"parts"`
}

type OutcomePathPart struct {
	Name string `json:"name"`
}

type OutcomeResult struct {
	Id int `json:"id"`
	Links json.RawMessage `json:"links"`
	Percent float64 `json:"percent"`
	Score int `json:"score"`
	SubmittedOrAssessedAt string `json:"submitted_or_assessed_at"`
}

type OutcomeRollup struct {
	Links json.RawMessage `json:"links"`
	Name string `json:"name"`
	Scores json.RawMessage `json:"scores"`
}

type OutcomeRollupLinks struct {
	Course int `json:"course"`
	Section int `json:"section"`
	User int `json:"user"`
}

type OutcomeRollupScore struct {
	Count int `json:"count"`
	Links json.RawMessage `json:"links"`
	Score int `json:"score"`
}

type OutcomeRollupScoreLinks struct {
	Outcome int `json:"outcome"`
}

type OverrideTarget struct {
	Id int `json:"id"`
	Name string `json:"name"`
}

type Page struct {
	BlockEditorAttributes json.RawMessage `json:"block_editor_attributes"`
	Body string `json:"body"`
	CreatedAt string `json:"created_at"`
	EditingRoles string `json:"editing_roles"`
	Editor string `json:"editor"`
	FrontPage bool `json:"front_page"`
	HideFromStudents bool `json:"hide_from_students"`
	LastEditedBy json.RawMessage `json:"last_edited_by"`
	LockExplanation string `json:"lock_explanation"`
	LockInfo json.RawMessage `json:"lock_info"`
	LockedForUser bool `json:"locked_for_user"`
	PageId int `json:"page_id"`
	PublishAt string `json:"publish_at"`
	Published bool `json:"published"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
}

type PageRevision struct {
	Body string `json:"body"`
	EditedBy json.RawMessage `json:"edited_by"`
	Latest bool `json:"latest"`
	RevisionId int `json:"revision_id"`
	Title string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
}

type PageView struct {
	Action string `json:"action"`
	AppName string `json:"app_name"`
	AssetType string `json:"asset_type"`
	AssetUserAccessId float64 `json:"asset_user_access_id"`
	ContextType string `json:"context_type"`
	Contributed bool `json:"contributed"`
	Controller string `json:"controller"`
	CreatedAt string `json:"created_at"`
	DeveloperKeyId float64 `json:"developer_key_id"`
	HttpMethod string `json:"http_method"`
	Id string `json:"id"`
	InteractionSeconds float64 `json:"interaction_seconds"`
	Links json.RawMessage `json:"links"`
	Participated bool `json:"participated"`
	RemoteIp string `json:"remote_ip"`
	RenderTime float64 `json:"render_time"`
	SessionId string `json:"session_id"`
	Url string `json:"url"`
	UserAgent string `json:"user_agent"`
	UserRequest bool `json:"user_request"`
}

type PageViewLinks struct {
	Account int `json:"account"`
	Asset int `json:"asset"`
	Context int `json:"context"`
	RealUser int `json:"real_user"`
	User int `json:"user"`
}

type PairingCode struct {
	Code string `json:"code"`
	ExpiresAt string `json:"expires_at"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type PeerReview struct {
	Assessor string `json:"assessor"`
	AssessorId int `json:"assessor_id"`
	AssetId int `json:"asset_id"`
	AssetType string `json:"asset_type"`
	Id int `json:"id"`
	SubmissionComments string `json:"submission_comments"`
	User string `json:"user"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type Permission struct {
	AvailableTo json.RawMessage `json:"available_to"`
	Group string `json:"group"`
	GroupLabel string `json:"group_label"`
	Key string `json:"key"`
	Label string `json:"label"`
	TrueFor json.RawMessage `json:"true_for"`
}

type PermissionHelpText struct {
	Considerations json.RawMessage `json:"considerations"`
	Details json.RawMessage `json:"details"`
}

type PlannerNote struct {
	CourseId int `json:"course_id"`
	Description string `json:"description"`
	Id int `json:"id"`
	LinkedObjectHtmlUrl string `json:"linked_object_html_url"`
	LinkedObjectId int `json:"linked_object_id"`
	LinkedObjectType string `json:"linked_object_type"`
	LinkedObjectUrl string `json:"linked_object_url"`
	Title string `json:"title"`
	TodoDate string `json:"todo_date"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type PlannerOverride struct {
	AssignmentId int `json:"assignment_id"`
	CreatedAt string `json:"created_at"`
	DeletedAt string `json:"deleted_at"`
	Dismissed bool `json:"dismissed"`
	Id int `json:"id"`
	MarkedComplete bool `json:"marked_complete"`
	PlannableId int `json:"plannable_id"`
	PlannableType string `json:"plannable_type"`
	UpdatedAt string `json:"updated_at"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type Poll struct {
	CreatedAt string `json:"created_at"`
	Description string `json:"description"`
	Id int `json:"id"`
	Question string `json:"question"`
	TotalResults json.RawMessage `json:"total_results"`
	UserId int `json:"user_id"`
}

type PollChoice struct {
	Id int `json:"id"`
	IsCorrect bool `json:"is_correct"`
	PollId int `json:"poll_id"`
	Position int `json:"position"`
	Text string `json:"text"`
}

type PollSession struct {
	CourseId int `json:"course_id"`
	CourseSectionId int `json:"course_section_id"`
	CreatedAt string `json:"created_at"`
	HasPublicResults bool `json:"has_public_results"`
	Id int `json:"id"`
	IsPublished bool `json:"is_published"`
	PollId int `json:"poll_id"`
	PollSubmissions json.RawMessage `json:"poll_submissions"`
	Results json.RawMessage `json:"results"`
}

type PollSubmission struct {
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	PollChoiceId int `json:"poll_choice_id"`
	UserId int `json:"user_id"`
}

type Proficiency struct {
	Ratings json.RawMessage `json:"ratings"`
}

type ProficiencyRating struct {
	Color string `json:"color"`
	Description string `json:"description"`
	Mastery bool `json:"mastery"`
	Points float64 `json:"points"`
}

type Profile struct {
	AvatarUrl string `json:"avatar_url"`
	Bio string `json:"bio"`
	Calendar json.RawMessage `json:"calendar"`
	Id int `json:"id"`
	K5User bool `json:"k5_user"`
	Locale string `json:"locale"`
	LoginId string `json:"login_id"`
	LtiUserId string `json:"lti_user_id"`
	Name string `json:"name"`
	PrimaryEmail string `json:"primary_email"`
	Pronunciation string `json:"pronunciation"`
	ShortName string `json:"short_name"`
	SisUserId string `json:"sis_user_id"`
	SortableName string `json:"sortable_name"`
	TimeZone string `json:"time_zone"`
	Title string `json:"title"`
	UseClassicFontInK5 bool `json:"use_classic_font_in_k5"`
}

type Progress struct {
	Completion int `json:"completion"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	Message string `json:"message"`
	Results json.RawMessage `json:"results"`
	Tag string `json:"tag"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type ProvisionalGrade struct {
	Final bool `json:"final"`
	Grade string `json:"grade"`
	GradeMatchesCurrentSubmission bool `json:"grade_matches_current_submission"`
	GradedAt string `json:"graded_at"`
	ProvisionalGradeId int `json:"provisional_grade_id"`
	Score int `json:"score"`
	SpeedgraderUrl string `json:"speedgrader_url"`
}

type Quiz struct {
	AccessCode string `json:"access_code"`
	AllDates json.RawMessage `json:"all_dates"`
	AllowedAttempts int `json:"allowed_attempts"`
	AnonymousSubmissions bool `json:"anonymous_submissions"`
	AssignmentGroupId int `json:"assignment_group_id"`
	CantGoBack bool `json:"cant_go_back"`
	Description string `json:"description"`
	DueAt string `json:"due_at"`
	HideCorrectAnswersAt string `json:"hide_correct_answers_at"`
	HideResults string `json:"hide_results"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	IpFilter string `json:"ip_filter"`
	LockAt string `json:"lock_at"`
	LockExplanation string `json:"lock_explanation"`
	LockInfo json.RawMessage `json:"lock_info"`
	LockedForUser bool `json:"locked_for_user"`
	MobileUrl string `json:"mobile_url"`
	OneQuestionAtATime bool `json:"one_question_at_a_time"`
	OneTimeResults bool `json:"one_time_results"`
	Permissions json.RawMessage `json:"permissions"`
	PointsPossible int `json:"points_possible"`
	PreviewUrl string `json:"preview_url"`
	Published bool `json:"published"`
	QuestionCount int `json:"question_count"`
	QuestionTypes json.RawMessage `json:"question_types"`
	QuizExtensionsUrl string `json:"quiz_extensions_url"`
	QuizType string `json:"quiz_type"`
	ScoringPolicy string `json:"scoring_policy"`
	ShowCorrectAnswers bool `json:"show_correct_answers"`
	ShowCorrectAnswersAt string `json:"show_correct_answers_at"`
	ShowCorrectAnswersLastAttempt bool `json:"show_correct_answers_last_attempt"`
	ShuffleAnswers bool `json:"shuffle_answers"`
	SpeedgraderUrl string `json:"speedgrader_url"`
	TimeLimit int `json:"time_limit"`
	Title string `json:"title"`
	UnlockAt string `json:"unlock_at"`
	Unpublishable bool `json:"unpublishable"`
	VersionNumber int `json:"version_number"`
}

type QuizAssignmentOverride struct {
	Base bool `json:"base"`
	DueAt string `json:"due_at"`
	Id int `json:"id"`
	LockAt string `json:"lock_at"`
	Title string `json:"title"`
	UnlockAt string `json:"unlock_at"`
}

type QuizAssignmentOverrideSet struct {
	AllDates json.RawMessage `json:"all_dates"`
	DueDates json.RawMessage `json:"due_dates"`
	QuizId string `json:"quiz_id"`
}

type QuizAssignmentOverrideSetContainer struct {
	QuizAssignmentOverrides json.RawMessage `json:"quiz_assignment_overrides"`
}

type QuizExtension struct {
	EndAt string `json:"end_at"`
	ExtraAttempts int `json:"extra_attempts"`
	ExtraTime int `json:"extra_time"`
	ManuallyUnlocked bool `json:"manually_unlocked"`
	QuizId int `json:"quiz_id"`
	UserId int `json:"user_id"`
}

type QuizGroup struct {
	AssessmentQuestionBankId int `json:"assessment_question_bank_id"`
	Id int `json:"id"`
	Name string `json:"name"`
	PickCount int `json:"pick_count"`
	Position int `json:"position"`
	QuestionPoints int `json:"question_points"`
	QuizId int `json:"quiz_id"`
}

type QuizIPFilter struct {
	Account string `json:"account"`
	Filter string `json:"filter"`
	Name string `json:"name"`
}

type QuizPermissions struct {
	Create bool `json:"create"`
	Manage bool `json:"manage"`
	Read bool `json:"read"`
	ReadStatistics bool `json:"read_statistics"`
	ReviewGrades bool `json:"review_grades"`
	Submit bool `json:"submit"`
	Update bool `json:"update"`
}

type QuizQuestion struct {
	Answers json.RawMessage `json:"answers"`
	AssessmentQuestionBankId int `json:"assessment_question_bank_id"`
	CorrectComments string `json:"correct_comments"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	IncorrectComments string `json:"incorrect_comments"`
	NeutralComments string `json:"neutral_comments"`
	PointsPossible int `json:"points_possible"`
	Position int `json:"position"`
	QuestionName string `json:"question_name"`
	QuestionText string `json:"question_text"`
	QuestionType string `json:"question_type"`
	QuizId int `json:"quiz_id"`
}

type QuizReport struct {
	Anonymous bool `json:"anonymous"`
	CreatedAt string `json:"created_at"`
	File json.RawMessage `json:"file"`
	Generatable bool `json:"generatable"`
	Id int `json:"id"`
	IncludesAllVersions bool `json:"includes_all_versions"`
	Progress json.RawMessage `json:"progress"`
	ProgressUrl string `json:"progress_url"`
	QuizId int `json:"quiz_id"`
	ReadableType string `json:"readable_type"`
	ReportType string `json:"report_type"`
	UpdatedAt string `json:"updated_at"`
	Url string `json:"url"`
}

type QuizStatistics struct {
	GeneratedAt string `json:"generated_at"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	IncludesAllVersions bool `json:"includes_all_versions"`
	Links json.RawMessage `json:"links"`
	MultipleAttemptsExist bool `json:"multiple_attempts_exist"`
	QuestionStatistics json.RawMessage `json:"question_statistics"`
	QuizId int `json:"quiz_id"`
	SubmissionStatistics json.RawMessage `json:"submission_statistics"`
	Url string `json:"url"`
}

type QuizStatisticsAnswerPointBiserial struct {
	AnswerId int `json:"answer_id"`
	Correct bool `json:"correct"`
	Distractor bool `json:"distractor"`
	PointBiserial float64 `json:"point_biserial"`
}

type QuizStatisticsAnswerStatistics struct {
	Id int `json:"id"`
	Responses int `json:"responses"`
	Text string `json:"text"`
	Weight int `json:"weight"`
}

type QuizStatisticsLinks struct {
	Quiz string `json:"quiz"`
}

type QuizStatisticsQuestionStatistics struct {
	Answers json.RawMessage `json:"answers"`
	Responses int `json:"responses"`
}

type QuizStatisticsSubmissionStatistics struct {
	CorrectCountAverage float64 `json:"correct_count_average"`
	DurationAverage float64 `json:"duration_average"`
	IncorrectCountAverage float64 `json:"incorrect_count_average"`
	ScoreAverage float64 `json:"score_average"`
	ScoreHigh float64 `json:"score_high"`
	ScoreLow float64 `json:"score_low"`
	ScoreStdev float64 `json:"score_stdev"`
	Scores json.RawMessage `json:"scores"`
	UniqueCount int `json:"unique_count"`
}

type QuizSubmission struct {
	Attempt int `json:"attempt"`
	EndAt string `json:"end_at"`
	ExtraAttempts int `json:"extra_attempts"`
	ExtraTime int `json:"extra_time"`
	FinishedAt string `json:"finished_at"`
	FudgePoints int `json:"fudge_points"`
	HasSeenResults bool `json:"has_seen_results"`
	Id int `json:"id"`
	KeptScore int `json:"kept_score"`
	ManuallyUnlocked bool `json:"manually_unlocked"`
	OverdueAndNeedsSubmission bool `json:"overdue_and_needs_submission"`
	QuizId int `json:"quiz_id"`
	Score int `json:"score"`
	ScoreBeforeRegrade int `json:"score_before_regrade"`
	StartedAt string `json:"started_at"`
	SubmissionId int `json:"submission_id"`
	TimeSpent int `json:"time_spent"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type QuizSubmissionEvent struct {
	CreatedAt string `json:"created_at"`
	EventData json.RawMessage `json:"event_data"`
	EventType string `json:"event_type"`
}

type QuizSubmissionQuestion struct {
	Answer string `json:"answer"`
	Answers json.RawMessage `json:"answers"`
	Flagged bool `json:"flagged"`
	Id int `json:"id"`
}

type QuizSubmissionUserList struct {
}

type QuizSubmissionUserListMeta struct {
}

type Report struct {
	Attachment json.RawMessage `json:"attachment"`
	CreatedAt string `json:"created_at"`
	EndedAt string `json:"ended_at"`
	FileUrl string `json:"file_url"`
	Id int `json:"id"`
	Parameters json.RawMessage `json:"parameters"`
	Progress int `json:"progress"`
	StartedAt string `json:"started_at"`
	Status string `json:"status"`
}

type ReportParameters struct {
}

type Result struct {
	Comment string `json:"comment"`
	Id string `json:"id"`
	ResultMaximum float64 `json:"resultMaximum"`
	ResultScore float64 `json:"resultScore"`
	ScoreOf string `json:"scoreOf"`
	UserId string `json:"userId"`
}

type ResultLinks struct {
	Assessment string `json:"assessment"`
	Assessor string `json:"assessor"`
	User string `json:"user"`
}

type Role struct {
	Account json.RawMessage `json:"account"`
	BaseRoleType string `json:"base_role_type"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	IsAccountRole bool `json:"is_account_role"`
	Label string `json:"label"`
	LastUpdatedAt string `json:"last_updated_at"`
	Permissions json.RawMessage `json:"permissions"`
	Role string `json:"role"`
	WorkflowState string `json:"workflow_state"`
}

type RolePermissions struct {
	AppliesToDescendants bool `json:"applies_to_descendants"`
	AppliesToSelf bool `json:"applies_to_self"`
	Enabled bool `json:"enabled"`
	Explicit bool `json:"explicit"`
	Locked bool `json:"locked"`
	PriorDefault bool `json:"prior_default"`
	Readonly bool `json:"readonly"`
}

type Rubric struct {
	Assessments json.RawMessage `json:"assessments"`
	Associations json.RawMessage `json:"associations"`
	ContextId int `json:"context_id"`
	ContextType string `json:"context_type"`
	Data json.RawMessage `json:"data"`
	FreeFormCriterionComments bool `json:"free_form_criterion_comments"`
	HideScoreTotal bool `json:"hide_score_total"`
	Id int `json:"id"`
	PointsPossible int `json:"points_possible"`
	ReadOnly bool `json:"read_only"`
	Reusable bool `json:"reusable"`
	Title string `json:"title"`
}

type RubricAssessment struct {
	ArtifactAttempt int `json:"artifact_attempt"`
	ArtifactId int `json:"artifact_id"`
	ArtifactType string `json:"artifact_type"`
	AssessmentType string `json:"assessment_type"`
	AssessorId int `json:"assessor_id"`
	Comments json.RawMessage `json:"comments"`
	Data json.RawMessage `json:"data"`
	Id int `json:"id"`
	RubricAssociationId int `json:"rubric_association_id"`
	RubricId int `json:"rubric_id"`
	Score int `json:"score"`
}

type RubricAssociation struct {
	AssociationId int `json:"association_id"`
	AssociationType string `json:"association_type"`
	HideOutcomeResults bool `json:"hide_outcome_results"`
	HidePoints bool `json:"hide_points"`
	HideScoreTotal bool `json:"hide_score_total"`
	Id int `json:"id"`
	Purpose string `json:"purpose"`
	RubricId int `json:"rubric_id"`
	SummaryData string `json:"summary_data"`
	UseForGrading bool `json:"use_for_grading"`
}

type RubricCriteria struct {
	CriterionUseRange bool `json:"criterion_use_range"`
	Description string `json:"description"`
	Id string `json:"id"`
	IgnoreForScoring bool `json:"ignore_for_scoring"`
	LearningOutcomeId string `json:"learning_outcome_id"`
	LongDescription string `json:"long_description"`
	Points int `json:"points"`
	Ratings json.RawMessage `json:"ratings"`
	VendorGuid string `json:"vendor_guid"`
}

type RubricCriterion struct {
	CriterionUseRange bool `json:"criterion_use_range"`
	Description string `json:"description"`
	Id string `json:"id"`
	LongDescription string `json:"long_description"`
	Points int `json:"points"`
	Ratings json.RawMessage `json:"ratings"`
}

type RubricRating struct {
	CriterionId string `json:"criterion_id"`
	Description string `json:"description"`
	Id string `json:"id"`
	LongDescription string `json:"long_description"`
	Points int `json:"points"`
}

type SSOSettings struct {
	AuthDiscoveryUrl string `json:"auth_discovery_url"`
	ChangePasswordUrl string `json:"change_password_url"`
	LoginHandleName string `json:"login_handle_name"`
	UnknownUserUrl string `json:"unknown_user_url"`
}

type Scope struct {
	Action string `json:"action"`
	Controller string `json:"controller"`
	Resource string `json:"resource"`
	ResourceName string `json:"resource_name"`
	Scope string `json:"scope"`
	Verb string `json:"verb"`
}

type Score struct {
	ActivityProgress string `json:"activityProgress"`
	Comment string `json:"comment"`
	GradingProgress string `json:"gradingProgress"`
	ScoreGiven float64 `json:"scoreGiven"`
	ScoreMaximum float64 `json:"scoreMaximum"`
	Submission json.RawMessage `json:"submission"`
	Timestamp string `json:"timestamp"`
	UserId string `json:"userId"`
}

type ScoreStatistic struct {
	LowerQ int `json:"lower_q"`
	Max int `json:"max"`
	Mean int `json:"mean"`
	Median int `json:"median"`
	Min int `json:"min"`
	UpperQ int `json:"upper_q"`
}

type SearchResult struct {
	Body string `json:"body"`
	ContentId int `json:"content_id"`
	ContentType string `json:"content_type"`
	Distance float64 `json:"distance"`
	HtmlUrl string `json:"html_url"`
	Title string `json:"title"`
}

type SearchableAccount struct {
	DisplayPath json.RawMessage `json:"display_path"`
	Id string `json:"id"`
	Name string `json:"name"`
	SisId string `json:"sis_id"`
}

type SearchableCourse struct {
	CourseCode string `json:"course_code"`
	DisplayPath json.RawMessage `json:"display_path"`
	Id string `json:"id"`
	Name string `json:"name"`
	SisId string `json:"sis_id"`
}

type Section struct {
	CourseId int `json:"course_id"`
	EndAt string `json:"end_at"`
	Id int `json:"id"`
	IntegrationId string `json:"integration_id"`
	Name string `json:"name"`
	NonxlistCourseId int `json:"nonxlist_course_id"`
	RestrictEnrollmentsToSectionDates bool `json:"restrict_enrollments_to_section_dates"`
	SisCourseId string `json:"sis_course_id"`
	SisImportId int `json:"sis_import_id"`
	SisSectionId string `json:"sis_section_id"`
	StartAt string `json:"start_at"`
	Students json.RawMessage `json:"students"`
	TotalStudents int `json:"total_students"`
}

type SectionAssignmentOverrideAttributes struct {
	DueAt string `json:"due_at"`
	LockAt string `json:"lock_at"`
	OverrideTitle string `json:"override_title"`
	UnlockAt string `json:"unlock_at"`
}

type SectionAttributes struct {
	Id int `json:"id"`
	IntegrationId string `json:"integration_id"`
	Name string `json:"name"`
	OriginCourse json.RawMessage `json:"origin_course"`
	Override json.RawMessage `json:"override"`
	SisId string `json:"sis_id"`
	XlistCourse json.RawMessage `json:"xlist_course"`
}

type SharedBrandConfig struct {
	AccountId string `json:"account_id"`
	BrandConfigMd5 string `json:"brand_config_md5"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	Name string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

type SisAssignment struct {
	AssignmentGroup json.RawMessage `json:"assignment_group"`
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	DueAt string `json:"due_at"`
	Id int `json:"id"`
	IncludeInFinalGrade bool `json:"include_in_final_grade"`
	IntegrationData string `json:"integration_data"`
	IntegrationId string `json:"integration_id"`
	LockAt string `json:"lock_at"`
	Name string `json:"name"`
	PointsPossible int `json:"points_possible"`
	Sections json.RawMessage `json:"sections"`
	SubmissionTypes json.RawMessage `json:"submission_types"`
	UnlockAt string `json:"unlock_at"`
	UserOverrides json.RawMessage `json:"user_overrides"`
}

type SisImport struct {
	AddSisStickiness bool `json:"add_sis_stickiness"`
	BatchMode bool `json:"batch_mode"`
	BatchModeTermId string `json:"batch_mode_term_id"`
	ClearSisStickiness bool `json:"clear_sis_stickiness"`
	CreatedAt string `json:"created_at"`
	CsvAttachments json.RawMessage `json:"csv_attachments"`
	Data json.RawMessage `json:"data"`
	DiffedAgainstImportId int `json:"diffed_against_import_id"`
	DiffingDataSetIdentifier string `json:"diffing_data_set_identifier"`
	DiffingRemaster bool `json:"diffing_remaster"`
	DiffingThresholdExceeded bool `json:"diffing_threshold_exceeded"`
	EndedAt string `json:"ended_at"`
	ErrorsAttachment json.RawMessage `json:"errors_attachment"`
	Id int `json:"id"`
	MultiTermBatchMode bool `json:"multi_term_batch_mode"`
	OverrideSisStickiness bool `json:"override_sis_stickiness"`
	ProcessingErrors json.RawMessage `json:"processing_errors"`
	ProcessingWarnings json.RawMessage `json:"processing_warnings"`
	Progress string `json:"progress"`
	SkipDeletes bool `json:"skip_deletes"`
	Statistics json.RawMessage `json:"statistics"`
	UpdatedAt string `json:"updated_at"`
	User json.RawMessage `json:"user"`
	WorkflowState string `json:"workflow_state"`
}

type SisImportCounts struct {
	AbstractCourses int `json:"abstract_courses"`
	Accounts int `json:"accounts"`
	BatchCoursesDeleted int `json:"batch_courses_deleted"`
	BatchEnrollmentsDeleted int `json:"batch_enrollments_deleted"`
	BatchSectionsDeleted int `json:"batch_sections_deleted"`
	Courses int `json:"courses"`
	Enrollments int `json:"enrollments"`
	ErrorCount int `json:"error_count"`
	GradePublishingResults int `json:"grade_publishing_results"`
	GroupMemberships int `json:"group_memberships"`
	Groups int `json:"groups"`
	Sections int `json:"sections"`
	Terms int `json:"terms"`
	Users int `json:"users"`
	WarningCount int `json:"warning_count"`
	Xlists int `json:"xlists"`
}

type SisImportData struct {
	Counts json.RawMessage `json:"counts"`
	ImportType string `json:"import_type"`
	SuppliedBatches json.RawMessage `json:"supplied_batches"`
}

type SisImportError struct {
	File string `json:"file"`
	Message string `json:"message"`
	Row int `json:"row"`
	RowInfo string `json:"row_info"`
	SisImportId int `json:"sis_import_id"`
}

type SisImportStatistic struct {
	Concluded int `json:"concluded"`
	Created int `json:"created"`
	Deactivated int `json:"deactivated"`
	Deleted int `json:"deleted"`
	Restored int `json:"restored"`
}

type SisImportStatistics struct {
	AbstractCourse json.RawMessage `json:"AbstractCourse"`
	Account json.RawMessage `json:"Account"`
	AccountUser json.RawMessage `json:"AccountUser"`
	CommunicationChannel json.RawMessage `json:"CommunicationChannel"`
	Course json.RawMessage `json:"Course"`
	CourseSection json.RawMessage `json:"CourseSection"`
	Enrollment json.RawMessage `json:"Enrollment"`
	EnrollmentTerm json.RawMessage `json:"EnrollmentTerm"`
	Group json.RawMessage `json:"Group"`
	GroupCategory json.RawMessage `json:"GroupCategory"`
	GroupMembership json.RawMessage `json:"GroupMembership"`
	Pseudonym json.RawMessage `json:"Pseudonym"`
	UserObserver json.RawMessage `json:"UserObserver"`
	TotalStateChanges int `json:"total_state_changes"`
}

type StudentAttributes struct {
	SisUserId string `json:"sis_user_id"`
	UserId int `json:"user_id"`
}

type Submission struct {
	Id int `json:"id"`
	StudentEnteredScore string `json:"student_entered_score"`
}

type SubmissionComment struct {
	Author string `json:"author"`
	AuthorId int `json:"author_id"`
	AuthorName string `json:"author_name"`
	Comment string `json:"comment"`
	CreatedAt string `json:"created_at"`
	EditedAt string `json:"edited_at"`
	Id int `json:"id"`
	MediaComment json.RawMessage `json:"media_comment"`
}

type SubmissionHistory struct {
	SubmissionId int `json:"submission_id"`
	Versions json.RawMessage `json:"versions"`
}

type SubmissionVersion struct {
	AssignmentId int `json:"assignment_id"`
	AssignmentName string `json:"assignment_name"`
	Body string `json:"body"`
	CurrentGrade string `json:"current_grade"`
	CurrentGradedAt string `json:"current_graded_at"`
	CurrentGrader string `json:"current_grader"`
	GradeMatchesCurrentSubmission bool `json:"grade_matches_current_submission"`
	GradedAt string `json:"graded_at"`
	Grader string `json:"grader"`
	GraderId int `json:"grader_id"`
	Id int `json:"id"`
	NewGrade string `json:"new_grade"`
	NewGradedAt string `json:"new_graded_at"`
	NewGrader string `json:"new_grader"`
	PreviousGrade string `json:"previous_grade"`
	PreviousGradedAt string `json:"previous_graded_at"`
	PreviousGrader string `json:"previous_grader"`
	Score int `json:"score"`
	SubmissionType string `json:"submission_type"`
	Url string `json:"url"`
	UserId int `json:"user_id"`
	UserName string `json:"user_name"`
	WorkflowState string `json:"workflow_state"`
}

type Tab struct {
	Hidden bool `json:"hidden"`
	HtmlUrl string `json:"html_url"`
	Id string `json:"id"`
	Label string `json:"label"`
	Position int `json:"position"`
	Type string `json:"type"`
	Visibility string `json:"visibility"`
}

type TemporaryEnrollmentPairing struct {
	Id int `json:"id"`
	WorkflowState string `json:"workflow_state"`
}

type Term struct {
	EndAt string `json:"end_at"`
	Id int `json:"id"`
	Name string `json:"name"`
	StartAt string `json:"start_at"`
}

type TermsOfService struct {
	AccountId int `json:"account_id"`
	Content string `json:"content"`
	Id int `json:"id"`
	Passive bool `json:"passive"`
	SelfRegistrationType string `json:"self_registration_type"`
	TermsType string `json:"terms_type"`
}

type Token struct {
	AppName string `json:"app_name"`
	CanManuallyRegenerate bool `json:"can_manually_regenerate"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
	Id int `json:"id"`
	Purpose string `json:"purpose"`
	RealUserId int `json:"real_user_id"`
	RememberAccess bool `json:"remember_access"`
	Scopes json.RawMessage `json:"scopes"`
	Token string `json:"token"`
	TokenHint string `json:"token_hint"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type ToolConfiguration struct {
	DeveloperKeyId int `json:"developer_key_id"`
	Settings json.RawMessage `json:"settings"`
}

type ToolSetting struct {
	ResourceTypeCode string `json:"resource_type_code"`
	ResourceUrl string `json:"resource_url"`
}

type TurnitinSettings struct {
	ExcludeBiblio bool `json:"exclude_biblio"`
	ExcludeQuoted bool `json:"exclude_quoted"`
	ExcludeSmallMatchesType string `json:"exclude_small_matches_type"`
	ExcludeSmallMatchesValue int `json:"exclude_small_matches_value"`
	InternetCheck bool `json:"internet_check"`
	JournalCheck bool `json:"journal_check"`
	OriginalityReportVisibility string `json:"originality_report_visibility"`
	SPaperCheck bool `json:"s_paper_check"`
}

type UpdatedEventData struct {
	ConcludeAt json.RawMessage `json:"conclude_at"`
	IsPublic json.RawMessage `json:"is_public"`
	Name json.RawMessage `json:"name"`
	StartAt json.RawMessage `json:"start_at"`
}

type UsageRights struct {
	FileIds json.RawMessage `json:"file_ids"`
	LegalCopyright string `json:"legal_copyright"`
	License string `json:"license"`
	LicenseName string `json:"license_name"`
	Message string `json:"message"`
	UseJustification string `json:"use_justification"`
}

type User struct {
	AvatarState string `json:"avatar_state"`
	AvatarUrl string `json:"avatar_url"`
	Bio string `json:"bio"`
	Email string `json:"email"`
	Enrollments json.RawMessage `json:"enrollments"`
	FirstName string `json:"first_name"`
	Id int `json:"id"`
	IntegrationId string `json:"integration_id"`
	LastLogin string `json:"last_login"`
	LastName string `json:"last_name"`
	Locale string `json:"locale"`
	LoginId string `json:"login_id"`
	Name string `json:"name"`
	Pronouns string `json:"pronouns"`
	ShortName string `json:"short_name"`
	SisImportId int `json:"sis_import_id"`
	SisUserId string `json:"sis_user_id"`
	SortableName string `json:"sortable_name"`
	TimeZone string `json:"time_zone"`
}

type UserAssignmentOverrideAttributes struct {
	DueAt string `json:"due_at"`
	Id int `json:"id"`
	LockAt string `json:"lock_at"`
	Students json.RawMessage `json:"students"`
	Title string `json:"title"`
	UnlockAt string `json:"unlock_at"`
}

type UserDisplay struct {
	AvatarImageUrl string `json:"avatar_image_url"`
	HtmlUrl string `json:"html_url"`
	Id int `json:"id"`
	ShortName string `json:"short_name"`
}

type WebZipExport struct {
	ContentExportId int `json:"content_export_id"`
	CourseId int `json:"course_id"`
	CreatedAt string `json:"created_at"`
	Id int `json:"id"`
	ProgressId int `json:"progress_id"`
	ProgressUrl string `json:"progress_url"`
	UpdatedAt string `json:"updated_at"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
	ZipAttachment json.RawMessage `json:"zip_attachment"`
}

type ePortfolio struct {
	CreatedAt string `json:"created_at"`
	DeletedAt string `json:"deleted_at"`
	Id int `json:"id"`
	Name string `json:"name"`
	Public bool `json:"public"`
	SpamStatus string `json:"spam_status"`
	UpdatedAt string `json:"updated_at"`
	UserId int `json:"user_id"`
	WorkflowState string `json:"workflow_state"`
}

type ePortfolioPage struct {
	Content string `json:"content"`
	CreatedAt string `json:"created_at"`
	EportfolioId int `json:"eportfolio_id"`
	Id int `json:"id"`
	Name string `json:"name"`
	Position int `json:"position"`
	UpdatedAt string `json:"updated_at"`
}
