// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsBulkEnrollmentEnrollmentsApiCmd(flags *rootFlags) *cobra.Command {
	var bodyCourseIds string
	var bodyEnrollmentRoleId int
	var bodyEnrollmentType string
	var bodyUserIds string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "enrollments-api <account_id>",
		Aliases: []string{"create"},
		Short: "Enrolls multiple users in one or more courses in a single operation.",
		Example: "  canvas-pp-cli accounts bulk-enrollment enrollments-api 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "bulk-enrollment.enrollments-api", "pp:method": "POST", "pp:path": "/accounts/{account_id}/bulk_enrollment"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("course-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "course-ids")
				}
				if !cmd.Flags().Changed("user-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "user-ids")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/bulk_enrollment"
			path = replacePathParam(path, "account_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCourseIds != "" {
					var parsedCourseIds any
					if err := json.Unmarshal([]byte(bodyCourseIds), &parsedCourseIds); err != nil {
						return fmt.Errorf("parsing --course-ids JSON: %w", err)
					}
					body["course_ids"] = parsedCourseIds
				}
				if bodyEnrollmentRoleId != 0 {
					body["enrollment_role_id"] = bodyEnrollmentRoleId
				}
				if bodyEnrollmentType != "" {
					body["enrollment_type"] = bodyEnrollmentType
				}
				if bodyUserIds != "" {
					var parsedUserIds any
					if err := json.Unmarshal([]byte(bodyUserIds), &parsedUserIds); err != nil {
						return fmt.Errorf("parsing --user-ids JSON: %w", err)
					}
					body["user_ids"] = parsedUserIds
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "bulk-enrollment",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCourseIds, "course-ids", "", "[Required, Integer] The course IDs to enroll each user in.")
	cmd.Flags().IntVar(&bodyEnrollmentRoleId, "enrollment-role-id", 0, "Optional custom course-level role id to apply to created enrollments.")
	cmd.Flags().StringVar(&bodyEnrollmentType, "enrollment-type", "", "Enroll each user as a student, teacher, TA, observer, or designer. If no value is given, the type will be...")
	cmd.Flags().StringVar(&bodyUserIds, "user-ids", "", "[Required, Integer] The user IDs to enroll in the courses.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
