// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Manage users",
	}

	cmd.AddCommand(newAccountsUsersAccountsRemoveCmd(flags))
	cmd.AddCommand(newAccountsUsersAccountsRemoveAccountsCmd(flags))
	cmd.AddCommand(newAccountsUsersAccountsRestoreCmd(flags))
	cmd.AddCommand(newAccountsUsersAccountsUpdateCmd(flags))
	cmd.AddCommand(newAccountsUsersServiceCredentialsApiIndexCmd(flags))
	cmd.AddCommand(newAccountsUsersServiceCredentialsCreateCmd(flags))
	return cmd
}
