// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsAdminsIndexCmd(flags *rootFlags) *cobra.Command {
	var flagUserId string
	var flagSearchTerm string
	var flagIncludeDeleted bool
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "index <account_id>",
		Aliases: []string{"get"},
		Short: "A paginated list of the admins in the account",
		Example: "  canvas-cli accounts admins index 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "admins.index", "pp:method": "GET", "pp:path": "/accounts/{account_id}/admins", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/admins"
			path = replacePathParam(path, "account_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "admins", path, map[string]string{
				"user_id": fmt.Sprintf("%v", flagUserId),
				"search_term": fmt.Sprintf("%v", flagSearchTerm),
				"include_deleted": fmt.Sprintf("%v", flagIncludeDeleted),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "[[Integer]] Scope the results to those with user IDs equal to any of the IDs specified here.")
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial name or full ID of the admins to match and return in the results list. Must be at least 2 characters.")
	cmd.Flags().BoolVar(&flagIncludeDeleted, "include-deleted", false, "When set to true, returns admins who have been deleted")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
