// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsGradingPeriodSetsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyEnrollmentTermIds string
	var bodyGradingPeriodSetDisplayTotalsForAllGradingPeriods string
	var bodyGradingPeriodSetTitle string
	var bodyGradingPeriodSetWeighted string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <account_id> <id>",
		Short: "Update an existing grading period set <b>204 No Content</b> response code is returned if the update was successful.",
		Example: "  canvas-pp-cli accounts grading-period-sets update 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --grading-period-set-title example-resource",
		Annotations: map[string]string{"pp:endpoint": "grading-period-sets.update", "pp:method": "PATCH", "pp:path": "/accounts/{account_id}/grading_period_sets/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("grading-period-set-title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "grading-period-set-title")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/grading_period_sets/{id}"
			path = replacePathParam(path, "account_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyEnrollmentTermIds != "" {
					var parsedEnrollmentTermIds any
					if err := json.Unmarshal([]byte(bodyEnrollmentTermIds), &parsedEnrollmentTermIds); err != nil {
						return fmt.Errorf("parsing --enrollment-term-ids JSON: %w", err)
					}
					body["enrollment_term_ids"] = parsedEnrollmentTermIds
				}
				if bodyGradingPeriodSetDisplayTotalsForAllGradingPeriods != "" {
					var parsedGradingPeriodSetDisplayTotalsForAllGradingPeriods any
					if err := json.Unmarshal([]byte(bodyGradingPeriodSetDisplayTotalsForAllGradingPeriods), &parsedGradingPeriodSetDisplayTotalsForAllGradingPeriods); err != nil {
						return fmt.Errorf("parsing --grading-period-set-display-totals-for-all-grading-periods JSON: %w", err)
					}
					body["grading_period_set[][display_totals_for_all_grading_periods]"] = bodyGradingPeriodSetDisplayTotalsForAllGradingPeriods
				}
				if bodyGradingPeriodSetTitle != "" {
					var parsedGradingPeriodSetTitle any
					if err := json.Unmarshal([]byte(bodyGradingPeriodSetTitle), &parsedGradingPeriodSetTitle); err != nil {
						return fmt.Errorf("parsing --grading-period-set-title JSON: %w", err)
					}
					body["grading_period_set[][title]"] = bodyGradingPeriodSetTitle
				}
				if bodyGradingPeriodSetWeighted != "" {
					var parsedGradingPeriodSetWeighted any
					if err := json.Unmarshal([]byte(bodyGradingPeriodSetWeighted), &parsedGradingPeriodSetWeighted); err != nil {
						return fmt.Errorf("parsing --grading-period-set-weighted JSON: %w", err)
					}
					body["grading_period_set[][weighted]"] = bodyGradingPeriodSetWeighted
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "grading-period-sets",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyEnrollmentTermIds, "enrollment-term-ids", "", "[Array] A list of associated term ids for the grading period set")
	cmd.Flags().StringVar(&bodyGradingPeriodSetDisplayTotalsForAllGradingPeriods, "grading-period-set-display-totals-for-all-grading-periods", "", "[Boolean] A boolean to determine whether the totals for all grading periods in the set are displayed")
	cmd.Flags().StringVar(&bodyGradingPeriodSetTitle, "grading-period-set-title", "", "[Required, String] The title of the grading period set")
	cmd.Flags().StringVar(&bodyGradingPeriodSetWeighted, "grading-period-set-weighted", "", "[Boolean] A boolean to determine whether the grading periods in the set are weighted")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
