// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountCalendarsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-calendars",
		Short: "Manage account calendars",
	}

	cmd.AddCommand(newAccountCalendarsApiIndexCmd(flags))
	cmd.AddCommand(newAccountCalendarsApiShowCmd(flags))
	cmd.AddCommand(newAccountCalendarsApiUpdateCmd(flags))
	return cmd
}
