// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsBlackoutDatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "blackout-dates",
		Short: "API for accessing blackout date information.",
	}

	cmd.AddCommand(newAccountsBlackoutDatesCreateForAccountsCmd(flags))
	cmd.AddCommand(newAccountsBlackoutDatesDestroyForAccountsCmd(flags))
	cmd.AddCommand(newAccountsBlackoutDatesIndexForAccountsCmd(flags))
	cmd.AddCommand(newAccountsBlackoutDatesNewForAccountsCmd(flags))
	cmd.AddCommand(newAccountsBlackoutDatesShowForAccountsCmd(flags))
	cmd.AddCommand(newAccountsBlackoutDatesUpdateForAccountsCmd(flags))
	return cmd
}
