// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsAccountNotificationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-notifications",
		Short: "API for account notifications.",
	}

	cmd.AddCommand(newAccountsAccountNotificationsCreateCmd(flags))
	cmd.AddCommand(newAccountsAccountNotificationsShowCmd(flags))
	cmd.AddCommand(newAccountsAccountNotificationsUpdateCmd(flags))
	cmd.AddCommand(newAccountsAccountNotificationsUserCloseNotificationCmd(flags))
	cmd.AddCommand(newAccountsAccountNotificationsUserIndexCmd(flags))
	return cmd
}
