// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsFeaturesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "features",
		Short: "Manage features",
	}

	cmd.AddCommand(newAccountsFeaturesFlagsDeleteForAccountsCmd(flags))
	cmd.AddCommand(newAccountsFeaturesFlagsEnabledForAccountsCmd(flags))
	cmd.AddCommand(newAccountsFeaturesFlagsIndexForAccountsCmd(flags))
	cmd.AddCommand(newAccountsFeaturesFlagsShowForAccountsCmd(flags))
	cmd.AddCommand(newAccountsFeaturesFlagsUpdateForAccountsCmd(flags))
	return cmd
}
