// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsOutcomeProficiencyApiCreateForAccountsCmd(flags *rootFlags) *cobra.Command {
	var bodyRatingsColor string
	var bodyRatingsDescription string
	var bodyRatingsMastery string
	var bodyRatingsPoints string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "api-create-for-accounts <account_id>",
		Aliases: []string{"create"},
		Short: "Create or update account-level proficiency ratings. These ratings will apply to all sub-accounts, unless they have...",
		Example: "  canvas-pp-cli accounts outcome-proficiency api-create-for-accounts 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "outcome-proficiency.api-create-for-accounts", "pp:method": "POST", "pp:path": "/accounts/{account_id}/outcome_proficiency"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/outcome_proficiency"
			path = replacePathParam(path, "account_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyRatingsColor != "" {
					var parsedRatingsColor any
					if err := json.Unmarshal([]byte(bodyRatingsColor), &parsedRatingsColor); err != nil {
						return fmt.Errorf("parsing --ratings-color JSON: %w", err)
					}
					body["ratings[][color]"] = bodyRatingsColor
				}
				if bodyRatingsDescription != "" {
					var parsedRatingsDescription any
					if err := json.Unmarshal([]byte(bodyRatingsDescription), &parsedRatingsDescription); err != nil {
						return fmt.Errorf("parsing --ratings-description JSON: %w", err)
					}
					body["ratings[][description]"] = bodyRatingsDescription
				}
				if bodyRatingsMastery != "" {
					var parsedRatingsMastery any
					if err := json.Unmarshal([]byte(bodyRatingsMastery), &parsedRatingsMastery); err != nil {
						return fmt.Errorf("parsing --ratings-mastery JSON: %w", err)
					}
					body["ratings[][mastery]"] = bodyRatingsMastery
				}
				if bodyRatingsPoints != "" {
					var parsedRatingsPoints any
					if err := json.Unmarshal([]byte(bodyRatingsPoints), &parsedRatingsPoints); err != nil {
						return fmt.Errorf("parsing --ratings-points JSON: %w", err)
					}
					body["ratings[][points]"] = bodyRatingsPoints
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "outcome-proficiency",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyRatingsColor, "ratings-color", "", "[Integer] The color associated with the rating level. Should be a hex color code like '00FFFF'.")
	cmd.Flags().StringVar(&bodyRatingsDescription, "ratings-description", "", "[String] The description of the rating level.")
	cmd.Flags().StringVar(&bodyRatingsMastery, "ratings-mastery", "", "[Integer] Indicates the rating level where mastery is first achieved. Only one rating in a proficiency should be...")
	cmd.Flags().StringVar(&bodyRatingsPoints, "ratings-points", "", "[Integer] The non-negative number of points of the rating level. Points across ratings should be strictly decreasing...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
