// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsExternalToolsTimingMetaCreateForAccountsCmd(flags *rootFlags) *cobra.Command {
	var bodyPlacementConfigurationKeyPlacementName string
	var bodyClientId string
	var bodyConfigType string
	var bodyConfigUrl string
	var bodyConfigXml string
	var bodyConsumerKey string
	var bodyCustomFields string
	var bodyDescription string
	var bodyDomain string
	var bodyIconUrl string
	var bodyIsRceFavorite bool
	var bodyName string
	var bodyNotSelectable bool
	var bodyOauthCompliant bool
	var bodyPrivacyLevel string
	var bodySharedSecret string
	var bodyText string
	var bodyUnifiedToolId string
	var bodyUrl string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "timing-meta-create-for-accounts <account_id>",
		Short: "Create an external tool in the specified course/account. The created tool will be returned, see the 'show' endpoint...",
		Example: "  canvas-cli accounts external-tools timing-meta-create-for-accounts 550e8400-e29b-41d4-a716-446655440000 --client-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "external-tools.timing-meta-create-for-accounts", "pp:method": "POST", "pp:path": "/accounts/{account_id}/external_tools"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("client-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-id")
				}
				if !cmd.Flags().Changed("config-url") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "config-url")
				}
				if !cmd.Flags().Changed("config-xml") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "config-xml")
				}
				if !cmd.Flags().Changed("consumer-key") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "consumer-key")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("privacy-level") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "privacy-level")
				}
				if !cmd.Flags().Changed("shared-secret") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "shared-secret")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/external_tools"
			path = replacePathParam(path, "account_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyPlacementConfigurationKeyPlacementName != "" {
					var parsedPlacementConfigurationKeyPlacementName any
					if err := json.Unmarshal([]byte(bodyPlacementConfigurationKeyPlacementName), &parsedPlacementConfigurationKeyPlacementName); err != nil {
						return fmt.Errorf("parsing --placement-configuration-key-placement-name JSON: %w", err)
					}
					body["[<placement_configuration_key>][placement_name]"] = bodyPlacementConfigurationKeyPlacementName
				}
				if bodyClientId != "" {
					body["client_id"] = bodyClientId
				}
				if bodyConfigType != "" {
					body["config_type"] = bodyConfigType
				}
				if bodyConfigUrl != "" {
					body["config_url"] = bodyConfigUrl
				}
				if bodyConfigXml != "" {
					body["config_xml"] = bodyConfigXml
				}
				if bodyConsumerKey != "" {
					body["consumer_key"] = bodyConsumerKey
				}
				if bodyCustomFields != "" {
					var parsedCustomFields any
					if err := json.Unmarshal([]byte(bodyCustomFields), &parsedCustomFields); err != nil {
						return fmt.Errorf("parsing --custom-fields JSON: %w", err)
					}
					body["custom_fields"] = parsedCustomFields
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDomain != "" {
					body["domain"] = bodyDomain
				}
				if bodyIconUrl != "" {
					body["icon_url"] = bodyIconUrl
				}
				if bodyIsRceFavorite != false {
					body["is_rce_favorite"] = bodyIsRceFavorite
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyNotSelectable != false {
					body["not_selectable"] = bodyNotSelectable
				}
				if bodyOauthCompliant != false {
					body["oauth_compliant"] = bodyOauthCompliant
				}
				if bodyPrivacyLevel != "" {
					body["privacy_level"] = bodyPrivacyLevel
				}
				if bodySharedSecret != "" {
					body["shared_secret"] = bodySharedSecret
				}
				if bodyText != "" {
					body["text"] = bodyText
				}
				if bodyUnifiedToolId != "" {
					body["unified_tool_id"] = bodyUnifiedToolId
				}
				if bodyUrl != "" {
					body["url"] = bodyUrl
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "external-tools",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyPlacementConfigurationKeyPlacementName, "placement-configuration-key-placement-name", "", "[variable] Set the <placement_configuration_key> value for a specific placement.")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "The client id is attached to the developer key. If supplied all other parameters are unnecessary and will be ignored")
	cmd.Flags().StringVar(&bodyConfigType, "config-type", "", "Configuration can be passed in as Common Cartridge XML instead of using query parameters. If this value is 'by_url'...")
	cmd.Flags().StringVar(&bodyConfigUrl, "config-url", "", "URL where the server can retrieve an XML tool configuration, as specified in the Common Cartridge XML specification....")
	cmd.Flags().StringVar(&bodyConfigXml, "config-xml", "", "XML tool configuration, as specified in the Common Cartridge XML specification. This is required if 'config_type' is...")
	cmd.Flags().StringVar(&bodyConsumerKey, "consumer-key", "", "The consumer key for the external tool")
	cmd.Flags().StringVar(&bodyCustomFields, "custom-fields", "", "Custom fields")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description of the tool")
	cmd.Flags().StringVar(&bodyDomain, "domain", "", "The domain to match links against. Either 'url' or 'domain' should be set, not both.")
	cmd.Flags().StringVar(&bodyIconUrl, "icon-url", "", "The url of the icon to show for this tool")
	cmd.Flags().BoolVar(&bodyIsRceFavorite, "is-rce-favorite", false, "(Deprecated in favor of {api:ExternalToolsController#mark_rce_favorite Mark tool to RCE Favorites} and...")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the tool")
	cmd.Flags().BoolVar(&bodyNotSelectable, "not-selectable", false, "Default: false. If set to true, and if resource_selection is set to false, the tool won't show up in the external...")
	cmd.Flags().BoolVar(&bodyOauthCompliant, "oauth-compliant", false, "Default: false, if set to true LTI query params will not be copied to the post body.")
	cmd.Flags().StringVar(&bodyPrivacyLevel, "privacy-level", "", "How much user information to send to the external tool.")
	cmd.Flags().StringVar(&bodySharedSecret, "shared-secret", "", "The shared secret with the external tool")
	cmd.Flags().StringVar(&bodyText, "text", "", "The default text to show for this tool")
	cmd.Flags().StringVar(&bodyUnifiedToolId, "unified-tool-id", "", "The unique identifier for the tool in LearnPlatform")
	cmd.Flags().StringVar(&bodyUrl, "url", "", "The url to match links against. Either 'url' or 'domain' should be set, not both.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
