// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsSisImportsApiCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddSisStickiness bool
	var bodyAttachment string
	var bodyBatchMode bool
	var bodyBatchModeEnrollmentDropStatus string
	var bodyBatchModeTermId string
	var bodyChangeThreshold int
	var bodyClearSisStickiness bool
	var bodyDiffRowCountThreshold int
	var bodyDiffingDataSetIdentifier string
	var bodyDiffingDropStatus string
	var bodyDiffingRemasterDataSet bool
	var bodyDiffingUserRemoveStatus string
	var bodyExtension string
	var bodyImportType string
	var bodyMultiTermBatchMode bool
	var bodyOverrideSisStickiness bool
	var bodyPreAttachment string
	var bodySkipDeletes bool
	var bodyUpdateSisIdIfLoginClaimed bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "api-create <account_id>",
		Aliases: []string{"create"},
		Short: "Import SIS data into Canvas. Must be on a root account with SIS imports enabled. For more information on the format...",
		Example: "  canvas-cli accounts sis-imports api-create 550e8400-e29b-41d4-a716-446655440000 --attachment example-value",
		Annotations: map[string]string{"pp:endpoint": "sis-imports.api-create", "pp:method": "POST", "pp:path": "/accounts/{account_id}/sis_imports"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("attachment") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "attachment")
				}
				if !cmd.Flags().Changed("batch-mode-term-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "batch-mode-term-id")
				}
				if !cmd.Flags().Changed("change-threshold") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "change-threshold")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/sis_imports"
			path = replacePathParam(path, "account_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAddSisStickiness != false {
					body["add_sis_stickiness"] = bodyAddSisStickiness
				}
				if bodyAttachment != "" {
					body["attachment"] = bodyAttachment
				}
				if bodyBatchMode != false {
					body["batch_mode"] = bodyBatchMode
				}
				if bodyBatchModeEnrollmentDropStatus != "" {
					body["batch_mode_enrollment_drop_status"] = bodyBatchModeEnrollmentDropStatus
				}
				if bodyBatchModeTermId != "" {
					body["batch_mode_term_id"] = bodyBatchModeTermId
				}
				if bodyChangeThreshold != 0 {
					body["change_threshold"] = bodyChangeThreshold
				}
				if bodyClearSisStickiness != false {
					body["clear_sis_stickiness"] = bodyClearSisStickiness
				}
				if bodyDiffRowCountThreshold != 0 {
					body["diff_row_count_threshold"] = bodyDiffRowCountThreshold
				}
				if bodyDiffingDataSetIdentifier != "" {
					body["diffing_data_set_identifier"] = bodyDiffingDataSetIdentifier
				}
				if bodyDiffingDropStatus != "" {
					body["diffing_drop_status"] = bodyDiffingDropStatus
				}
				if bodyDiffingRemasterDataSet != false {
					body["diffing_remaster_data_set"] = bodyDiffingRemasterDataSet
				}
				if bodyDiffingUserRemoveStatus != "" {
					body["diffing_user_remove_status"] = bodyDiffingUserRemoveStatus
				}
				if bodyExtension != "" {
					body["extension"] = bodyExtension
				}
				if bodyImportType != "" {
					body["import_type"] = bodyImportType
				}
				if bodyMultiTermBatchMode != false {
					body["multi_term_batch_mode"] = bodyMultiTermBatchMode
				}
				if bodyOverrideSisStickiness != false {
					body["override_sis_stickiness"] = bodyOverrideSisStickiness
				}
				if bodyPreAttachment != "" {
					var parsedPreAttachment any
					if err := json.Unmarshal([]byte(bodyPreAttachment), &parsedPreAttachment); err != nil {
						return fmt.Errorf("parsing --pre-attachment JSON: %w", err)
					}
					body["pre_attachment"] = parsedPreAttachment
				}
				if bodySkipDeletes != false {
					body["skip_deletes"] = bodySkipDeletes
				}
				if bodyUpdateSisIdIfLoginClaimed != false {
					body["update_sis_id_if_login_claimed"] = bodyUpdateSisIdIfLoginClaimed
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "sis-imports",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&bodyAddSisStickiness, "add-sis-stickiness", false, "This option, if present, will process all changes as if they were UI changes. This means that 'stickiness' will be...")
	cmd.Flags().StringVar(&bodyAttachment, "attachment", "", "There are three ways to post SIS import data: 1. As a multipart/form-data form field named +attachment+ 2. As a raw...")
	cmd.Flags().BoolVar(&bodyBatchMode, "batch-mode", false, "If set, this SIS import will be run in batch mode, deleting any data previously imported via SIS that is not present...")
	cmd.Flags().StringVar(&bodyBatchModeEnrollmentDropStatus, "batch-mode-enrollment-drop-status", "", "If batch_mode_enrollment_drop_status is passed, this SIS import will use this status for enrollments that are not...")
	cmd.Flags().StringVar(&bodyBatchModeTermId, "batch-mode-term-id", "", "Limit deletions to only this term. Required if batch mode is enabled.")
	cmd.Flags().IntVar(&bodyChangeThreshold, "change-threshold", 0, "If set with batch_mode, the batch cleanup process will not run if the number of items deleted is higher than the...")
	cmd.Flags().BoolVar(&bodyClearSisStickiness, "clear-sis-stickiness", false, "This option, if present, will clear 'stickiness' from all fields processed by this import. Requires that...")
	cmd.Flags().IntVar(&bodyDiffRowCountThreshold, "diff-row-count-threshold", 0, "If set with diffing, diffing will not be performed if the number of rows to be run in the fully calculated diff...")
	cmd.Flags().StringVar(&bodyDiffingDataSetIdentifier, "diffing-data-set-identifier", "", "If set on a CSV import, Canvas will attempt to optimize the SIS import by comparing this set of CSVs to the previous...")
	cmd.Flags().StringVar(&bodyDiffingDropStatus, "diffing-drop-status", "", "If diffing_drop_status is passed, this SIS import will use this status for enrollments that are not included in the...")
	cmd.Flags().BoolVar(&bodyDiffingRemasterDataSet, "diffing-remaster-data-set", false, "If true, and diffing_data_set_identifier is sent, this SIS import will be part of the data set, but diffing will not...")
	cmd.Flags().StringVar(&bodyDiffingUserRemoveStatus, "diffing-user-remove-status", "", "For users removed from one batch to the next one using the same diffing_data_set_identifier, set their status to the...")
	cmd.Flags().StringVar(&bodyExtension, "extension", "", "Recommended for raw post request style imports. This field will be used to distinguish between zip, xml, csv, and...")
	cmd.Flags().StringVar(&bodyImportType, "import-type", "", "Choose the data format for reading SIS data. With a standard Canvas install, this option can only be...")
	cmd.Flags().BoolVar(&bodyMultiTermBatchMode, "multi-term-batch-mode", false, "Runs batch mode against all terms in terms file. Requires change_threshold.")
	cmd.Flags().BoolVar(&bodyOverrideSisStickiness, "override-sis-stickiness", false, "Default is false. If true, any fields containing “sticky” or UI changes will be overridden. See SIS CSV Format...")
	cmd.Flags().StringVar(&bodyPreAttachment, "pre-attachment", "", "Pre attachment")
	cmd.Flags().BoolVar(&bodySkipDeletes, "skip-deletes", false, "When set the import will skip any deletes. This does not account for objects that are deleted during the batch mode...")
	cmd.Flags().BoolVar(&bodyUpdateSisIdIfLoginClaimed, "update-sis-id-if-login-claimed", false, "This option, if present, will override the old (or non-existent) non-matching SIS ID with the new SIS ID in the...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
