// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsTemporaryEnrollmentPairingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "temporary-enrollment-pairings",
		Short: "Manage temporary enrollment pairings",
	}

	cmd.AddCommand(newAccountsTemporaryEnrollmentPairingsApiCreateCmd(flags))
	cmd.AddCommand(newAccountsTemporaryEnrollmentPairingsApiDestroyCmd(flags))
	cmd.AddCommand(newAccountsTemporaryEnrollmentPairingsApiIndexCmd(flags))
	cmd.AddCommand(newAccountsTemporaryEnrollmentPairingsApiNewCmd(flags))
	cmd.AddCommand(newAccountsTemporaryEnrollmentPairingsApiShowCmd(flags))
	return cmd
}
