// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsCoursesShowForAccountsCmd(flags *rootFlags) *cobra.Command {
	var flagInclude string
	var flagTeacherLimit int

	cmd := &cobra.Command{
		Use:   "show-for-accounts <account_id> <id>",
		Short: "Return information on a single course. Accepts the same include[] parameters as the list action plus:",
		Example: "  canvas-cli accounts courses show-for-accounts 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "courses.show-for-accounts", "pp:method": "GET", "pp:path": "/accounts/{account_id}/courses/{id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/courses/{id}"
			path = replacePathParam(path, "account_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			params := map[string]string{}
			if flagInclude != "" {
				params["include"] = fmt.Sprintf("%v", flagInclude)
			}
			if flagTeacherLimit != 0 {
				params["teacher_limit"] = fmt.Sprintf("%v", flagTeacherLimit)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "courses", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'needs_grading_count'|'syllabus_body'|'public_description'|'total_scores'|'current_grading_period_scores'|'t...")
	cmd.Flags().IntVar(&flagTeacherLimit, "teacher-limit", 0, "The maximum number of teacher enrollments to show. If the course contains more teachers than this, instead of giving...")

	return cmd
}
