// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsAdminsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "admins",
		Short: "Manage account role assignments",
	}

	cmd.AddCommand(newAccountsAdminsCreateCmd(flags))
	cmd.AddCommand(newAccountsAdminsDestroyCmd(flags))
	cmd.AddCommand(newAccountsAdminsIndexCmd(flags))
	cmd.AddCommand(newAccountsAdminsSelfRolesCmd(flags))
	return cmd
}
