// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsCoursesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "courses",
		Short: "API for accessing course information.",
	}

	cmd.AddCommand(newAccountsCoursesAccountsApiCmd(flags))
	cmd.AddCommand(newAccountsCoursesBatchUpdateCmd(flags))
	cmd.AddCommand(newAccountsCoursesCreateCmd(flags))
	cmd.AddCommand(newAccountsCoursesShowForAccountsCmd(flags))
	return cmd
}
