// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsAdminsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyRole string
	var bodyRoleId int
	var bodySendConfirmation bool
	var bodyUserId int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create <account_id>",
		Short: "Flag an existing user as an admin within the account.",
		Example: "  canvas-pp-cli accounts admins create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "admins.create", "pp:method": "POST", "pp:path": "/accounts/{account_id}/admins"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("user-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "user-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/admins"
			path = replacePathParam(path, "account_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyRole != "" {
					var parsedRole any
					if err := json.Unmarshal([]byte(bodyRole), &parsedRole); err != nil {
						return fmt.Errorf("parsing --role JSON: %w", err)
					}
					body["role"] = bodyRole
				}
				if bodyRoleId != 0 {
					body["role_id"] = bodyRoleId
				}
				if bodySendConfirmation != false {
					body["send_confirmation"] = bodySendConfirmation
				}
				if bodyUserId != 0 {
					body["user_id"] = bodyUserId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "admins",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyRole, "role", "", "[DEPRECATED] The user's admin relationship with the account will be created with the given role. Defaults to...")
	cmd.Flags().IntVar(&bodyRoleId, "role-id", 0, "The user's admin relationship with the account will be created with the given role. Defaults to the built-in role...")
	cmd.Flags().BoolVar(&bodySendConfirmation, "send-confirmation", false, "Send a notification email to the new admin if true. Default is true.")
	cmd.Flags().IntVar(&bodyUserId, "user-id", 0, "The id of the user to promote.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
