// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsReportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reports",
		Short: "Manage reports",
	}

	cmd.AddCommand(newAccountsReportsAccountAbortCmd(flags))
	cmd.AddCommand(newAccountsReportsAccountAvailableCmd(flags))
	cmd.AddCommand(newAccountsReportsAccountCreateCmd(flags))
	cmd.AddCommand(newAccountsReportsAccountDestroyCmd(flags))
	cmd.AddCommand(newAccountsReportsAccountIndexCmd(flags))
	cmd.AddCommand(newAccountsReportsAccountShowCmd(flags))
	return cmd
}
