// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsRolesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "roles",
		Short: "Manage roles",
	}

	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorActivateCmd(flags))
	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorAddCmd(flags))
	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorApiIndexCmd(flags))
	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorManageablePermissionsCmd(flags))
	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorRemoveCmd(flags))
	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorShowCmd(flags))
	cmd.AddCommand(newAccountsRolesBadPermissionSettingErrorUpdateCmd(flags))
	return cmd
}
