// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsLoginsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "logins",
		Short: "Copyright (C) 2015 - present Instructure, Inc. This file is part of Canvas. Canvas is free software: you can...",
	}

	cmd.AddCommand(newAccountsLoginsPseudonymsCreateCmd(flags))
	cmd.AddCommand(newAccountsLoginsPseudonymsIndexForAccountsCmd(flags))
	cmd.AddCommand(newAccountsLoginsPseudonymsUpdateCmd(flags))
	return cmd
}
