// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsAuthenticationProvidersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "authentication-providers",
		Short: "Manage authentication providers",
	}

	cmd.AddCommand(newAccountsAuthenticationProvidersCreateCmd(flags))
	cmd.AddCommand(newAccountsAuthenticationProvidersDestroyCmd(flags))
	cmd.AddCommand(newAccountsAuthenticationProvidersIndexCmd(flags))
	cmd.AddCommand(newAccountsAuthenticationProvidersRestoreCmd(flags))
	cmd.AddCommand(newAccountsAuthenticationProvidersShowCmd(flags))
	cmd.AddCommand(newAccountsAuthenticationProvidersUpdateCmd(flags))
	return cmd
}
