// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsSubAccountsAccountsCmd(flags *rootFlags) *cobra.Command {
	var flagRecursive bool
	var flagOrder string
	var flagInclude string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "accounts <account_id>",
		Aliases: []string{"get"},
		Short: "List accounts that are sub-accounts of the given account.",
		Example: "  canvas-pp-cli accounts sub-accounts accounts 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "sub-accounts.accounts", "pp:method": "GET", "pp:path": "/accounts/{account_id}/sub_accounts", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{ "id", "name" }
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/accounts/{account_id}/sub_accounts"
			path = replacePathParam(path, "account_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "sub-accounts", path, map[string]string{
				"recursive": fmt.Sprintf("%v", flagRecursive),
				"order": fmt.Sprintf("%v", flagOrder),
				"include": fmt.Sprintf("%v", flagInclude),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&flagRecursive, "recursive", false, "If true, the entire account tree underneath this account will be returned (though still paginated). If false, only...")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Sorts the accounts by id or name. Only applies when recursive is false. Defaults to id. (one of: id, name)")
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'course_count'|'sub_account_count'] Array of additional information to include. 'course_count':: returns...")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
