// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsRootOutcomeGroupCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "root-outcome-group",
		Short: "Manage root outcome group",
	}

	cmd.AddCommand(newAccountsRootOutcomeGroupOutcomeGroupsApiRedirectForAccountsCmd(flags))
	return cmd
}
