// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsOutcomeGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "outcome-groups",
		Short: "Copyright (C) 2011 - present Instructure, Inc. This file is part of Canvas. Canvas is free software: you can...",
	}

	cmd.AddCommand(newAccountsOutcomeGroupsApiCreateForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiDestroyForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiImportForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiIndexForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiLinkForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiLinkForAccounts2Cmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiOutcomesForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiShowForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiSubgroupsForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiUnlinkForAccountsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsApiUpdateForAccountsCmd(flags))
	return cmd
}
