// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "accounts",
		Short: "API for accessing account data.",
	}

	cmd.AddCommand(newAccountsIndexCmd(flags))
	cmd.AddCommand(newAccountsShowCmd(flags))
	cmd.AddCommand(newAccountsUpdateCmd(flags))
	cmd.AddCommand(newAccountsAccountCalendarsCmd(flags))
	cmd.AddCommand(newAccountsAccountNotificationsCmd(flags))
	cmd.AddCommand(newAccountsAdminsCmd(flags))
	cmd.AddCommand(newAccountsAssignmentsCmd(flags))
	cmd.AddCommand(newAccountsAuthenticationProvidersCmd(flags))
	cmd.AddCommand(newAccountsBlackoutDatesCmd(flags))
	cmd.AddCommand(newAccountsBrandVariablesCmd(flags))
	cmd.AddCommand(newAccountsBulkEnrollmentCmd(flags))
	cmd.AddCommand(newAccountsContentMigrationsCmd(flags))
	cmd.AddCommand(newAccountsCoursesCmd(flags))
	cmd.AddCommand(newAccountsCspSettingsCmd(flags))
	cmd.AddCommand(newAccountsDeveloperKeysCmd(flags))
	cmd.AddCommand(newAccountsEnrollmentsCmd(flags))
	cmd.AddCommand(newAccountsExternalToolsCmd(flags))
	cmd.AddCommand(newAccountsFeaturesCmd(flags))
	cmd.AddCommand(newAccountsFoldersCmd(flags))
	cmd.AddCommand(newAccountsGradingPeriodSetsCmd(flags))
	cmd.AddCommand(newAccountsGradingPeriodsCmd(flags))
	cmd.AddCommand(newAccountsGradingStandardsCmd(flags))
	cmd.AddCommand(newAccountsGroupCategoriesCmd(flags))
	cmd.AddCommand(newAccountsGroupsCmd(flags))
	cmd.AddCommand(newAccountsHelpLinksCmd(flags))
	cmd.AddCommand(newAccountsLoginsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupLinksCmd(flags))
	cmd.AddCommand(newAccountsOutcomeGroupsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeImportsCmd(flags))
	cmd.AddCommand(newAccountsOutcomeProficiencyCmd(flags))
	cmd.AddCommand(newAccountsPermissionsCmd(flags))
	cmd.AddCommand(newAccountsReportsCmd(flags))
	cmd.AddCommand(newAccountsRolesCmd(flags))
	cmd.AddCommand(newAccountsRootOutcomeGroupCmd(flags))
	cmd.AddCommand(newAccountsRubricsCmd(flags))
	cmd.AddCommand(newAccountsScopesCmd(flags))
	cmd.AddCommand(newAccountsSelfRegistrationCmd(flags))
	cmd.AddCommand(newAccountsSettingsCmd(flags))
	cmd.AddCommand(newAccountsSharedBrandConfigsCmd(flags))
	cmd.AddCommand(newAccountsSisImportErrorsCmd(flags))
	cmd.AddCommand(newAccountsSisImportsCmd(flags))
	cmd.AddCommand(newAccountsSsoSettingsCmd(flags))
	cmd.AddCommand(newAccountsSubAccountsCmd(flags))
	cmd.AddCommand(newAccountsTabsCmd(flags))
	cmd.AddCommand(newAccountsTemporaryEnrollmentPairingsCmd(flags))
	cmd.AddCommand(newAccountsTermsCmd(flags))
	cmd.AddCommand(newAccountsTermsOfServiceCmd(flags))
	cmd.AddCommand(newAccountsUsersCmd(flags))
	cmd.AddCommand(newAccountsVisibleCalendarsCountCmd(flags))
	return cmd
}
