// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAuditGradeChangeApiQueryCmd(flags *rootFlags) *cobra.Command {
	var flagCourseId string
	var flagAssignmentId string
	var flagStudentId string
	var flagGraderId string
	var flagStartTime string
	var flagEndTime string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "grade-change-api-query",
		Aliases: []string{"list"},
		Short: "List grade change events satisfying all given parameters. Teachers may query for events in courses they teach....",
		Example: "  canvas-cli audit grade-change-api-query",
		Annotations: map[string]string{"pp:endpoint": "audit.grade-change-api-query", "pp:method": "GET", "pp:path": "/audit/grade_change", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/audit/grade_change"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "audit", path, map[string]string{
				"course_id": fmt.Sprintf("%v", flagCourseId),
				"assignment_id": fmt.Sprintf("%v", flagAssignmentId),
				"student_id": fmt.Sprintf("%v", flagStudentId),
				"grader_id": fmt.Sprintf("%v", flagGraderId),
				"start_time": fmt.Sprintf("%v", flagStartTime),
				"end_time": fmt.Sprintf("%v", flagEndTime),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCourseId, "course-id", "", "Restrict query to events in the specified course.")
	cmd.Flags().StringVar(&flagAssignmentId, "assignment-id", "", "Restrict query to the given assignment. If 'override' is given, query the course final grade override instead.")
	cmd.Flags().StringVar(&flagStudentId, "student-id", "", "User id of a student to search grading events for.")
	cmd.Flags().StringVar(&flagGraderId, "grader-id", "", "User id of a grader to search grading events for.")
	cmd.Flags().StringVar(&flagStartTime, "start-time", "", "The beginning of the time range from which you want events.")
	cmd.Flags().StringVar(&flagEndTime, "end-time", "", "The end of the time range from which you want events.")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
