// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCalendarEventsReservationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reservations",
		Short: "Manage reservations",
	}

	cmd.AddCommand(newCalendarEventsReservationsCalendarEventsApiReserveOtherCmd(flags))
	cmd.AddCommand(newCalendarEventsReservationsCalendarEventsApiReserveOther2Cmd(flags))
	return cmd
}
