// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCalendarEventsApiIndexCmd(flags *rootFlags) *cobra.Command {
	var flagType string
	var flagStartDate string
	var flagEndDate string
	var flagUndated bool
	var flagAllEvents bool
	var flagContextCodes string
	var flagExcludes string
	var flagIncludes string
	var flagImportantDates bool
	var flagBlackoutDate bool
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "api-index",
		Aliases: []string{"list"},
		Short: "Retrieve the paginated list of calendar events or assignments for the current user",
		Example: "  canvas-cli calendar-events api-index",
		Annotations: map[string]string{"pp:endpoint": "calendar-events.api-index", "pp:method": "GET", "pp:path": "/calendar_events", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("type") {
				allowedType := []string{ "event", "assignment", "sub_assignment" }
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "type", flagType, allowedType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/calendar_events"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "calendar-events", path, map[string]string{
				"type": fmt.Sprintf("%v", flagType),
				"start_date": fmt.Sprintf("%v", flagStartDate),
				"end_date": fmt.Sprintf("%v", flagEndDate),
				"undated": fmt.Sprintf("%v", flagUndated),
				"all_events": fmt.Sprintf("%v", flagAllEvents),
				"context_codes": fmt.Sprintf("%v", flagContextCodes),
				"excludes": fmt.Sprintf("%v", flagExcludes),
				"includes": fmt.Sprintf("%v", flagIncludes),
				"important_dates": fmt.Sprintf("%v", flagImportantDates),
				"blackout_date": fmt.Sprintf("%v", flagBlackoutDate),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "", "Defaults to 'event' (one of: event, assignment, sub_assignment)")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Only return events since the start_date (inclusive). Defaults to today. The value should be formatted as: yyyy-mm-dd...")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Only return events before the end_date (inclusive). Defaults to start_date. The value should be formatted as:...")
	cmd.Flags().BoolVar(&flagUndated, "undated", false, "Defaults to false (dated events only). If true, only return undated events and ignore start_date and end_date.")
	cmd.Flags().BoolVar(&flagAllEvents, "all-events", false, "Defaults to false (uses start_date, end_date, and undated criteria). If true, all events are returned, ignoring...")
	cmd.Flags().StringVar(&flagContextCodes, "context-codes", "", "[String] List of context codes of courses, groups, users, or accounts whose events you want to see. If not...")
	cmd.Flags().StringVar(&flagExcludes, "excludes", "", "[Array] Array of attributes to exclude. Possible values are 'description', 'child_events' and 'assignment'")
	cmd.Flags().StringVar(&flagIncludes, "includes", "", "[Array] Array of optional attributes to include. Possible values are 'web_conference' and 'series_natural_language'")
	cmd.Flags().BoolVar(&flagImportantDates, "important-dates", false, "Defaults to false. If true, only events with important dates set to true will be returned.")
	cmd.Flags().BoolVar(&flagBlackoutDate, "blackout-date", false, "Defaults to false. If true, only events with blackout date set to true will be returned.")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
