// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCanvasLmsSearchAllCoursesCmd(flags *rootFlags) *cobra.Command {
	var flagSearch string
	var flagPublicOnly bool
	var flagOpenEnrollmentOnly bool
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "all-courses",
		Aliases: []string{"list"},
		Short: "A paginated list of all courses visible in the public index",
		Example: "  canvas-cli canvas-lms-search all-courses",
		Annotations: map[string]string{"pp:endpoint": "canvas-lms-search.all-courses", "pp:method": "GET", "pp:path": "/search/all_courses", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/search/all_courses"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "canvas-lms-search", path, map[string]string{
				"search": fmt.Sprintf("%v", flagSearch),
				"public_only": fmt.Sprintf("%v", flagPublicOnly),
				"open_enrollment_only": fmt.Sprintf("%v", flagOpenEnrollmentOnly),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearch, "search", "", "Search terms used for matching users/courses/groups (e.g. 'bob smith'). If multiple terms are given (separated via...")
	cmd.Flags().BoolVar(&flagPublicOnly, "public-only", false, "Only return courses with public content. Defaults to false.")
	cmd.Flags().BoolVar(&flagOpenEnrollmentOnly, "open-enrollment-only", false, "Only return courses that allow self enrollment. Defaults to false.")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
