// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newConversationsAddMessageConversationsCmd(flags *rootFlags) *cobra.Command {
	var bodyAttachmentIds string
	var bodyBody string
	var bodyIncludedMessages string
	var bodyMediaCommentId string
	var bodyMediaCommentType string
	var bodyRecipients string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "conversations <id>",
		Aliases: []string{"create"},
		Short: "Add a message to an existing conversation. Response is similar to the GET/show action, except that only includes the...",
		Example: "  canvas-cli conversations add-message conversations 550e8400-e29b-41d4-a716-446655440000 --body example-value",
		Annotations: map[string]string{"pp:endpoint": "add-message.conversations", "pp:method": "POST", "pp:path": "/conversations/{id}/add_message"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("body") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "body")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/conversations/{id}/add_message"
			path = replacePathParam(path, "id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAttachmentIds != "" {
					var parsedAttachmentIds any
					if err := json.Unmarshal([]byte(bodyAttachmentIds), &parsedAttachmentIds); err != nil {
						return fmt.Errorf("parsing --attachment-ids JSON: %w", err)
					}
					body["attachment_ids"] = parsedAttachmentIds
				}
				if bodyBody != "" {
					body["body"] = bodyBody
				}
				if bodyIncludedMessages != "" {
					var parsedIncludedMessages any
					if err := json.Unmarshal([]byte(bodyIncludedMessages), &parsedIncludedMessages); err != nil {
						return fmt.Errorf("parsing --included-messages JSON: %w", err)
					}
					body["included_messages"] = parsedIncludedMessages
				}
				if bodyMediaCommentId != "" {
					body["media_comment_id"] = bodyMediaCommentId
				}
				if bodyMediaCommentType != "" {
					body["media_comment_type"] = bodyMediaCommentType
				}
				if bodyRecipients != "" {
					var parsedRecipients any
					if err := json.Unmarshal([]byte(bodyRecipients), &parsedRecipients); err != nil {
						return fmt.Errorf("parsing --recipients JSON: %w", err)
					}
					body["recipients"] = parsedRecipients
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "add-message",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAttachmentIds, "attachment-ids", "", "[String] An array of attachments ids. These must be files that have been previously uploaded to the sender's...")
	cmd.Flags().StringVar(&bodyBody, "body", "", "The message to be sent.")
	cmd.Flags().StringVar(&bodyIncludedMessages, "included-messages", "", "[String]")
	cmd.Flags().StringVar(&bodyMediaCommentId, "media-comment-id", "", "Media comment id of an audio of video file to be associated with this message.")
	cmd.Flags().StringVar(&bodyMediaCommentType, "media-comment-type", "", "Type of the associated media file.")
	cmd.Flags().StringVar(&bodyRecipients, "recipients", "", "[String]")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
