// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newConversationsIndexCmd(flags *rootFlags) *cobra.Command {
	var flagScope string
	var flagFilter string
	var flagFilterModeAndOr string
	var flagInterleaveSubmissions bool
	var flagIncludeAllConversationIds bool
	var flagInclude string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "index",
		Short: "Returns the paginated list of conversations for the current user, most recent ones first....",
		Example: "  canvas-pp-cli conversations index",
		Annotations: map[string]string{"pp:endpoint": "conversations.index", "pp:method": "GET", "pp:path": "/conversations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("scope") {
				allowedScope := []string{ "unread", "starred", "archived", "sent" }
				validScope := false
				for _, v := range allowedScope {
					if flagScope == v {
						validScope = true
						break
					}
				}
				if !validScope {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "scope", flagScope, allowedScope)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/conversations"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "conversations", path, map[string]string{
				"scope": fmt.Sprintf("%v", flagScope),
				"filter": fmt.Sprintf("%v", flagFilter),
				`filter_mode["and"|"or"]`: fmt.Sprintf("%v", flagFilterModeAndOr),
				"interleave_submissions": fmt.Sprintf("%v", flagInterleaveSubmissions),
				"include_all_conversation_ids": fmt.Sprintf("%v", flagIncludeAllConversationIds),
				"include": fmt.Sprintf("%v", flagInclude),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagScope, "scope", "", "When set, only return conversations of the specified type. For example, set to 'unread' to return only conversations... (one of: unread, starred, archived, sent)")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "[String, course_id|group_id|user_id] When set, only return conversations for the specified courses, groups or users....")
	cmd.Flags().StringVar(&flagFilterModeAndOr, "filter-mode-and-or", "", "When filter[] contains multiple filters, combine them with this mode, filtering conversations that at have at least...")
	cmd.Flags().BoolVar(&flagInterleaveSubmissions, "interleave-submissions", false, "(Obsolete) Submissions are no longer linked to conversations. This parameter is ignored.")
	cmd.Flags().BoolVar(&flagIncludeAllConversationIds, "include-all-conversation-ids", false, "Default is false. If true, the top-level element of the response will be an object rather than an array, and will...")
	cmd.Flags().StringVar(&flagInclude, "include", "", "[Optional, String, 'participant_avatars'|'uuid'] 'participant_avatars':: Optionally include an 'avatar_url' key for...")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
