// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesExternalToolsTimingMetaGenerateSessionlessLaunchForCoursesCmd(flags *rootFlags) *cobra.Command {
	var flagId string
	var flagUrl string
	var flagAssignmentId string
	var flagModuleItemId string
	var flagLaunchType string
	var flagResourceLinkLookupUuid string

	cmd := &cobra.Command{
		Use:   "timing-meta-generate-sessionless-launch-for-courses <course_id>",
		Aliases: []string{"get"},
		Short: "Returns a sessionless launch url for an external tool. Prefers the resource_link_lookup_uuid, but defaults to the...",
		Example: "  canvas-pp-cli courses external-tools timing-meta-generate-sessionless-launch-for-courses 550e8400-e29b-41d4-a716-446655440000 --assignment-id 550e8400-e29b-41d4-a716-446655440000 --module-item-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "external-tools.timing-meta-generate-sessionless-launch-for-courses", "pp:method": "GET", "pp:path": "/courses/{course_id}/external_tools/sessionless_launch", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("assignment-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "assignment-id")
			}
			if !cmd.Flags().Changed("module-item-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "module-item-id")
			}
			if cmd.Flags().Changed("launch-type") {
				allowedLaunchType := []string{ "assessment", "module_item" }
				validLaunchType := false
				for _, v := range allowedLaunchType {
					if flagLaunchType == v {
						validLaunchType = true
						break
					}
				}
				if !validLaunchType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "launch-type", flagLaunchType, allowedLaunchType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/external_tools/sessionless_launch"
			path = replacePathParam(path, "course_id", args[0])
			params := map[string]string{}
			if flagId != "" {
				params["id"] = fmt.Sprintf("%v", flagId)
			}
			if flagUrl != "" {
				params["url"] = fmt.Sprintf("%v", flagUrl)
			}
			if flagAssignmentId != "" {
				params["assignment_id"] = fmt.Sprintf("%v", flagAssignmentId)
			}
			if flagModuleItemId != "" {
				params["module_item_id"] = fmt.Sprintf("%v", flagModuleItemId)
			}
			if flagLaunchType != "" {
				params["launch_type"] = fmt.Sprintf("%v", flagLaunchType)
			}
			if flagResourceLinkLookupUuid != "" {
				params["resource_link_lookup_uuid"] = fmt.Sprintf("%v", flagResourceLinkLookupUuid)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "external-tools", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagId, "id", "", "The external id of the tool to launch.")
	cmd.Flags().StringVar(&flagUrl, "url", "", "The LTI launch url for the external tool.")
	cmd.Flags().StringVar(&flagAssignmentId, "assignment-id", "", "The assignment id for an assignment launch. Required if launch_type is set to 'assessment'.")
	cmd.Flags().StringVar(&flagModuleItemId, "module-item-id", "", "The assignment id for a module item launch. Required if launch_type is set to 'module_item'.")
	cmd.Flags().StringVar(&flagLaunchType, "launch-type", "", "The type of launch to perform on the external tool. Placement names (eg. 'course_navigation') can also be specified... (one of: assessment, module_item)")
	cmd.Flags().StringVar(&flagResourceLinkLookupUuid, "resource-link-lookup-uuid", "", "The identifier to lookup a resource link.")

	return cmd
}
