// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesGradebookHistoryApiSubmissionsCmd(flags *rootFlags) *cobra.Command {
	var flagDate string

	cmd := &cobra.Command{
		Use:   "api-submissions <assignment_id> <course_id> <grader_id>",
		Short: "Gives a nested list of submission versions",
		Example: "  canvas-cli courses gradebook-history api-submissions 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --date 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "gradebook-history.api-submissions", "pp:method": "GET", "pp:path": "/courses/{course_id}/gradebook_history/{date}/graders/{grader_id}/assignments/{assignment_id}/submissions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "date")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/gradebook_history/{date}/graders/{grader_id}/assignments/{assignment_id}/submissions"
			path = replacePathParam(path, "assignment_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[1])
			if len(args) < 4 {
				return usageErr(fmt.Errorf("grader_id is required\nUsage: %s <%s>", cmd.CommandPath(), "grader_id"))
			}
			path = replacePathParam(path, "grader_id", args[3])
			path = replacePathParam(path, "date", fmt.Sprintf("%v", flagDate))
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "gradebook-history", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDate, "date", "", "The date for which you would like to see submissions")

	return cmd
}
