// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesAssignmentGroupsApiCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyGroupWeight float64
	var bodyIntegrationData string
	var bodyName string
	var bodyPosition int
	var bodySisSourceId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "api-create <course_id>",
		Aliases: []string{"create"},
		Short: "Create a new assignment group for this course.",
		Example: "  canvas-pp-cli courses assignment-groups api-create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assignment-groups.api-create", "pp:method": "POST", "pp:path": "/courses/{course_id}/assignment_groups"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/assignment_groups"
			path = replacePathParam(path, "course_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyGroupWeight != 0.0 {
					body["group_weight"] = bodyGroupWeight
				}
				if bodyIntegrationData != "" {
					body["integration_data"] = bodyIntegrationData
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPosition != 0 {
					body["position"] = bodyPosition
				}
				if bodySisSourceId != "" {
					body["sis_source_id"] = bodySisSourceId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "assignment-groups",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyGroupWeight, "group-weight", 0.0, "The percent of the total grade that this assignment group represents")
	cmd.Flags().StringVar(&bodyIntegrationData, "integration-data", "", "The integration data of the Assignment Group")
	cmd.Flags().StringVar(&bodyName, "name", "", "The assignment group's name")
	cmd.Flags().IntVar(&bodyPosition, "position", 0, "The position of this assignment group in relation to the other assignment groups")
	cmd.Flags().StringVar(&bodySisSourceId, "sis-source-id", "", "The sis source id of the Assignment Group")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
