// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesFeaturesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "features",
		Short: "Manage features",
	}

	cmd.AddCommand(newCoursesFeaturesFlagsDeleteForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFeaturesFlagsEnabledForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFeaturesFlagsIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFeaturesFlagsShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFeaturesFlagsUpdateForCoursesCmd(flags))
	return cmd
}
