// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesGradingPeriodsBatchUpdateForCoursesCmd(flags *rootFlags) *cobra.Command {
	var bodyGradingPeriodsCloseDate string
	var bodyGradingPeriodsEndDate string
	var bodyGradingPeriodsId string
	var bodyGradingPeriodsStartDate string
	var bodyGradingPeriodsTitle string
	var bodyGradingPeriodsWeight string
	var bodySetId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "batch-update-for-courses <course_id>",
		Short: "Update multiple grading periods",
		Example: "  canvas-pp-cli courses grading-periods batch-update-for-courses 550e8400-e29b-41d4-a716-446655440000 --grading-periods-close-date 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "grading-periods.batch-update-for-courses", "pp:method": "PATCH", "pp:path": "/courses/{course_id}/grading_periods/batch_update"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("grading-periods-close-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "grading-periods-close-date")
				}
				if !cmd.Flags().Changed("grading-periods-end-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "grading-periods-end-date")
				}
				if !cmd.Flags().Changed("grading-periods-start-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "grading-periods-start-date")
				}
				if !cmd.Flags().Changed("grading-periods-title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "grading-periods-title")
				}
				if !cmd.Flags().Changed("set-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "set-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/grading_periods/batch_update"
			path = replacePathParam(path, "course_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyGradingPeriodsCloseDate != "" {
					var parsedGradingPeriodsCloseDate any
					if err := json.Unmarshal([]byte(bodyGradingPeriodsCloseDate), &parsedGradingPeriodsCloseDate); err != nil {
						return fmt.Errorf("parsing --grading-periods-close-date JSON: %w", err)
					}
					body["grading_periods[][close_date]"] = bodyGradingPeriodsCloseDate
				}
				if bodyGradingPeriodsEndDate != "" {
					var parsedGradingPeriodsEndDate any
					if err := json.Unmarshal([]byte(bodyGradingPeriodsEndDate), &parsedGradingPeriodsEndDate); err != nil {
						return fmt.Errorf("parsing --grading-periods-end-date JSON: %w", err)
					}
					body["grading_periods[][end_date]"] = bodyGradingPeriodsEndDate
				}
				if bodyGradingPeriodsId != "" {
					var parsedGradingPeriodsId any
					if err := json.Unmarshal([]byte(bodyGradingPeriodsId), &parsedGradingPeriodsId); err != nil {
						return fmt.Errorf("parsing --grading-periods-id JSON: %w", err)
					}
					body["grading_periods[][id]"] = bodyGradingPeriodsId
				}
				if bodyGradingPeriodsStartDate != "" {
					var parsedGradingPeriodsStartDate any
					if err := json.Unmarshal([]byte(bodyGradingPeriodsStartDate), &parsedGradingPeriodsStartDate); err != nil {
						return fmt.Errorf("parsing --grading-periods-start-date JSON: %w", err)
					}
					body["grading_periods[][start_date]"] = bodyGradingPeriodsStartDate
				}
				if bodyGradingPeriodsTitle != "" {
					var parsedGradingPeriodsTitle any
					if err := json.Unmarshal([]byte(bodyGradingPeriodsTitle), &parsedGradingPeriodsTitle); err != nil {
						return fmt.Errorf("parsing --grading-periods-title JSON: %w", err)
					}
					body["grading_periods[][title]"] = bodyGradingPeriodsTitle
				}
				if bodyGradingPeriodsWeight != "" {
					var parsedGradingPeriodsWeight any
					if err := json.Unmarshal([]byte(bodyGradingPeriodsWeight), &parsedGradingPeriodsWeight); err != nil {
						return fmt.Errorf("parsing --grading-periods-weight JSON: %w", err)
					}
					body["grading_periods[][weight]"] = bodyGradingPeriodsWeight
				}
				if bodySetId != "" {
					body["set_id"] = bodySetId
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "grading-periods",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyGradingPeriodsCloseDate, "grading-periods-close-date", "", "[Required, Date] The date after which grades can no longer be changed for a grading period. The close_date is...")
	cmd.Flags().StringVar(&bodyGradingPeriodsEndDate, "grading-periods-end-date", "", "[Required, Date] The date the grading period ends. The end_date is required for creating a new grading period, but...")
	cmd.Flags().StringVar(&bodyGradingPeriodsId, "grading-periods-id", "", "[String] The id of the grading period. If the id parameter does not exist, a new grading period will be created.")
	cmd.Flags().StringVar(&bodyGradingPeriodsStartDate, "grading-periods-start-date", "", "[Required, Date] The date the grading period starts. The start_date is required for creating a new grading period,...")
	cmd.Flags().StringVar(&bodyGradingPeriodsTitle, "grading-periods-title", "", "[Required, String] The title of the grading period. The title is required for creating a new grading period, but not...")
	cmd.Flags().StringVar(&bodyGradingPeriodsWeight, "grading-periods-weight", "", "[Float] A weight value that contributes to the overall weight of a grading period set which is used to calculate how...")
	cmd.Flags().StringVar(&bodySetId, "set-id", "", "The id of the grading period set.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
