// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesModulesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "modules",
		Short: "Manage modules",
	}

	cmd.AddCommand(newCoursesModulesAssignmentOverridesBulkUpdateCmd(flags))
	cmd.AddCommand(newCoursesModulesAssignmentOverridesIndexCmd(flags))
	cmd.AddCommand(newCoursesModulesContextApiCreateCmd(flags))
	cmd.AddCommand(newCoursesModulesContextApiDestroyCmd(flags))
	cmd.AddCommand(newCoursesModulesContextApiIndexCmd(flags))
	cmd.AddCommand(newCoursesModulesContextApiRelockCmd(flags))
	cmd.AddCommand(newCoursesModulesContextApiShowCmd(flags))
	cmd.AddCommand(newCoursesModulesContextApiUpdateCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiCreateCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiDestroyCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiIndexCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiMarkAsDoneCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiMarkItemReadCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiSelectMasteryPathCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiShowCmd(flags))
	cmd.AddCommand(newCoursesModulesContextItemsApiUpdateCmd(flags))
	cmd.AddCommand(newCoursesModulesLearningObjectDatesShowForCoursesCmd(flags))
	return cmd
}
