// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesOutcomeGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "outcome-groups",
		Short: "Copyright (C) 2011 - present Instructure, Inc. This file is part of Canvas. Canvas is free software: you can...",
	}

	cmd.AddCommand(newCoursesOutcomeGroupsApiCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiDestroyForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiImportForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiLinkForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiLinkForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiOutcomesForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiSubgroupsForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiUnlinkForCoursesCmd(flags))
	cmd.AddCommand(newCoursesOutcomeGroupsApiUpdateForCoursesCmd(flags))
	return cmd
}
