// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesApplyScoreToUngradedSubmissionsGradebooksCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignmentIds string
	var bodyExcused bool
	var bodyMarkAsMissing bool
	var bodyOnlyPastDue bool
	var bodyPercent float64
	var bodyStudentIds string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "gradebooks <course_id>",
		Aliases: []string{"update"},
		Short: "Perform a bulk scoring of ungraded submissions for a course, or mark ungraded submissions as excused. The course's...",
		Example: "  canvas-cli courses apply-score-to-ungraded-submissions gradebooks 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "apply-score-to-ungraded-submissions.gradebooks", "pp:method": "PUT", "pp:path": "/courses/{course_id}/apply_score_to_ungraded_submissions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("assignment-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "assignment-ids")
				}
				if !cmd.Flags().Changed("student-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "student-ids")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/apply_score_to_ungraded_submissions"
			path = replacePathParam(path, "course_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignmentIds != "" {
					var parsedAssignmentIds any
					if err := json.Unmarshal([]byte(bodyAssignmentIds), &parsedAssignmentIds); err != nil {
						return fmt.Errorf("parsing --assignment-ids JSON: %w", err)
					}
					body["assignment_ids"] = parsedAssignmentIds
				}
				if bodyExcused != false {
					body["excused"] = bodyExcused
				}
				if bodyMarkAsMissing != false {
					body["mark_as_missing"] = bodyMarkAsMissing
				}
				if bodyOnlyPastDue != false {
					body["only_past_due"] = bodyOnlyPastDue
				}
				if bodyPercent != 0.0 {
					body["percent"] = bodyPercent
				}
				if bodyStudentIds != "" {
					var parsedStudentIds any
					if err := json.Unmarshal([]byte(bodyStudentIds), &parsedStudentIds); err != nil {
						return fmt.Errorf("parsing --student-ids JSON: %w", err)
					}
					body["student_ids"] = parsedStudentIds
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "apply-score-to-ungraded-submissions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAssignmentIds, "assignment-ids", "", "An array of assignment ids to apply score to ungraded submissions.")
	cmd.Flags().BoolVar(&bodyExcused, "excused", false, "If true, mark ungraded submissions as excused. Exactly one of this parameter (with a true value) or the 'percent'...")
	cmd.Flags().BoolVar(&bodyMarkAsMissing, "mark-as-missing", false, "If true, mark all affected submissions as missing in addition to issuing a grade.")
	cmd.Flags().BoolVar(&bodyOnlyPastDue, "only-past-due", false, "If true, only operate on submissions whose due date has passed.")
	cmd.Flags().Float64Var(&bodyPercent, "percent", 0.0, "A percentage value between 0 and 100 representing the percent score to apply. Exactly one of this parameter or the...")
	cmd.Flags().StringVar(&bodyStudentIds, "student-ids", "", "An array of student ids to apply score to ungraded submissions.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
