// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "files",
		Short: "Manage files",
	}

	cmd.AddCommand(newCoursesFilesCoursesCreateCmd(flags))
	cmd.AddCommand(newCoursesFilesLearningObjectDatesShowForCourses6Cmd(flags))
	cmd.AddCommand(newCoursesFilesLearningObjectDatesUpdateForCourses5Cmd(flags))
	cmd.AddCommand(newCoursesFilesMetadataSaxDocApiIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFilesMetadataSaxDocApiQuotaForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFilesMetadataSaxDocApiShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFilesMetadataSaxDocRefCmd(flags))
	return cmd
}
