// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesRecentStudentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "recent-students",
		Short: "Manage recent students",
	}

	cmd.AddCommand(newCoursesRecentStudentsCoursesCmd(flags))
	return cmd
}
