// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesContentShareUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-share-users",
		Short: "Manage content share users",
	}

	cmd.AddCommand(newCoursesContentShareUsersCoursesCmd(flags))
	return cmd
}
