// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesOutcomeMasteryDistributionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "outcome-mastery-distribution",
		Short: "Manage outcome mastery distribution",
	}

	cmd.AddCommand(newCoursesOutcomeMasteryDistributionOutcomeResultsMasteryDistributionCmd(flags))
	return cmd
}
