// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesFrontPageCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "front-page",
		Short: "Manage front page",
	}

	cmd.AddCommand(newCoursesFrontPageWikiPagesApiShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFrontPageWikiPagesApiUpdateForCoursesCmd(flags))
	return cmd
}
