// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesTabsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tabs",
		Short: "Manage tabs",
	}

	cmd.AddCommand(newCoursesTabsIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesTabsUpdateCmd(flags))
	return cmd
}
