// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesRubricAssociationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "rubric-associations",
		Short: "Manage rubric associations",
	}

	cmd.AddCommand(newCoursesRubricAssociationsCreateCmd(flags))
	cmd.AddCommand(newCoursesRubricAssociationsDestroyCmd(flags))
	cmd.AddCommand(newCoursesRubricAssociationsRubricAssessmentsCreateCmd(flags))
	cmd.AddCommand(newCoursesRubricAssociationsRubricAssessmentsDestroyCmd(flags))
	cmd.AddCommand(newCoursesRubricAssociationsRubricAssessmentsUpdateCmd(flags))
	cmd.AddCommand(newCoursesRubricAssociationsUpdateCmd(flags))
	return cmd
}
