// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesGroupCategoriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "group-categories",
		Short: "Group Categories allow grouping of groups together in canvas. There are a few different built-in group categories...",
	}

	cmd.AddCommand(newCoursesGroupCategoriesBulkManageDifferentiationTagCmd(flags))
	cmd.AddCommand(newCoursesGroupCategoriesCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesGroupCategoriesExportTagsCmd(flags))
	cmd.AddCommand(newCoursesGroupCategoriesImportTagsCmd(flags))
	cmd.AddCommand(newCoursesGroupCategoriesIndexForCoursesCmd(flags))
	return cmd
}
