// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesDiscussionTopicsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "discussion-topics",
		Short: "API for accessing and participating in discussion topics in groups and courses.",
	}

	cmd.AddCommand(newCoursesDiscussionTopicsApiAddEntryForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiAddReplyForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiDisableSummaryForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiDuplicateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiEntriesForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiEntryListForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiFindOrCreateSummaryForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiFindSummaryForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkAllReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkAllTopicReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkAllUnreadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkEntryReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkEntryUnreadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkTopicReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiMarkTopicUnreadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiRateEntryForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiRepliesForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiSubscribeTopicForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiSummaryFeedbackForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiUnsubscribeTopicForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsApiViewForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsDestroyForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsDiscussionEntriesDestroyForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsDiscussionEntriesUpdateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsLearningObjectDatesShowForCourses4Cmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsLearningObjectDatesUpdateForCourses3Cmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsReorderForCoursesCmd(flags))
	cmd.AddCommand(newCoursesDiscussionTopicsUpdateForCoursesCmd(flags))
	return cmd
}
