// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesUsageRightsSetForCoursesCmd(flags *rootFlags) *cobra.Command {
	var bodyFileIds string
	var bodyFolderIds string
	var bodyPublish bool
	var bodyUsageRights string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "set-for-courses <course_id>",
		Aliases: []string{"update"},
		Short: "Sets copyright and license information for one or more files",
		Example: "  canvas-pp-cli courses usage-rights set-for-courses 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "usage-rights.set-for-courses", "pp:method": "PUT", "pp:path": "/courses/{course_id}/usage_rights"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("file-ids") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "file-ids")
				}
				if !cmd.Flags().Changed("usage-rights") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "usage-rights")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/usage_rights"
			path = replacePathParam(path, "course_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyFileIds != "" {
					var parsedFileIds any
					if err := json.Unmarshal([]byte(bodyFileIds), &parsedFileIds); err != nil {
						return fmt.Errorf("parsing --file-ids JSON: %w", err)
					}
					body["file_ids"] = parsedFileIds
				}
				if bodyFolderIds != "" {
					var parsedFolderIds any
					if err := json.Unmarshal([]byte(bodyFolderIds), &parsedFolderIds); err != nil {
						return fmt.Errorf("parsing --folder-ids JSON: %w", err)
					}
					body["folder_ids"] = parsedFolderIds
				}
				if bodyPublish != false {
					body["publish"] = bodyPublish
				}
				if bodyUsageRights != "" {
					var parsedUsageRights any
					if err := json.Unmarshal([]byte(bodyUsageRights), &parsedUsageRights); err != nil {
						return fmt.Errorf("parsing --usage-rights JSON: %w", err)
					}
					body["usage_rights"] = parsedUsageRights
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "usage-rights",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyFileIds, "file-ids", "", "[Required] List of ids of files to set usage rights for.")
	cmd.Flags().StringVar(&bodyFolderIds, "folder-ids", "", "[Optional] List of ids of folders to search for files to set usage rights for. Note that new files uploaded to these...")
	cmd.Flags().BoolVar(&bodyPublish, "publish", false, "Whether the file(s) or folder(s) should be published on save, provided that usage rights have been specified (set to...")
	cmd.Flags().StringVar(&bodyUsageRights, "usage-rights", "", "Usage rights")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
