// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesDiscussionTopicsLearningObjectDatesUpdateForCourses3Cmd(flags *rootFlags) *cobra.Command {
	var bodyAssignmentOverrides string
	var bodyDueAt string
	var bodyLockAt string
	var bodyOnlyVisibleToOverrides bool
	var bodyPeerReview string
	var bodyUnlockAt string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "learning-object-dates-update-for-courses-3 <discussion_topic_id> <course_id>",
		Short: "Updates date-related information for learning objects, including due date, availability dates, override status, and...",
		Example: "  canvas-pp-cli courses discussion-topics learning-object-dates-update-for-courses-3 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "discussion-topics.learning-object-dates-update-for-courses-3", "pp:method": "PUT", "pp:path": "/courses/{course_id}/discussion_topics/{discussion_topic_id}/date_details"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/discussion_topics/{discussion_topic_id}/date_details"
			path = replacePathParam(path, "discussion_topic_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignmentOverrides != "" {
					var parsedAssignmentOverrides any
					if err := json.Unmarshal([]byte(bodyAssignmentOverrides), &parsedAssignmentOverrides); err != nil {
						return fmt.Errorf("parsing --assignment-overrides JSON: %w", err)
					}
					body["assignment_overrides"] = parsedAssignmentOverrides
				}
				if bodyDueAt != "" {
					body["due_at"] = bodyDueAt
				}
				if bodyLockAt != "" {
					body["lock_at"] = bodyLockAt
				}
				if bodyOnlyVisibleToOverrides != false {
					body["only_visible_to_overrides"] = bodyOnlyVisibleToOverrides
				}
				if bodyPeerReview != "" {
					var parsedPeerReview any
					if err := json.Unmarshal([]byte(bodyPeerReview), &parsedPeerReview); err != nil {
						return fmt.Errorf("parsing --peer-review JSON: %w", err)
					}
					body["peer_review"] = parsedPeerReview
				}
				if bodyUnlockAt != "" {
					body["unlock_at"] = bodyUnlockAt
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "discussion-topics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAssignmentOverrides, "assignment-overrides", "", "[Array] List of overrides to apply to the learning object. Overrides that already exist should include an ID and...")
	cmd.Flags().StringVar(&bodyDueAt, "due-at", "", "The learning object's due date. Not applicable for ungraded discussions, pages, and files.")
	cmd.Flags().StringVar(&bodyLockAt, "lock-at", "", "The learning object's lock date. Must be after the due date if there is one.")
	cmd.Flags().BoolVar(&bodyOnlyVisibleToOverrides, "only-visible-to-overrides", false, "Whether the learning object is only assigned to students who are targeted by an override.")
	cmd.Flags().StringVar(&bodyPeerReview, "peer-review", "", "Peer review")
	cmd.Flags().StringVar(&bodyUnlockAt, "unlock-at", "", "The learning object's unlock date. Must be before the due date if there is one.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
