// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesAssignmentsExtensionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignmentExtensionsExtraAttempts string
	var bodyAssignmentExtensionsUserId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "extensions-create <assignment_id> <course_id>",
		Short: "<b>Responses</b> * <b>200 OK</b> if the request was successful * <b>403 Forbidden</b> if you are not allowed to...",
		Example: "  canvas-cli courses assignments extensions-create 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --assignment-extensions-extra-attempts example-value",
		Annotations: map[string]string{"pp:endpoint": "assignments.extensions-create", "pp:method": "POST", "pp:path": "/courses/{course_id}/assignments/{assignment_id}/extensions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("assignment-extensions-extra-attempts") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "assignment-extensions-extra-attempts")
				}
				if !cmd.Flags().Changed("assignment-extensions-user-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "assignment-extensions-user-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/assignments/{assignment_id}/extensions"
			path = replacePathParam(path, "assignment_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignmentExtensionsExtraAttempts != "" {
					var parsedAssignmentExtensionsExtraAttempts any
					if err := json.Unmarshal([]byte(bodyAssignmentExtensionsExtraAttempts), &parsedAssignmentExtensionsExtraAttempts); err != nil {
						return fmt.Errorf("parsing --assignment-extensions-extra-attempts JSON: %w", err)
					}
					body["assignment_extensions[][extra_attempts]"] = bodyAssignmentExtensionsExtraAttempts
				}
				if bodyAssignmentExtensionsUserId != "" {
					var parsedAssignmentExtensionsUserId any
					if err := json.Unmarshal([]byte(bodyAssignmentExtensionsUserId), &parsedAssignmentExtensionsUserId); err != nil {
						return fmt.Errorf("parsing --assignment-extensions-user-id JSON: %w", err)
					}
					body["assignment_extensions[][user_id]"] = bodyAssignmentExtensionsUserId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "assignments",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAssignmentExtensionsExtraAttempts, "assignment-extensions-extra-attempts", "", "[Required, Integer] Number of times the student is allowed to re-take the assignment over the limit.")
	cmd.Flags().StringVar(&bodyAssignmentExtensionsUserId, "assignment-extensions-user-id", "", "[Required, Integer] The ID of the user we want to add assignment extensions for.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
