// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesContentMigrationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-migrations",
		Short: "API for accessing content migrations and migration issues",
	}

	cmd.AddCommand(newCoursesContentMigrationsAssetIdMappingCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsAvailableMigratorsForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsContentListForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsMigrationIssuesIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsMigrationIssuesShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsMigrationIssuesUpdateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesContentMigrationsUpdateForCoursesCmd(flags))
	return cmd
}
