// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesFoldersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "folders",
		Short: "Manage folders",
	}

	cmd.AddCommand(newCoursesFoldersCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFoldersListAllForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFoldersMediaForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFoldersResolvePathForCoursesCmd(flags))
	cmd.AddCommand(newCoursesFoldersResolvePathForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesFoldersShowForCoursesCmd(flags))
	return cmd
}
