// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesRubricsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyId int
	var bodyRubric string
	var bodyRubricAssociation string
	var bodyRubricAssociationId int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create <course_id>",
		Short: "Returns the rubric with the given id. Unfortunately this endpoint does not return a standard Rubric object, instead...",
		Example: "  canvas-cli courses rubrics create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "rubrics.create", "pp:method": "POST", "pp:path": "/courses/{course_id}/rubrics"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/rubrics"
			path = replacePathParam(path, "course_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyId != 0 {
					body["id"] = bodyId
				}
				if bodyRubric != "" {
					var parsedRubric any
					if err := json.Unmarshal([]byte(bodyRubric), &parsedRubric); err != nil {
						return fmt.Errorf("parsing --rubric JSON: %w", err)
					}
					body["rubric"] = parsedRubric
				}
				if bodyRubricAssociation != "" {
					var parsedRubricAssociation any
					if err := json.Unmarshal([]byte(bodyRubricAssociation), &parsedRubricAssociation); err != nil {
						return fmt.Errorf("parsing --rubric-association JSON: %w", err)
					}
					body["rubric_association"] = parsedRubricAssociation
				}
				if bodyRubricAssociationId != 0 {
					body["rubric_association_id"] = bodyRubricAssociationId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "rubrics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyId, "id", 0, "The id of the rubric")
	cmd.Flags().StringVar(&bodyRubric, "rubric", "", "Rubric")
	cmd.Flags().StringVar(&bodyRubricAssociation, "rubric-association", "", "Rubric association")
	cmd.Flags().IntVar(&bodyRubricAssociationId, "rubric-association-id", 0, "The id of the rubric association object (not the course/assignment itself, but the join table record id). It can be...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
