// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesAssignmentGroupsIndexCmd(flags *rootFlags) *cobra.Command {
	var flagInclude string
	var flagAssignmentIds string
	var flagExcludeAssignmentSubmissionTypes string
	var flagOverrideAssignmentDates bool
	var flagGradingPeriodId string
	var flagScopeAssignmentsToStudent bool
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "index <course_id>",
		Short: "Returns the paginated list of assignment groups for the current context. The returned groups are sorted by their...",
		Example: "  canvas-cli courses assignment-groups index 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assignment-groups.index", "pp:method": "GET", "pp:path": "/courses/{course_id}/assignment_groups", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/assignment_groups"
			path = replacePathParam(path, "course_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "assignment-groups", path, map[string]string{
				"include": fmt.Sprintf("%v", flagInclude),
				"assignment_ids": fmt.Sprintf("%v", flagAssignmentIds),
				"exclude_assignment_submission_types": fmt.Sprintf("%v", flagExcludeAssignmentSubmissionTypes),
				"override_assignment_dates": fmt.Sprintf("%v", flagOverrideAssignmentDates),
				"grading_period_id": fmt.Sprintf("%v", flagGradingPeriodId),
				"scope_assignments_to_student": fmt.Sprintf("%v", flagScopeAssignmentsToStudent),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'assignments'|'discussion_topic'|'all_dates'|'assignment_visibility'|'overrides'|'submission'|'observed_user...")
	cmd.Flags().StringVar(&flagAssignmentIds, "assignment-ids", "", "[String] If 'assignments' are included, optionally return only assignments having their ID in this array. This...")
	cmd.Flags().StringVar(&flagExcludeAssignmentSubmissionTypes, "exclude-assignment-submission-types", "", "[String, 'online_quiz'|'discussion_topic'|'wiki_page'|'external_tool'] If 'assignments' are included, those with the...")
	cmd.Flags().BoolVar(&flagOverrideAssignmentDates, "override-assignment-dates", false, "Apply assignment overrides for each assignment, defaults to true.")
	cmd.Flags().StringVar(&flagGradingPeriodId, "grading-period-id", "", "The id of the grading period in which assignment groups are being requested (Requires grading periods to exist.)")
	cmd.Flags().BoolVar(&flagScopeAssignmentsToStudent, "scope-assignments-to-student", false, "If true, all assignments returned will apply to the current user in the specified grading period. If assignments...")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
