// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesGradebookHistoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gradebook-history",
		Short: "Manage gradebook history",
	}

	cmd.AddCommand(newCoursesGradebookHistoryApiDayDetailsCmd(flags))
	cmd.AddCommand(newCoursesGradebookHistoryApiDaysCmd(flags))
	cmd.AddCommand(newCoursesGradebookHistoryApiFeedCmd(flags))
	cmd.AddCommand(newCoursesGradebookHistoryApiSubmissionsCmd(flags))
	return cmd
}
