// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesCspSettingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "csp-settings",
		Short: "API for enabling/disabling the use of Content Security Policy headers and configuring allowed domains",
	}

	cmd.AddCommand(newCoursesCspSettingsGetForCoursesCmd(flags))
	cmd.AddCommand(newCoursesCspSettingsSetForCoursesCmd(flags))
	return cmd
}
