// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesExternalFeedsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "external-feeds",
		Short: "External feeds represent RSS feeds that can be attached to a Course or Group, in order to automatically create...",
	}

	cmd.AddCommand(newCoursesExternalFeedsCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesExternalFeedsDestroyForCoursesCmd(flags))
	cmd.AddCommand(newCoursesExternalFeedsIndexForCoursesCmd(flags))
	return cmd
}
