// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesContentExportsApiCreateForCoursesCmd(flags *rootFlags) *cobra.Command {
	var bodyExportType string
	var bodySelect string
	var bodySkipNotifications bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "api-create-for-courses <course_id>",
		Aliases: []string{"create"},
		Short: "Begin a content export job for a course, group, or user. You can use the {api:ProgressController#show Progress API}...",
		Example: "  canvas-cli courses content-exports api-create-for-courses 550e8400-e29b-41d4-a716-446655440000 --export-type example-value",
		Annotations: map[string]string{"pp:endpoint": "content-exports.api-create-for-courses", "pp:method": "POST", "pp:path": "/courses/{course_id}/content_exports"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("export-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "export-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/content_exports"
			path = replacePathParam(path, "course_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyExportType != "" {
					body["export_type"] = bodyExportType
				}
				if bodySelect != "" {
					body["select"] = bodySelect
				}
				if bodySkipNotifications != false {
					body["skip_notifications"] = bodySkipNotifications
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "content-exports",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyExportType, "export-type", "", "'common_cartridge':: Export the contents of the course in the Common Cartridge (.imscc) format 'qti':: Export...")
	cmd.Flags().StringVar(&bodySelect, "select", "", "The select parameter allows exporting specific data. The keys are object types like 'files', 'folders', 'pages',...")
	cmd.Flags().BoolVar(&bodySkipNotifications, "skip-notifications", false, "Don't send the notifications about the export to the user. Default: false")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
