// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesAssignmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "assignments",
		Short: "Manage assignments",
	}

	cmd.AddCommand(newCoursesAssignmentsAnonymousProvisionalGradesStatusCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiBulkUpdateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiCheckAllocationConversionCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiCreateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiDuplicateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiShowCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiStudentGroupMembersCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsApiUpdateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsDestroyCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsExtensionsCreateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsLearningObjectDatesShowForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesAssignmentsLearningObjectDatesUpdateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsModerationSetCreateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsModerationSetIndexCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesBatchCreateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesBatchRetrieveCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesBatchUpdateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesCreateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesDestroyCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesIndexCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesShowCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsOverridesUpdateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsPeerReviewsApiAllocateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsPeerReviewsApiCreateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsPeerReviewsApiDestroyForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsPeerReviewsApiIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsPeerReviewsApiIndexForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesAssignmentsProvisionalGradesBulkSelectCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsProvisionalGradesPublishCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsProvisionalGradesSelectCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsProvisionalGradesStatusCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSisApiSisForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionCommentsApiCreateFileCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionCommentsApiDestroyCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionCommentsApiUpdateCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiBulkUpdateForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiCreateFileForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiDocumentAnnotationsReadStateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiGradeableStudentsCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiIndexForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMarkDocumentAnnotationsReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMarkRubricAssessmentsReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMarkRubricAssessmentsReadForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMarkSubmissionItemReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMarkSubmissionReadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMarkSubmissionUnreadForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiMultipleGradeableStudentsCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiRubricAssessmentsReadStateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiRubricAssessmentsReadStateForCourses2Cmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiShowAnonymousForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiShowForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiSubmissionSummaryForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiUpdateAnonymousForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsApiUpdateForCoursesCmd(flags))
	cmd.AddCommand(newCoursesAssignmentsSubmissionsCreateForCoursesCmd(flags))
	return cmd
}
