// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesAssignmentsSubmissionsApiGradeableStudentsCmd(flags *rootFlags) *cobra.Command {
	var flagSort string
	var flagOrder string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "submissions-api-gradeable-students <assignment_id> <course_id>",
		Short: "A paginated list of gradeable students for the assignment. The caller must have permission to view grades. If...",
		Example: "  canvas-cli courses assignments submissions-api-gradeable-students 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assignments.submissions-api-gradeable-students", "pp:method": "GET", "pp:path": "/courses/{course_id}/assignments/{assignment_id}/gradeable_students", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{ "name" }
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{ "asc", "desc" }
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/courses/{course_id}/assignments/{assignment_id}/gradeable_students"
			path = replacePathParam(path, "assignment_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[1])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "assignments", path, map[string]string{
				"sort": fmt.Sprintf("%v", flagSort),
				"order": fmt.Sprintf("%v", flagOrder),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort results by this field. (one of: name)")
	cmd.Flags().StringVar(&flagOrder, "order", "", "The sorting order. Defaults to 'asc'. (one of: asc, desc)")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
