// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "files",
		Short: "Manage files",
	}

	cmd.AddCommand(newFilesMetadataSaxDocApiShowOtherCmd(flags))
	cmd.AddCommand(newFilesMetadataSaxDocApiUpdateCmd(flags))
	cmd.AddCommand(newFilesMetadataSaxDocDestroyCmd(flags))
	cmd.AddCommand(newFilesIconMetadataCmd(flags))
	cmd.AddCommand(newFilesPublicUrlCmd(flags))
	cmd.AddCommand(newFilesResetVerifierCmd(flags))
	return cmd
}
