// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGlobalCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "global",
		Short: "Manage global",
	}

	cmd.AddCommand(newGlobalOutcomeGroupsApiCreateOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiDestroyOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiImportOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiLinkOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiLinkOther2Cmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiOutcomesOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiRedirectOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiShowOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiSubgroupsOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiUnlinkOtherCmd(flags))
	cmd.AddCommand(newGlobalOutcomeGroupsApiUpdateOtherCmd(flags))
	return cmd
}
