// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsDiscussionTopicsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "discussion-topics",
		Short: "API for accessing and participating in discussion topics in groups and courses.",
	}

	cmd.AddCommand(newGroupsDiscussionTopicsApiAddEntryForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiAddReplyForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiDisableSummaryForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiDuplicateForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiEntriesForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiEntryListForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiFindOrCreateSummaryForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiFindSummaryForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkAllReadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkAllTopicReadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkAllUnreadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkEntryReadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkEntryUnreadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkTopicReadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiMarkTopicUnreadForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiRateEntryForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiRepliesForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiShowForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiSubscribeTopicForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiSummaryFeedbackForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiUnsubscribeTopicForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsApiViewForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsCreateForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsDestroyForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsDiscussionEntriesDestroyForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsDiscussionEntriesUpdateForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsIndexForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsReorderForGroupsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsUpdateForGroupsCmd(flags))
	return cmd
}
