// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsMembershipsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "memberships",
		Short: "Manage memberships",
	}

	cmd.AddCommand(newGroupsMembershipsGroupCreateCmd(flags))
	cmd.AddCommand(newGroupsMembershipsGroupDestroyForGroupsCmd(flags))
	cmd.AddCommand(newGroupsMembershipsGroupIndexCmd(flags))
	cmd.AddCommand(newGroupsMembershipsGroupShowForGroupsCmd(flags))
	cmd.AddCommand(newGroupsMembershipsGroupUpdateForGroupsCmd(flags))
	return cmd
}
