// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupCategoriesGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "groups",
		Short: "Groups serve as the data for a few different ideas in Canvas. The first is that they can be a community in the...",
	}

	cmd.AddCommand(newGroupCategoriesGroupsCategoriesCmd(flags))
	cmd.AddCommand(newGroupCategoriesGroupsCreateOtherCmd(flags))
	return cmd
}
