// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsContentMigrationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-migrations",
		Short: "API for accessing content migrations and migration issues",
	}

	cmd.AddCommand(newGroupsContentMigrationsAvailableMigratorsForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsContentListForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsCreateForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsIndexForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsMigrationIssuesIndexForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsMigrationIssuesShowForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsMigrationIssuesUpdateForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsShowForGroupsCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsUpdateForGroupsCmd(flags))
	return cmd
}
