// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsPagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "pages",
		Short: "Manage pages",
	}

	cmd.AddCommand(newGroupsPagesWikiApiCreateForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiDestroyForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiIndexForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiRevertForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiRevisionsForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiShowForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiShowRevisionForGroupsCmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiShowRevisionForGroups2Cmd(flags))
	cmd.AddCommand(newGroupsPagesWikiApiUpdateForGroupsCmd(flags))
	return cmd
}
