// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "groups",
		Short: "Groups serve as the data for a few different ideas in Canvas. The first is that they can be a community in the...",
	}

	cmd.AddCommand(newGroupsCreateOther2Cmd(flags))
	cmd.AddCommand(newGroupsDestroyCmd(flags))
	cmd.AddCommand(newGroupsShowCmd(flags))
	cmd.AddCommand(newGroupsUpdateCmd(flags))
	cmd.AddCommand(newGroupsActivityStreamCmd(flags))
	cmd.AddCommand(newGroupsAssignmentsCmd(flags))
	cmd.AddCommand(newGroupsCollaborationsCmd(flags))
	cmd.AddCommand(newGroupsConferencesCmd(flags))
	cmd.AddCommand(newGroupsContentExportsCmd(flags))
	cmd.AddCommand(newGroupsContentLicensesCmd(flags))
	cmd.AddCommand(newGroupsContentMigrationsCmd(flags))
	cmd.AddCommand(newGroupsDiscussionTopicsCmd(flags))
	cmd.AddCommand(newGroupsExternalFeedsCmd(flags))
	cmd.AddCommand(newGroupsExternalToolsCmd(flags))
	cmd.AddCommand(newGroupsFilesCmd(flags))
	cmd.AddCommand(newGroupsFoldersCmd(flags))
	cmd.AddCommand(newGroupsFrontPageCmd(flags))
	cmd.AddCommand(newGroupsInviteCmd(flags))
	cmd.AddCommand(newGroupsMediaAttachmentsCmd(flags))
	cmd.AddCommand(newGroupsMediaObjectsCmd(flags))
	cmd.AddCommand(newGroupsMembershipsCmd(flags))
	cmd.AddCommand(newGroupsPagesCmd(flags))
	cmd.AddCommand(newGroupsPermissionsCmd(flags))
	cmd.AddCommand(newGroupsPotentialCollaboratorsCmd(flags))
	cmd.AddCommand(newGroupsPreviewHtmlCmd(flags))
	cmd.AddCommand(newGroupsTabsCmd(flags))
	cmd.AddCommand(newGroupsUsageRightsCmd(flags))
	cmd.AddCommand(newGroupsUsersCmd(flags))
	return cmd
}
