// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newGroupsCreateOther2Cmd(flags *rootFlags) *cobra.Command {
	var bodyDescription string
	var bodyIsPublic bool
	var bodyJoinLevel string
	var bodyName string
	var bodySisGroupId string
	var bodyStorageQuotaMb int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create-other-2",
		Aliases: []string{"create"},
		Short: "Creates a new group. Groups created using the '/api/v1/groups/' endpoint will be community groups.",
		Example: "  canvas-cli groups create-other-2",
		Annotations: map[string]string{"pp:endpoint": "groups.create-other-2", "pp:method": "POST", "pp:path": "/groups"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/groups"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyIsPublic != false {
					body["is_public"] = bodyIsPublic
				}
				if bodyJoinLevel != "" {
					body["join_level"] = bodyJoinLevel
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodySisGroupId != "" {
					body["sis_group_id"] = bodySisGroupId
				}
				if bodyStorageQuotaMb != 0 {
					body["storage_quota_mb"] = bodyStorageQuotaMb
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "groups",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description of the group")
	cmd.Flags().BoolVar(&bodyIsPublic, "is-public", false, "whether the group is public (applies only to community groups)")
	cmd.Flags().StringVar(&bodyJoinLevel, "join-level", "", "Join level")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the group")
	cmd.Flags().StringVar(&bodySisGroupId, "sis-group-id", "", "The sis ID of the group. Must have manage_sis permission to set.")
	cmd.Flags().IntVar(&bodyStorageQuotaMb, "storage-quota-mb", 0, "The allowed file storage for the group, in megabytes. This parameter is ignored if the caller does not have the...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
