// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGroupsDiscussionTopicsIndexForGroupsCmd(flags *rootFlags) *cobra.Command {
	var flagInclude string
	var flagOrderBy string
	var flagScope string
	var flagOnlyAnnouncements bool
	var flagFilterBy string
	var flagSearchTerm string
	var flagExcludeContextModuleLockedTopics bool
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "index-for-groups <group_id>",
		Short: "Returns the paginated list of discussion topics for this course or group.",
		Example: "  canvas-cli groups discussion-topics index-for-groups 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "discussion-topics.index-for-groups", "pp:method": "GET", "pp:path": "/groups/{group_id}/discussion_topics", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("order-by") {
				allowedOrderBy := []string{ "position", "recent_activity", "title" }
				validOrderBy := false
				for _, v := range allowedOrderBy {
					if flagOrderBy == v {
						validOrderBy = true
						break
					}
				}
				if !validOrderBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order-by", flagOrderBy, allowedOrderBy)
				}
			}
			if cmd.Flags().Changed("scope") {
				allowedScope := []string{ "locked", "unlocked", "pinned", "unpinned" }
				validScope := false
				for _, v := range allowedScope {
					if flagScope == v {
						validScope = true
						break
					}
				}
				if !validScope {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "scope", flagScope, allowedScope)
				}
			}
			if cmd.Flags().Changed("filter-by") {
				allowedFilterBy := []string{ "all", "unread" }
				validFilterBy := false
				for _, v := range allowedFilterBy {
					if flagFilterBy == v {
						validFilterBy = true
						break
					}
				}
				if !validFilterBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "filter-by", flagFilterBy, allowedFilterBy)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/groups/{group_id}/discussion_topics"
			path = replacePathParam(path, "group_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "discussion-topics", path, map[string]string{
				"include": fmt.Sprintf("%v", flagInclude),
				"order_by": fmt.Sprintf("%v", flagOrderBy),
				"scope": fmt.Sprintf("%v", flagScope),
				"only_announcements": fmt.Sprintf("%v", flagOnlyAnnouncements),
				"filter_by": fmt.Sprintf("%v", flagFilterBy),
				"search_term": fmt.Sprintf("%v", flagSearchTerm),
				"exclude_context_module_locked_topics": fmt.Sprintf("%v", flagExcludeContextModuleLockedTopics),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'all_dates', 'sections', 'sections_user_count', 'overrides'] If 'all_dates' is passed, all dates associated...")
	cmd.Flags().StringVar(&flagOrderBy, "order-by", "", "Determines the order of the discussion topic list. Defaults to 'position'. (one of: position, recent_activity, title)")
	cmd.Flags().StringVar(&flagScope, "scope", "", "Only return discussion topics in the given state(s). Defaults to including all topics. Filtering is done after... (one of: locked, unlocked, pinned, unpinned)")
	cmd.Flags().BoolVar(&flagOnlyAnnouncements, "only-announcements", false, "Return announcements instead of discussion topics. Defaults to false")
	cmd.Flags().StringVar(&flagFilterBy, "filter-by", "", "The state of the discussion topic to return. Currently only supports unread state. (one of: all, unread)")
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial title of the discussion topics to match and return.")
	cmd.Flags().BoolVar(&flagExcludeContextModuleLockedTopics, "exclude-context-module-locked-topics", false, "For students, exclude topics that are locked by module progression. Defaults to false.")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
