// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newJwtsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyCanvasAudience bool
	var bodyContextId int
	var bodyContextType string
	var bodyContextUuid string
	var bodyWorkflows string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a unique JWT for use with other Canvas services Generates a different JWT each time it's called. Each JWT...",
		Example: "  canvas-pp-cli jwts create",
		Annotations: map[string]string{"pp:endpoint": "jwts.create", "pp:method": "POST", "pp:path": "/jwts"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/jwts"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCanvasAudience != false {
					body["canvas_audience"] = bodyCanvasAudience
				}
				if bodyContextId != 0 {
					body["context_id"] = bodyContextId
				}
				if bodyContextType != "" {
					body["context_type"] = bodyContextType
				}
				if bodyContextUuid != "" {
					body["context_uuid"] = bodyContextUuid
				}
				if bodyWorkflows != "" {
					var parsedWorkflows any
					if err := json.Unmarshal([]byte(bodyWorkflows), &parsedWorkflows); err != nil {
						return fmt.Errorf("parsing --workflows JSON: %w", err)
					}
					body["workflows"] = parsedWorkflows
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "jwts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&bodyCanvasAudience, "canvas-audience", false, "Defaults to true. If false, the JWT will be signed, but not encrypted, for use in downstream services. The default...")
	cmd.Flags().IntVar(&bodyContextId, "context-id", 0, "The id of the context to generate the JWT for, in case the workflow requires it.")
	cmd.Flags().StringVar(&bodyContextType, "context-type", "", "The type of the context to generate the JWT for, in case the workflow requires it. Case insensitive.")
	cmd.Flags().StringVar(&bodyContextUuid, "context-uuid", "", "The uuid of the context to generate the JWT for, in case the workflow requires it. Note that context_id and...")
	cmd.Flags().StringVar(&bodyWorkflows, "workflows", "", "[String] Adds additional data to the JWT to be used by the consuming service workflow")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
