// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMediaAttachmentsMediaObjectsIndexOther2Cmd(flags *rootFlags) *cobra.Command {
	var flagSort string
	var flagOrder string
	var flagExclude string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "media-objects-index-other-2",
		Aliases: []string{"list"},
		Short: "Returns media objects created by the user making the request. When using the second version, returns media objects...",
		Example: "  canvas-pp-cli media-attachments media-objects-index-other-2",
		Annotations: map[string]string{"pp:endpoint": "media-attachments.media-objects-index-other-2", "pp:method": "GET", "pp:path": "/media_attachments", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{ "title", "created_at" }
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{ "asc", "desc" }
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/media_attachments"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "media-attachments", path, map[string]string{
				"sort": fmt.Sprintf("%v", flagSort),
				"order": fmt.Sprintf("%v", flagOrder),
				"exclude": fmt.Sprintf("%v", flagExclude),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSort, "sort", "", "Field to sort on. Default is 'title' title:: sorts on user_entered_title if available, title if not. created_at::... (one of: title, created_at)")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Sort direction. Default is 'asc' (one of: asc, desc)")
	cmd.Flags().StringVar(&flagExclude, "exclude", "", "[String, 'sources'|'tracks'] Array of data to exclude. By excluding 'sources' and 'tracks', the api will not need to...")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
