// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMediaObjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "media-objects",
		Short: "When you upload or record webcam video/audio to kaltura, it makes a Media Object",
	}

	cmd.AddCommand(newMediaObjectsIndexOtherCmd(flags))
	cmd.AddCommand(newMediaObjectsUpdateOtherCmd(flags))
	cmd.AddCommand(newMediaObjectsMediaTracksCmd(flags))
	return cmd
}
