// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPlannerIndexOtherCmd(flags *rootFlags) *cobra.Command {
	var flagStartDate string
	var flagEndDate string
	var flagContextCodes string
	var flagObservedUserId string
	var flagFilter string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "index-other",
		Aliases: []string{"list"},
		Short: "Retrieve the paginated list of objects to be shown on the planner for the current user with the associated planner...",
		Example: "  canvas-cli planner index-other",
		Annotations: map[string]string{"pp:endpoint": "planner.index-other", "pp:method": "GET", "pp:path": "/planner/items", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("filter") {
				allowedFilter := []string{ "new_activity" }
				validFilter := false
				for _, v := range allowedFilter {
					if flagFilter == v {
						validFilter = true
						break
					}
				}
				if !validFilter {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "filter", flagFilter, allowedFilter)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/planner/items"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "planner", path, map[string]string{
				"start_date": fmt.Sprintf("%v", flagStartDate),
				"end_date": fmt.Sprintf("%v", flagEndDate),
				"context_codes": fmt.Sprintf("%v", flagContextCodes),
				"observed_user_id": fmt.Sprintf("%v", flagObservedUserId),
				"filter": fmt.Sprintf("%v", flagFilter),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Only return items starting from the given date. The value should be formatted as: yyyy-mm-dd or ISO 8601...")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Only return items up to the given date. The value should be formatted as: yyyy-mm-dd or ISO 8601 YYYY-MM-DDTHH:MM:SSZ.")
	cmd.Flags().StringVar(&flagContextCodes, "context-codes", "", "[String] List of context codes of courses and/or groups whose items you want to see. If not specified, defaults to...")
	cmd.Flags().StringVar(&flagObservedUserId, "observed-user-id", "", "Return planner items for the given observed user. Must be accompanied by context_codes[]. The user making the...")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "Only return items that are completed (includes items with planner_override.marked_complete = true or submitted... (one of: new_activity)")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
