// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newSectionsAssignmentsSubmissionsCreateOtherCmd(flags *rootFlags) *cobra.Command {
	var bodyComment string
	var bodySubmission string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "submissions-create-other <section_id> <assignment_id>",
		Short: "Make a submission for an assignment. You must be actively enrolled as a student in the course/section to do this....",
		Example: "  canvas-cli sections assignments submissions-create-other 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assignments.submissions-create-other", "pp:method": "POST", "pp:path": "/sections/{section_id}/assignments/{assignment_id}/submissions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("submission") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "submission")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sections/{section_id}/assignments/{assignment_id}/submissions"
			path = replacePathParam(path, "section_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("assignment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "assignment_id"))
			}
			path = replacePathParam(path, "assignment_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyComment != "" {
					var parsedComment any
					if err := json.Unmarshal([]byte(bodyComment), &parsedComment); err != nil {
						return fmt.Errorf("parsing --comment JSON: %w", err)
					}
					body["comment"] = parsedComment
				}
				if bodySubmission != "" {
					var parsedSubmission any
					if err := json.Unmarshal([]byte(bodySubmission), &parsedSubmission); err != nil {
						return fmt.Errorf("parsing --submission JSON: %w", err)
					}
					body["submission"] = parsedSubmission
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "assignments",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyComment, "comment", "", "Comment")
	cmd.Flags().StringVar(&bodySubmission, "submission", "", "Submission")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
