// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSectionsUsersSectionsCmd(flags *rootFlags) *cobra.Command {
	var flagSearchTerm string
	var flagInclude string
	var flagExcludeInactive bool
	var flagEnrollmentType string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "sections <id>",
		Aliases: []string{"get"},
		Short: "Returns a paginated list of users in the section.",
		Example: "  canvas-cli sections users sections 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "users.sections", "pp:method": "GET", "pp:path": "/sections/{id}/users", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("enrollment-type") {
				allowedEnrollmentType := []string{ "teacher", "student", "ta", "observer", "designer" }
				validEnrollmentType := false
				for _, v := range allowedEnrollmentType {
					if flagEnrollmentType == v {
						validEnrollmentType = true
						break
					}
				}
				if !validEnrollmentType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "enrollment-type", flagEnrollmentType, allowedEnrollmentType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sections/{id}/users"
			path = replacePathParam(path, "id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "users", path, map[string]string{
				"search_term": fmt.Sprintf("%v", flagSearchTerm),
				"include": fmt.Sprintf("%v", flagInclude),
				"exclude_inactive": fmt.Sprintf("%v", flagExcludeInactive),
				"enrollment_type": fmt.Sprintf("%v", flagEnrollmentType),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial name or full ID of the users to match and return in the results list. Must be at least 2 characters.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'avatar_url'] 'avatar_url': Include users' avatar_urls.")
	cmd.Flags().BoolVar(&flagExcludeInactive, "exclude-inactive", false, "Whether to filter out inactive users from the results. Defaults to false unless explicitly provided.")
	cmd.Flags().StringVar(&flagEnrollmentType, "enrollment-type", "", "When set, only return users with the specified enrollment type for the given section. (one of: teacher, student, ta, observer, designer)")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
