// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersObserverPairingCodesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "observer-pairing-codes",
		Short: "Manage observer pairing codes",
	}

	cmd.AddCommand(newUsersObserverPairingCodesApiCreateCmd(flags))
	return cmd
}
