// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsersMissingSubmissionsServiceCredentialsCmd(flags *rootFlags) *cobra.Command {
	var flagObservedUserId string
	var flagInclude string
	var flagFilter string
	var flagCourseIds string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "service-credentials <user_id>",
		Aliases: []string{"get"},
		Short: "A paginated list of past-due assignments for which the student does not have a submission. The user sending the...",
		Example: "  canvas-pp-cli users missing-submissions service-credentials 550e8400-e29b-41d4-a716-446655440000 --course-ids example-value",
		Annotations: map[string]string{"pp:endpoint": "missing-submissions.service-credentials", "pp:method": "GET", "pp:path": "/users/{user_id}/missing_submissions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("course-ids") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "course-ids")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/{user_id}/missing_submissions"
			path = replacePathParam(path, "user_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "missing-submissions", path, map[string]string{
				"observed_user_id": fmt.Sprintf("%v", flagObservedUserId),
				"include": fmt.Sprintf("%v", flagInclude),
				"filter": fmt.Sprintf("%v", flagFilter),
				"course_ids": fmt.Sprintf("%v", flagCourseIds),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagObservedUserId, "observed-user-id", "", "Return missing submissions for the given observed user. Must be accompanied by course_ids[]. The user making the...")
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'planner_overrides'|'course'] 'planner_overrides':: Optionally include the assignment's associated planner...")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "[String, 'submittable'|'current_grading_period'] 'submittable':: Only return assignments that the current user can...")
	cmd.Flags().StringVar(&flagCourseIds, "course-ids", "", "[String] Optionally restricts the list of past-due assignments to only those associated with the specified course...")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
