// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersPageViewsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "page-views",
		Short: "Manage page views",
	}

	cmd.AddCommand(newUsersPageViewsIndexCmd(flags))
	cmd.AddCommand(newUsersPageViewsPollQueryCmd(flags))
	cmd.AddCommand(newUsersPageViewsQueryCmd(flags))
	cmd.AddCommand(newUsersPageViewsQueryResultsCmd(flags))
	return cmd
}
