// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsersFilesMetadataSaxDocApiIndexForUsersCmd(flags *rootFlags) *cobra.Command {
	var flagContentTypes string
	var flagExcludeContentTypes string
	var flagSearchTerm string
	var flagInclude string
	var flagOnly string
	var flagSort string
	var flagOrder string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "metadata-sax-doc-api-index-for-users <user_id>",
		Aliases: []string{"get"},
		Short: "Returns the paginated list of files for the folder or course.",
		Example: "  canvas-cli users files metadata-sax-doc-api-index-for-users 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "files.metadata-sax-doc-api-index-for-users", "pp:method": "GET", "pp:path": "/users/{user_id}/files", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{ "name", "size", "created_at", "updated_at", "content_type", "user" }
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{ "asc", "desc" }
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/{user_id}/files"
			path = replacePathParam(path, "user_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "files", path, map[string]string{
				"content_types": fmt.Sprintf("%v", flagContentTypes),
				"exclude_content_types": fmt.Sprintf("%v", flagExcludeContentTypes),
				"search_term": fmt.Sprintf("%v", flagSearchTerm),
				"include": fmt.Sprintf("%v", flagInclude),
				"only": fmt.Sprintf("%v", flagOnly),
				"sort": fmt.Sprintf("%v", flagSort),
				"order": fmt.Sprintf("%v", flagOrder),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagContentTypes, "content-types", "", "[String] Filter results by content-type. You can specify type/subtype pairs (e.g., 'image/jpeg'), or simply types...")
	cmd.Flags().StringVar(&flagExcludeContentTypes, "exclude-content-types", "", "[String] Exclude given content-types from your results. You can specify type/subtype pairs (e.g., 'image/jpeg'), or...")
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial name of the files to match and return.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "['user'] Array of additional information to include. 'user':: the user who uploaded the file or last edited its...")
	cmd.Flags().StringVar(&flagOnly, "only", "", "[Array] Array of information to restrict to. Overrides include[] 'names':: only returns file name information")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort results by this field. Defaults to 'name'. Note that `sort=user` implies `include[]=user`. (one of: name, size, created_at, updated_at, content_type, user)")
	cmd.Flags().StringVar(&flagOrder, "order", "", "The sorting order. Defaults to 'asc'. (one of: asc, desc)")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
