// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsersFavoritesListFavoriteCoursesCmd(flags *rootFlags) *cobra.Command {
	var flagExcludeBlueprintCourses bool

	cmd := &cobra.Command{
		Use:   "favorites-list-favorite-courses",
		Short: "Retrieve the paginated list of favorite courses for the current user. If the user has not chosen any favorites, then...",
		Example: "  canvas-pp-cli users favorites-list-favorite-courses",
		Annotations: map[string]string{"pp:endpoint": "users.favorites-list-favorite-courses", "pp:method": "GET", "pp:path": "/users/self/favorites/courses", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/self/favorites/courses"
			params := map[string]string{}
			if flagExcludeBlueprintCourses != false {
				params["exclude_blueprint_courses"] = fmt.Sprintf("%v", flagExcludeBlueprintCourses)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "users", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&flagExcludeBlueprintCourses, "exclude-blueprint-courses", false, "When set, only return courses that are not configured as blueprint courses.")

	return cmd
}
