// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersFeaturesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "features",
		Short: "Manage features",
	}

	cmd.AddCommand(newUsersFeaturesFlagsDeleteForUsersCmd(flags))
	cmd.AddCommand(newUsersFeaturesFlagsEnabledForUsersCmd(flags))
	cmd.AddCommand(newUsersFeaturesFlagsIndexForUsersCmd(flags))
	cmd.AddCommand(newUsersFeaturesFlagsShowForUsersCmd(flags))
	cmd.AddCommand(newUsersFeaturesFlagsUpdateForUsersCmd(flags))
	return cmd
}
