// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersContentExportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-exports",
		Short: "Copyright (C) 2011 - present Instructure, Inc. This file is part of Canvas. Canvas is free software: you can...",
	}

	cmd.AddCommand(newUsersContentExportsApiCreateForUsersCmd(flags))
	cmd.AddCommand(newUsersContentExportsApiIndexForUsersCmd(flags))
	cmd.AddCommand(newUsersContentExportsApiShowForUsersCmd(flags))
	return cmd
}
