// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersTokensCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tokens",
		Short: "Manage tokens",
	}

	cmd.AddCommand(newUsersTokensCreateCmd(flags))
	cmd.AddCommand(newUsersTokensDestroyCmd(flags))
	cmd.AddCommand(newUsersTokensShowCmd(flags))
	cmd.AddCommand(newUsersTokensUpdateCmd(flags))
	return cmd
}
