// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsersEnrollmentsApiIndexForUsersCmd(flags *rootFlags) *cobra.Command {
	var flagType string
	var flagRole string
	var flagState string
	var flagInclude string
	var flagUserId string
	var flagGradingPeriodId string
	var flagEnrollmentTermId string
	var flagSisAccountId string
	var flagSisCourseId string
	var flagSisSectionId string
	var flagSisUserId string
	var flagCreatedForSisId string
	var flagPage string
	var flagPerPage int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "api-index-for-users <user_id>",
		Aliases: []string{"get"},
		Short: "Depending on the URL given, return a paginated list of either (1) all of the enrollments in a course, (2) all of the...",
		Example: "  canvas-cli users enrollments api-index-for-users 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "enrollments.api-index-for-users", "pp:method": "GET", "pp:path": "/users/{user_id}/enrollments", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/{user_id}/enrollments"
			path = replacePathParam(path, "user_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "enrollments", path, map[string]string{
				"type": fmt.Sprintf("%v", flagType),
				"role": fmt.Sprintf("%v", flagRole),
				"state": fmt.Sprintf("%v", flagState),
				"include": fmt.Sprintf("%v", flagInclude),
				"user_id": fmt.Sprintf("%v", flagUserId),
				"grading_period_id": fmt.Sprintf("%v", flagGradingPeriodId),
				"enrollment_term_id": fmt.Sprintf("%v", flagEnrollmentTermId),
				"sis_account_id": fmt.Sprintf("%v", flagSisAccountId),
				"sis_course_id": fmt.Sprintf("%v", flagSisCourseId),
				"sis_section_id": fmt.Sprintf("%v", flagSisSectionId),
				"sis_user_id": fmt.Sprintf("%v", flagSisUserId),
				"created_for_sis_id": fmt.Sprintf("%v", flagCreatedForSisId),
				"page": fmt.Sprintf("%v", flagPage),
				"per_page": fmt.Sprintf("%v", flagPerPage),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "", "[String] A list of enrollment types to return. Accepted values are 'StudentEnrollment', 'TeacherEnrollment',...")
	cmd.Flags().StringVar(&flagRole, "role", "", "[String] A list of enrollment roles to return. Accepted values include course-level roles created by the...")
	cmd.Flags().StringVar(&flagState, "state", "", "[String, 'active'|'invited'|'creation_pending'|'deleted'|'rejected'|'completed'|'inactive'|'current_and_invited'|'cur...")
	cmd.Flags().StringVar(&flagInclude, "include", "", "[String, 'avatar_url'|'group_ids'|'locked'|'observed_users'|'can_be_removed'|'uuid'|'current_points'] Array of...")
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "Filter by user_id (only valid for course or section enrollment queries). If set to the current user's id, this is a...")
	cmd.Flags().StringVar(&flagGradingPeriodId, "grading-period-id", "", "Return grades for the given grading_period. If this parameter is not specified, the returned grades will be for the...")
	cmd.Flags().StringVar(&flagEnrollmentTermId, "enrollment-term-id", "", "Returns only enrollments for the specified enrollment term. This parameter only applies to the user enrollments...")
	cmd.Flags().StringVar(&flagSisAccountId, "sis-account-id", "", "[String] Returns only enrollments for the specified SIS account ID(s). Does not look into sub_accounts. May pass in...")
	cmd.Flags().StringVar(&flagSisCourseId, "sis-course-id", "", "[String] Returns only enrollments matching the specified SIS course ID(s). May pass in array or string.")
	cmd.Flags().StringVar(&flagSisSectionId, "sis-section-id", "", "[String] Returns only section enrollments matching the specified SIS section ID(s). May pass in array or string.")
	cmd.Flags().StringVar(&flagSisUserId, "sis-user-id", "", "[String] Returns only enrollments for the specified SIS user ID(s). May pass in array or string.")
	cmd.Flags().StringVar(&flagCreatedForSisId, "created-for-sis-id", "", "[Boolean] If sis_user_id is present and created_for_sis_id is true, Returns only enrollments for the specified SIS...")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of items to return per page. Defaults to 10. Maximum is 100.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
