// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUsersCommunicationChannelsNotificationPreferencesShowForUsers2Cmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "notification-preferences-show-for-users-2 <address> <type> <notification> <user_id>",
		Short: "Fetch the preference for the given notification for the given communication channel",
		Example: "  canvas-pp-cli users communication-channels notification-preferences-show-for-users-2 example-value example-value example-value 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "communication-channels.notification-preferences-show-for-users-2", "pp:method": "GET", "pp:path": "/users/{user_id}/communication_channels/{type}/{address}/notification_preferences/{notification}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/{user_id}/communication_channels/{type}/{address}/notification_preferences/{notification}"
			path = replacePathParam(path, "address", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("type is required\nUsage: %s <%s>", cmd.CommandPath(), "type"))
			}
			path = replacePathParam(path, "type", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("notification is required\nUsage: %s <%s>", cmd.CommandPath(), "notification"))
			}
			path = replacePathParam(path, "notification", args[2])
			if len(args) < 4 {
				return usageErr(fmt.Errorf("user_id is required\nUsage: %s <%s>", cmd.CommandPath(), "user_id"))
			}
			path = replacePathParam(path, "user_id", args[3])
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "communication-channels", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	return cmd
}
