// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersPlannerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "planner",
		Short: "API for listing learning objects to display on the student planner and calendar",
	}

	cmd.AddCommand(newUsersPlannerIndexForUsersCmd(flags))
	return cmd
}
