// Copyright 2026 simple-scalable-solutions. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersContentMigrationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-migrations",
		Short: "API for accessing content migrations and migration issues",
	}

	cmd.AddCommand(newUsersContentMigrationsAvailableMigratorsForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsContentListForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsCreateForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsIndexForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsMigrationIssuesIndexForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsMigrationIssuesShowForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsMigrationIssuesUpdateForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsShowForUsersCmd(flags))
	cmd.AddCommand(newUsersContentMigrationsUpdateForUsersCmd(flags))
	return cmd
}
